apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-kiali-bridge
  labels:
    app: skupper-kiali-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skupper-kiali-bridge
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
      labels:
        app: skupper-kiali-bridge
    spec:
      containers:
      - image: ${IMAGE_NAME}
        imagePullPolicy: Always
        name: main
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /etc/messaging/
          name: skupper-local-client
        args:
        - '-messaging-config=/etc/messaging/connect.json'
        - '-debug'
        - '-extension=skupper'
      volumes:
      - name: skupper-local-client
        secret:
          defaultMode: 420
          secretName: skupper-local-client

