// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type Site struct {
	Name      string
	Identity  string
	Type      string
	Location  string
	Provider  string
	Version   string
	Platform  string
	Namespace string
}

const (
	SiteName mgmt.Field[Site] = iota
	SiteIdentity
	SiteTypeField
	SiteLocation
	SiteProvider
	SiteVersion
	SitePlatform
	SiteNamespace
)

var SiteType = mgmt.NewType("io.skupper.router.site", "site", false, []string{"QUERY", "READ"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: false, Update: false, Default: "io.skupper.router.site", HasDefault: true},
	{Name: "location", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "provider", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "version", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "platform", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "namespace", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
})

var SiteAllFields = mgmt.Fields(SiteName, SiteIdentity, SiteTypeField, SiteLocation, SiteProvider, SiteVersion, SitePlatform, SiteNamespace)

var SiteCreateFields mgmt.FieldSet[Site]

var SiteUpdateFields mgmt.FieldSet[Site]

func (*Site) ManagementType() *mgmt.Type { return SiteType }

func (e *Site) SetManagementField(field mgmt.Field[Site], value any) error {
	switch field {
	case SiteName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SiteType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case SiteIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SiteType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case SiteTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SiteType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case SiteLocation:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SiteType.Name, "location", value)
		}
		e.Location = decoded
		return nil
	case SiteProvider:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SiteType.Name, "provider", value)
		}
		e.Provider = decoded
		return nil
	case SiteVersion:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SiteType.Name, "version", value)
		}
		e.Version = decoded
		return nil
	case SitePlatform:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SiteType.Name, "platform", value)
		}
		e.Platform = decoded
		return nil
	case SiteNamespace:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SiteType.Name, "namespace", value)
		}
		e.Namespace = decoded
		return nil
	}
	return mgmt.DecodeError(SiteType.Name, "<unknown>", value)
}

func (e *Site) ManagementValue(field mgmt.Field[Site]) any {
	switch field {
	case SiteName:
		return e.Name
	case SiteIdentity:
		return e.Identity
	case SiteTypeField:
		return e.Type
	case SiteLocation:
		return e.Location
	case SiteProvider:
		return e.Provider
	case SiteVersion:
		return e.Version
	case SitePlatform:
		return e.Platform
	case SiteNamespace:
		return e.Namespace
	}
	return nil
}

func (e *Site) Equal(other *Site, fields mgmt.FieldSet[Site]) bool {
	if fields.Has(SiteName) && e.Name != other.Name {
		return false
	}
	if fields.Has(SiteIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(SiteTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(SiteLocation) && e.Location != other.Location {
		return false
	}
	if fields.Has(SiteProvider) && e.Provider != other.Provider {
		return false
	}
	if fields.Has(SiteVersion) && e.Version != other.Version {
		return false
	}
	if fields.Has(SitePlatform) && e.Platform != other.Platform {
		return false
	}
	if fields.Has(SiteNamespace) && e.Namespace != other.Namespace {
		return false
	}
	return true
}

func (e *Site) Diff(other *Site, fields mgmt.FieldSet[Site]) mgmt.FieldSet[Site] {
	var result mgmt.FieldSet[Site]
	if fields.Has(SiteName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(SiteName))
	}
	if fields.Has(SiteIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(SiteIdentity))
	}
	if fields.Has(SiteTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(SiteTypeField))
	}
	if fields.Has(SiteLocation) && e.Location != other.Location {
		result = result.Union(mgmt.Fields(SiteLocation))
	}
	if fields.Has(SiteProvider) && e.Provider != other.Provider {
		result = result.Union(mgmt.Fields(SiteProvider))
	}
	if fields.Has(SiteVersion) && e.Version != other.Version {
		result = result.Union(mgmt.Fields(SiteVersion))
	}
	if fields.Has(SitePlatform) && e.Platform != other.Platform {
		result = result.Union(mgmt.Fields(SitePlatform))
	}
	if fields.Has(SiteNamespace) && e.Namespace != other.Namespace {
		result = result.Union(mgmt.Fields(SiteNamespace))
	}
	return result
}

func (e *Site) ApplyDefaults(present mgmt.FieldSet[Site]) {
	if !present.Has(SiteTypeField) {
		e.Type = "io.skupper.router.site"
	}
}

func (e *Site) NonZeroFields() mgmt.FieldSet[Site] {
	var result mgmt.FieldSet[Site]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(SiteName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(SiteIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(SiteTypeField))
	}
	if e.Location != "" {
		result = result.Union(mgmt.Fields(SiteLocation))
	}
	if e.Provider != "" {
		result = result.Union(mgmt.Fields(SiteProvider))
	}
	if e.Version != "" {
		result = result.Union(mgmt.Fields(SiteVersion))
	}
	if e.Platform != "" {
		result = result.Union(mgmt.Fields(SitePlatform))
	}
	if e.Namespace != "" {
		result = result.Union(mgmt.Fields(SiteNamespace))
	}
	return result
}
