// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type AutoLink struct {
	Name            string
	Identity        string
	Type            string
	Address         string
	Direction       Direction
	ContainerId     string
	Connection      string
	ExternalAddress string
	LinkRef         string
	OperStatus      AutoLinkOperStatus
	LastError       string
}

const (
	AutoLinkName mgmt.Field[AutoLink] = iota
	AutoLinkIdentity
	AutoLinkTypeField
	AutoLinkAddress
	AutoLinkDirection
	AutoLinkContainerId
	AutoLinkConnection
	AutoLinkExternalAddress
	AutoLinkLinkRef
	AutoLinkOperStatusField
	AutoLinkLastError
)

var AutoLinkType = mgmt.NewType("io.skupper.router.router.config.autoLink", "autoLink", true, []string{"QUERY", "READ", "CREATE", "DELETE"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: true, Update: false, Default: "io.skupper.router.router.config.autoLink", HasDefault: true},
	{Name: "address", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "direction", Kind: mgmt.StringAttribute, Required: true, Create: true, Update: false, Enum: directionValues},
	{Name: "containerId", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "connection", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "externalAddress", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "linkRef", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "operStatus", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false, Enum: autoLinkOperStatusValues},
	{Name: "lastError", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
})

var AutoLinkAllFields = mgmt.Fields(AutoLinkName, AutoLinkIdentity, AutoLinkTypeField, AutoLinkAddress, AutoLinkDirection, AutoLinkContainerId, AutoLinkConnection, AutoLinkExternalAddress, AutoLinkLinkRef, AutoLinkOperStatusField, AutoLinkLastError)

var AutoLinkCreateFields = mgmt.Fields(AutoLinkName, AutoLinkTypeField, AutoLinkAddress, AutoLinkDirection, AutoLinkContainerId, AutoLinkConnection, AutoLinkExternalAddress)

var AutoLinkUpdateFields mgmt.FieldSet[AutoLink]

func (*AutoLink) ManagementType() *mgmt.Type { return AutoLinkType }

func (e *AutoLink) SetManagementField(field mgmt.Field[AutoLink], value any) error {
	switch field {
	case AutoLinkName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(AutoLinkType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case AutoLinkIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(AutoLinkType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case AutoLinkTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(AutoLinkType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case AutoLinkAddress:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(AutoLinkType.Name, "address", value)
		}
		e.Address = decoded
		return nil
	case AutoLinkDirection:
		decoded, ok := mgmt.AsEnum(value, directionValues)
		if !ok {
			return mgmt.DecodeError(AutoLinkType.Name, "direction", value)
		}
		e.Direction = Direction(decoded)
		return nil
	case AutoLinkContainerId:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(AutoLinkType.Name, "containerId", value)
		}
		e.ContainerId = decoded
		return nil
	case AutoLinkConnection:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(AutoLinkType.Name, "connection", value)
		}
		e.Connection = decoded
		return nil
	case AutoLinkExternalAddress:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(AutoLinkType.Name, "externalAddress", value)
		}
		e.ExternalAddress = decoded
		return nil
	case AutoLinkLinkRef:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(AutoLinkType.Name, "linkRef", value)
		}
		e.LinkRef = decoded
		return nil
	case AutoLinkOperStatusField:
		decoded, ok := mgmt.AsEnum(value, autoLinkOperStatusValues)
		if !ok {
			return mgmt.DecodeError(AutoLinkType.Name, "operStatus", value)
		}
		e.OperStatus = AutoLinkOperStatus(decoded)
		return nil
	case AutoLinkLastError:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(AutoLinkType.Name, "lastError", value)
		}
		e.LastError = decoded
		return nil
	}
	return mgmt.DecodeError(AutoLinkType.Name, "<unknown>", value)
}

func (e *AutoLink) ManagementValue(field mgmt.Field[AutoLink]) any {
	switch field {
	case AutoLinkName:
		return e.Name
	case AutoLinkIdentity:
		return e.Identity
	case AutoLinkTypeField:
		return e.Type
	case AutoLinkAddress:
		return e.Address
	case AutoLinkDirection:
		return string(e.Direction)
	case AutoLinkContainerId:
		return e.ContainerId
	case AutoLinkConnection:
		return e.Connection
	case AutoLinkExternalAddress:
		return e.ExternalAddress
	case AutoLinkLinkRef:
		return e.LinkRef
	case AutoLinkOperStatusField:
		return string(e.OperStatus)
	case AutoLinkLastError:
		return e.LastError
	}
	return nil
}

func (e *AutoLink) Equal(other *AutoLink, fields mgmt.FieldSet[AutoLink]) bool {
	if fields.Has(AutoLinkName) && e.Name != other.Name {
		return false
	}
	if fields.Has(AutoLinkIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(AutoLinkTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(AutoLinkAddress) && e.Address != other.Address {
		return false
	}
	if fields.Has(AutoLinkDirection) && e.Direction != other.Direction {
		return false
	}
	if fields.Has(AutoLinkContainerId) && e.ContainerId != other.ContainerId {
		return false
	}
	if fields.Has(AutoLinkConnection) && e.Connection != other.Connection {
		return false
	}
	if fields.Has(AutoLinkExternalAddress) && e.ExternalAddress != other.ExternalAddress {
		return false
	}
	if fields.Has(AutoLinkLinkRef) && e.LinkRef != other.LinkRef {
		return false
	}
	if fields.Has(AutoLinkOperStatusField) && e.OperStatus != other.OperStatus {
		return false
	}
	if fields.Has(AutoLinkLastError) && e.LastError != other.LastError {
		return false
	}
	return true
}

func (e *AutoLink) Diff(other *AutoLink, fields mgmt.FieldSet[AutoLink]) mgmt.FieldSet[AutoLink] {
	var result mgmt.FieldSet[AutoLink]
	if fields.Has(AutoLinkName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(AutoLinkName))
	}
	if fields.Has(AutoLinkIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(AutoLinkIdentity))
	}
	if fields.Has(AutoLinkTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(AutoLinkTypeField))
	}
	if fields.Has(AutoLinkAddress) && e.Address != other.Address {
		result = result.Union(mgmt.Fields(AutoLinkAddress))
	}
	if fields.Has(AutoLinkDirection) && e.Direction != other.Direction {
		result = result.Union(mgmt.Fields(AutoLinkDirection))
	}
	if fields.Has(AutoLinkContainerId) && e.ContainerId != other.ContainerId {
		result = result.Union(mgmt.Fields(AutoLinkContainerId))
	}
	if fields.Has(AutoLinkConnection) && e.Connection != other.Connection {
		result = result.Union(mgmt.Fields(AutoLinkConnection))
	}
	if fields.Has(AutoLinkExternalAddress) && e.ExternalAddress != other.ExternalAddress {
		result = result.Union(mgmt.Fields(AutoLinkExternalAddress))
	}
	if fields.Has(AutoLinkLinkRef) && e.LinkRef != other.LinkRef {
		result = result.Union(mgmt.Fields(AutoLinkLinkRef))
	}
	if fields.Has(AutoLinkOperStatusField) && e.OperStatus != other.OperStatus {
		result = result.Union(mgmt.Fields(AutoLinkOperStatusField))
	}
	if fields.Has(AutoLinkLastError) && e.LastError != other.LastError {
		result = result.Union(mgmt.Fields(AutoLinkLastError))
	}
	return result
}

func (e *AutoLink) ApplyDefaults(present mgmt.FieldSet[AutoLink]) {
	if !present.Has(AutoLinkTypeField) {
		e.Type = "io.skupper.router.router.config.autoLink"
	}
}

func (e *AutoLink) NonZeroFields() mgmt.FieldSet[AutoLink] {
	var result mgmt.FieldSet[AutoLink]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(AutoLinkName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(AutoLinkIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(AutoLinkTypeField))
	}
	if e.Address != "" {
		result = result.Union(mgmt.Fields(AutoLinkAddress))
	}
	if e.Direction != "" {
		result = result.Union(mgmt.Fields(AutoLinkDirection))
	}
	if e.ContainerId != "" {
		result = result.Union(mgmt.Fields(AutoLinkContainerId))
	}
	if e.Connection != "" {
		result = result.Union(mgmt.Fields(AutoLinkConnection))
	}
	if e.ExternalAddress != "" {
		result = result.Union(mgmt.Fields(AutoLinkExternalAddress))
	}
	if e.LinkRef != "" {
		result = result.Union(mgmt.Fields(AutoLinkLinkRef))
	}
	if e.OperStatus != "" {
		result = result.Union(mgmt.Fields(AutoLinkOperStatusField))
	}
	if e.LastError != "" {
		result = result.Union(mgmt.Fields(AutoLinkLastError))
	}
	return result
}
