// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type Router struct {
	Name                      string
	Identity                  string
	Type                      string
	Id                        string
	VanId                     string
	Mode                      RouterMode
	Area                      string
	Version                   string
	HostName                  string
	HelloIntervalSeconds      int64
	HelloMaxAgeSeconds        int64
	RaIntervalSeconds         int64
	RaIntervalFluxSeconds     int64
	RemoteLsMaxAgeSeconds     int64
	UnreachableHoldoffSeconds int64
	WorkerThreads             int64
	DebugDumpFile             string
	SaslConfigDir             string
	SaslConfigName            string
	TimestampsInUtc           bool
	TimestampFormat           string
	DefaultDistribution       Distribution
	Metadata                  string
	DataConnectionCount       string
	DropTcpConnections        bool
}

const (
	RouterName mgmt.Field[Router] = iota
	RouterIdentity
	RouterTypeField
	RouterId
	RouterVanId
	RouterModeField
	RouterArea
	RouterVersion
	RouterHostName
	RouterHelloIntervalSeconds
	RouterHelloMaxAgeSeconds
	RouterRaIntervalSeconds
	RouterRaIntervalFluxSeconds
	RouterRemoteLsMaxAgeSeconds
	RouterUnreachableHoldoffSeconds
	RouterWorkerThreads
	RouterDebugDumpFile
	RouterSaslConfigDir
	RouterSaslConfigName
	RouterTimestampsInUtc
	RouterTimestampFormat
	RouterDefaultDistribution
	RouterMetadata
	RouterDataConnectionCount
	RouterDropTcpConnections
)

var RouterType = mgmt.NewType("io.skupper.router.router", "router", false, []string{"QUERY", "READ"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: false, Update: false, Default: "io.skupper.router.router", HasDefault: true},
	{Name: "id", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "vanId", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "mode", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false, Default: RouterMode("standalone"), HasDefault: true, Enum: routerModeValues},
	{Name: "area", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false, Default: "0", HasDefault: true},
	{Name: "version", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "hostName", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "helloIntervalSeconds", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false, Default: int64(1), HasDefault: true},
	{Name: "helloMaxAgeSeconds", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false, Default: int64(3), HasDefault: true},
	{Name: "raIntervalSeconds", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false, Default: int64(30), HasDefault: true},
	{Name: "raIntervalFluxSeconds", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false, Default: int64(4), HasDefault: true},
	{Name: "remoteLsMaxAgeSeconds", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false, Default: int64(60), HasDefault: true},
	{Name: "unreachableHoldoffSeconds", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false, Default: int64(1), HasDefault: true},
	{Name: "workerThreads", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false, Default: int64(4), HasDefault: true},
	{Name: "debugDumpFile", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "saslConfigDir", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "saslConfigName", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false, Default: "skrouterd", HasDefault: true},
	{Name: "timestampsInUTC", Kind: mgmt.BoolAttribute, Required: false, Create: false, Update: false},
	{Name: "timestampFormat", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "defaultDistribution", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false, Default: Distribution("balanced"), HasDefault: true, Enum: distributionValues},
	{Name: "metadata", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "dataConnectionCount", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false, Default: "auto", HasDefault: true},
	{Name: "dropTcpConnections", Kind: mgmt.BoolAttribute, Required: false, Create: false, Update: false, Default: true, HasDefault: true},
})

var RouterAllFields = mgmt.Fields(RouterName, RouterIdentity, RouterTypeField, RouterId, RouterVanId, RouterModeField, RouterArea, RouterVersion, RouterHostName, RouterHelloIntervalSeconds, RouterHelloMaxAgeSeconds, RouterRaIntervalSeconds, RouterRaIntervalFluxSeconds, RouterRemoteLsMaxAgeSeconds, RouterUnreachableHoldoffSeconds, RouterWorkerThreads, RouterDebugDumpFile, RouterSaslConfigDir, RouterSaslConfigName, RouterTimestampsInUtc, RouterTimestampFormat, RouterDefaultDistribution, RouterMetadata, RouterDataConnectionCount, RouterDropTcpConnections)

var RouterCreateFields mgmt.FieldSet[Router]

var RouterUpdateFields mgmt.FieldSet[Router]

func (*Router) ManagementType() *mgmt.Type { return RouterType }

func (e *Router) SetManagementField(field mgmt.Field[Router], value any) error {
	switch field {
	case RouterName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case RouterIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case RouterTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case RouterId:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "id", value)
		}
		e.Id = decoded
		return nil
	case RouterVanId:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "vanId", value)
		}
		e.VanId = decoded
		return nil
	case RouterModeField:
		decoded, ok := mgmt.AsEnum(value, routerModeValues)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "mode", value)
		}
		e.Mode = RouterMode(decoded)
		return nil
	case RouterArea:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "area", value)
		}
		e.Area = decoded
		return nil
	case RouterVersion:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "version", value)
		}
		e.Version = decoded
		return nil
	case RouterHostName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "hostName", value)
		}
		e.HostName = decoded
		return nil
	case RouterHelloIntervalSeconds:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "helloIntervalSeconds", value)
		}
		e.HelloIntervalSeconds = decoded
		return nil
	case RouterHelloMaxAgeSeconds:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "helloMaxAgeSeconds", value)
		}
		e.HelloMaxAgeSeconds = decoded
		return nil
	case RouterRaIntervalSeconds:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "raIntervalSeconds", value)
		}
		e.RaIntervalSeconds = decoded
		return nil
	case RouterRaIntervalFluxSeconds:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "raIntervalFluxSeconds", value)
		}
		e.RaIntervalFluxSeconds = decoded
		return nil
	case RouterRemoteLsMaxAgeSeconds:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "remoteLsMaxAgeSeconds", value)
		}
		e.RemoteLsMaxAgeSeconds = decoded
		return nil
	case RouterUnreachableHoldoffSeconds:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "unreachableHoldoffSeconds", value)
		}
		e.UnreachableHoldoffSeconds = decoded
		return nil
	case RouterWorkerThreads:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "workerThreads", value)
		}
		e.WorkerThreads = decoded
		return nil
	case RouterDebugDumpFile:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "debugDumpFile", value)
		}
		e.DebugDumpFile = decoded
		return nil
	case RouterSaslConfigDir:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "saslConfigDir", value)
		}
		e.SaslConfigDir = decoded
		return nil
	case RouterSaslConfigName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "saslConfigName", value)
		}
		e.SaslConfigName = decoded
		return nil
	case RouterTimestampsInUtc:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "timestampsInUTC", value)
		}
		e.TimestampsInUtc = decoded
		return nil
	case RouterTimestampFormat:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "timestampFormat", value)
		}
		e.TimestampFormat = decoded
		return nil
	case RouterDefaultDistribution:
		decoded, ok := mgmt.AsEnum(value, distributionValues)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "defaultDistribution", value)
		}
		e.DefaultDistribution = Distribution(decoded)
		return nil
	case RouterMetadata:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "metadata", value)
		}
		e.Metadata = decoded
		return nil
	case RouterDataConnectionCount:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "dataConnectionCount", value)
		}
		e.DataConnectionCount = decoded
		return nil
	case RouterDropTcpConnections:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(RouterType.Name, "dropTcpConnections", value)
		}
		e.DropTcpConnections = decoded
		return nil
	}
	return mgmt.DecodeError(RouterType.Name, "<unknown>", value)
}

func (e *Router) ManagementValue(field mgmt.Field[Router]) any {
	switch field {
	case RouterName:
		return e.Name
	case RouterIdentity:
		return e.Identity
	case RouterTypeField:
		return e.Type
	case RouterId:
		return e.Id
	case RouterVanId:
		return e.VanId
	case RouterModeField:
		return string(e.Mode)
	case RouterArea:
		return e.Area
	case RouterVersion:
		return e.Version
	case RouterHostName:
		return e.HostName
	case RouterHelloIntervalSeconds:
		return e.HelloIntervalSeconds
	case RouterHelloMaxAgeSeconds:
		return e.HelloMaxAgeSeconds
	case RouterRaIntervalSeconds:
		return e.RaIntervalSeconds
	case RouterRaIntervalFluxSeconds:
		return e.RaIntervalFluxSeconds
	case RouterRemoteLsMaxAgeSeconds:
		return e.RemoteLsMaxAgeSeconds
	case RouterUnreachableHoldoffSeconds:
		return e.UnreachableHoldoffSeconds
	case RouterWorkerThreads:
		return e.WorkerThreads
	case RouterDebugDumpFile:
		return e.DebugDumpFile
	case RouterSaslConfigDir:
		return e.SaslConfigDir
	case RouterSaslConfigName:
		return e.SaslConfigName
	case RouterTimestampsInUtc:
		return e.TimestampsInUtc
	case RouterTimestampFormat:
		return e.TimestampFormat
	case RouterDefaultDistribution:
		return string(e.DefaultDistribution)
	case RouterMetadata:
		return e.Metadata
	case RouterDataConnectionCount:
		return e.DataConnectionCount
	case RouterDropTcpConnections:
		return e.DropTcpConnections
	}
	return nil
}

func (e *Router) Equal(other *Router, fields mgmt.FieldSet[Router]) bool {
	if fields.Has(RouterName) && e.Name != other.Name {
		return false
	}
	if fields.Has(RouterIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(RouterTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(RouterId) && e.Id != other.Id {
		return false
	}
	if fields.Has(RouterVanId) && e.VanId != other.VanId {
		return false
	}
	if fields.Has(RouterModeField) && e.Mode != other.Mode {
		return false
	}
	if fields.Has(RouterArea) && e.Area != other.Area {
		return false
	}
	if fields.Has(RouterVersion) && e.Version != other.Version {
		return false
	}
	if fields.Has(RouterHostName) && e.HostName != other.HostName {
		return false
	}
	if fields.Has(RouterHelloIntervalSeconds) && e.HelloIntervalSeconds != other.HelloIntervalSeconds {
		return false
	}
	if fields.Has(RouterHelloMaxAgeSeconds) && e.HelloMaxAgeSeconds != other.HelloMaxAgeSeconds {
		return false
	}
	if fields.Has(RouterRaIntervalSeconds) && e.RaIntervalSeconds != other.RaIntervalSeconds {
		return false
	}
	if fields.Has(RouterRaIntervalFluxSeconds) && e.RaIntervalFluxSeconds != other.RaIntervalFluxSeconds {
		return false
	}
	if fields.Has(RouterRemoteLsMaxAgeSeconds) && e.RemoteLsMaxAgeSeconds != other.RemoteLsMaxAgeSeconds {
		return false
	}
	if fields.Has(RouterUnreachableHoldoffSeconds) && e.UnreachableHoldoffSeconds != other.UnreachableHoldoffSeconds {
		return false
	}
	if fields.Has(RouterWorkerThreads) && e.WorkerThreads != other.WorkerThreads {
		return false
	}
	if fields.Has(RouterDebugDumpFile) && e.DebugDumpFile != other.DebugDumpFile {
		return false
	}
	if fields.Has(RouterSaslConfigDir) && e.SaslConfigDir != other.SaslConfigDir {
		return false
	}
	if fields.Has(RouterSaslConfigName) && e.SaslConfigName != other.SaslConfigName {
		return false
	}
	if fields.Has(RouterTimestampsInUtc) && e.TimestampsInUtc != other.TimestampsInUtc {
		return false
	}
	if fields.Has(RouterTimestampFormat) && e.TimestampFormat != other.TimestampFormat {
		return false
	}
	if fields.Has(RouterDefaultDistribution) && e.DefaultDistribution != other.DefaultDistribution {
		return false
	}
	if fields.Has(RouterMetadata) && e.Metadata != other.Metadata {
		return false
	}
	if fields.Has(RouterDataConnectionCount) && e.DataConnectionCount != other.DataConnectionCount {
		return false
	}
	if fields.Has(RouterDropTcpConnections) && e.DropTcpConnections != other.DropTcpConnections {
		return false
	}
	return true
}

func (e *Router) Diff(other *Router, fields mgmt.FieldSet[Router]) mgmt.FieldSet[Router] {
	var result mgmt.FieldSet[Router]
	if fields.Has(RouterName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(RouterName))
	}
	if fields.Has(RouterIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(RouterIdentity))
	}
	if fields.Has(RouterTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(RouterTypeField))
	}
	if fields.Has(RouterId) && e.Id != other.Id {
		result = result.Union(mgmt.Fields(RouterId))
	}
	if fields.Has(RouterVanId) && e.VanId != other.VanId {
		result = result.Union(mgmt.Fields(RouterVanId))
	}
	if fields.Has(RouterModeField) && e.Mode != other.Mode {
		result = result.Union(mgmt.Fields(RouterModeField))
	}
	if fields.Has(RouterArea) && e.Area != other.Area {
		result = result.Union(mgmt.Fields(RouterArea))
	}
	if fields.Has(RouterVersion) && e.Version != other.Version {
		result = result.Union(mgmt.Fields(RouterVersion))
	}
	if fields.Has(RouterHostName) && e.HostName != other.HostName {
		result = result.Union(mgmt.Fields(RouterHostName))
	}
	if fields.Has(RouterHelloIntervalSeconds) && e.HelloIntervalSeconds != other.HelloIntervalSeconds {
		result = result.Union(mgmt.Fields(RouterHelloIntervalSeconds))
	}
	if fields.Has(RouterHelloMaxAgeSeconds) && e.HelloMaxAgeSeconds != other.HelloMaxAgeSeconds {
		result = result.Union(mgmt.Fields(RouterHelloMaxAgeSeconds))
	}
	if fields.Has(RouterRaIntervalSeconds) && e.RaIntervalSeconds != other.RaIntervalSeconds {
		result = result.Union(mgmt.Fields(RouterRaIntervalSeconds))
	}
	if fields.Has(RouterRaIntervalFluxSeconds) && e.RaIntervalFluxSeconds != other.RaIntervalFluxSeconds {
		result = result.Union(mgmt.Fields(RouterRaIntervalFluxSeconds))
	}
	if fields.Has(RouterRemoteLsMaxAgeSeconds) && e.RemoteLsMaxAgeSeconds != other.RemoteLsMaxAgeSeconds {
		result = result.Union(mgmt.Fields(RouterRemoteLsMaxAgeSeconds))
	}
	if fields.Has(RouterUnreachableHoldoffSeconds) && e.UnreachableHoldoffSeconds != other.UnreachableHoldoffSeconds {
		result = result.Union(mgmt.Fields(RouterUnreachableHoldoffSeconds))
	}
	if fields.Has(RouterWorkerThreads) && e.WorkerThreads != other.WorkerThreads {
		result = result.Union(mgmt.Fields(RouterWorkerThreads))
	}
	if fields.Has(RouterDebugDumpFile) && e.DebugDumpFile != other.DebugDumpFile {
		result = result.Union(mgmt.Fields(RouterDebugDumpFile))
	}
	if fields.Has(RouterSaslConfigDir) && e.SaslConfigDir != other.SaslConfigDir {
		result = result.Union(mgmt.Fields(RouterSaslConfigDir))
	}
	if fields.Has(RouterSaslConfigName) && e.SaslConfigName != other.SaslConfigName {
		result = result.Union(mgmt.Fields(RouterSaslConfigName))
	}
	if fields.Has(RouterTimestampsInUtc) && e.TimestampsInUtc != other.TimestampsInUtc {
		result = result.Union(mgmt.Fields(RouterTimestampsInUtc))
	}
	if fields.Has(RouterTimestampFormat) && e.TimestampFormat != other.TimestampFormat {
		result = result.Union(mgmt.Fields(RouterTimestampFormat))
	}
	if fields.Has(RouterDefaultDistribution) && e.DefaultDistribution != other.DefaultDistribution {
		result = result.Union(mgmt.Fields(RouterDefaultDistribution))
	}
	if fields.Has(RouterMetadata) && e.Metadata != other.Metadata {
		result = result.Union(mgmt.Fields(RouterMetadata))
	}
	if fields.Has(RouterDataConnectionCount) && e.DataConnectionCount != other.DataConnectionCount {
		result = result.Union(mgmt.Fields(RouterDataConnectionCount))
	}
	if fields.Has(RouterDropTcpConnections) && e.DropTcpConnections != other.DropTcpConnections {
		result = result.Union(mgmt.Fields(RouterDropTcpConnections))
	}
	return result
}

func (e *Router) ApplyDefaults(present mgmt.FieldSet[Router]) {
	if !present.Has(RouterTypeField) {
		e.Type = "io.skupper.router.router"
	}
	if !present.Has(RouterModeField) {
		e.Mode = RouterMode("standalone")
	}
	if !present.Has(RouterArea) {
		e.Area = "0"
	}
	if !present.Has(RouterHelloIntervalSeconds) {
		e.HelloIntervalSeconds = int64(1)
	}
	if !present.Has(RouterHelloMaxAgeSeconds) {
		e.HelloMaxAgeSeconds = int64(3)
	}
	if !present.Has(RouterRaIntervalSeconds) {
		e.RaIntervalSeconds = int64(30)
	}
	if !present.Has(RouterRaIntervalFluxSeconds) {
		e.RaIntervalFluxSeconds = int64(4)
	}
	if !present.Has(RouterRemoteLsMaxAgeSeconds) {
		e.RemoteLsMaxAgeSeconds = int64(60)
	}
	if !present.Has(RouterUnreachableHoldoffSeconds) {
		e.UnreachableHoldoffSeconds = int64(1)
	}
	if !present.Has(RouterWorkerThreads) {
		e.WorkerThreads = int64(4)
	}
	if !present.Has(RouterSaslConfigName) {
		e.SaslConfigName = "skrouterd"
	}
	if !present.Has(RouterDefaultDistribution) {
		e.DefaultDistribution = Distribution("balanced")
	}
	if !present.Has(RouterDataConnectionCount) {
		e.DataConnectionCount = "auto"
	}
	if !present.Has(RouterDropTcpConnections) {
		e.DropTcpConnections = true
	}
}

func (e *Router) NonZeroFields() mgmt.FieldSet[Router] {
	var result mgmt.FieldSet[Router]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(RouterName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(RouterIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(RouterTypeField))
	}
	if e.Id != "" {
		result = result.Union(mgmt.Fields(RouterId))
	}
	if e.VanId != "" {
		result = result.Union(mgmt.Fields(RouterVanId))
	}
	if e.Mode != "" {
		result = result.Union(mgmt.Fields(RouterModeField))
	}
	if e.Area != "" {
		result = result.Union(mgmt.Fields(RouterArea))
	}
	if e.Version != "" {
		result = result.Union(mgmt.Fields(RouterVersion))
	}
	if e.HostName != "" {
		result = result.Union(mgmt.Fields(RouterHostName))
	}
	if e.HelloIntervalSeconds != 0 {
		result = result.Union(mgmt.Fields(RouterHelloIntervalSeconds))
	}
	if e.HelloMaxAgeSeconds != 0 {
		result = result.Union(mgmt.Fields(RouterHelloMaxAgeSeconds))
	}
	if e.RaIntervalSeconds != 0 {
		result = result.Union(mgmt.Fields(RouterRaIntervalSeconds))
	}
	if e.RaIntervalFluxSeconds != 0 {
		result = result.Union(mgmt.Fields(RouterRaIntervalFluxSeconds))
	}
	if e.RemoteLsMaxAgeSeconds != 0 {
		result = result.Union(mgmt.Fields(RouterRemoteLsMaxAgeSeconds))
	}
	if e.UnreachableHoldoffSeconds != 0 {
		result = result.Union(mgmt.Fields(RouterUnreachableHoldoffSeconds))
	}
	if e.WorkerThreads != 0 {
		result = result.Union(mgmt.Fields(RouterWorkerThreads))
	}
	if e.DebugDumpFile != "" {
		result = result.Union(mgmt.Fields(RouterDebugDumpFile))
	}
	if e.SaslConfigDir != "" {
		result = result.Union(mgmt.Fields(RouterSaslConfigDir))
	}
	if e.SaslConfigName != "" {
		result = result.Union(mgmt.Fields(RouterSaslConfigName))
	}
	if e.TimestampsInUtc {
		result = result.Union(mgmt.Fields(RouterTimestampsInUtc))
	}
	if e.TimestampFormat != "" {
		result = result.Union(mgmt.Fields(RouterTimestampFormat))
	}
	if e.DefaultDistribution != "" {
		result = result.Union(mgmt.Fields(RouterDefaultDistribution))
	}
	if e.Metadata != "" {
		result = result.Union(mgmt.Fields(RouterMetadata))
	}
	if e.DataConnectionCount != "" {
		result = result.Union(mgmt.Fields(RouterDataConnectionCount))
	}
	if e.DropTcpConnections {
		result = result.Union(mgmt.Fields(RouterDropTcpConnections))
	}
	return result
}
