// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type ProxyProfile struct {
	Name     string
	Identity string
	Type     string
	Host     string
	Port     string
	Username string
	Password string
}

const (
	ProxyProfileName mgmt.Field[ProxyProfile] = iota
	ProxyProfileIdentity
	ProxyProfileTypeField
	ProxyProfileHost
	ProxyProfilePort
	ProxyProfileUsername
	ProxyProfilePassword
)

var ProxyProfileType = mgmt.NewType("io.skupper.router.proxyProfile", "proxyProfile", false, []string{"QUERY", "READ", "CREATE", "UPDATE", "DELETE"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: true, Update: false, Default: "io.skupper.router.proxyProfile", HasDefault: true},
	{Name: "host", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: true},
	{Name: "port", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: true},
	{Name: "username", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: true},
	{Name: "password", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: true},
})

var ProxyProfileAllFields = mgmt.Fields(ProxyProfileName, ProxyProfileIdentity, ProxyProfileTypeField, ProxyProfileHost, ProxyProfilePort, ProxyProfileUsername, ProxyProfilePassword)

var ProxyProfileCreateFields = mgmt.Fields(ProxyProfileName, ProxyProfileTypeField, ProxyProfileHost, ProxyProfilePort, ProxyProfileUsername, ProxyProfilePassword)

var ProxyProfileUpdateFields = mgmt.Fields(ProxyProfileHost, ProxyProfilePort, ProxyProfileUsername, ProxyProfilePassword)

func (*ProxyProfile) ManagementType() *mgmt.Type { return ProxyProfileType }

func (e *ProxyProfile) SetManagementField(field mgmt.Field[ProxyProfile], value any) error {
	switch field {
	case ProxyProfileName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ProxyProfileType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case ProxyProfileIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ProxyProfileType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case ProxyProfileTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ProxyProfileType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case ProxyProfileHost:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ProxyProfileType.Name, "host", value)
		}
		e.Host = decoded
		return nil
	case ProxyProfilePort:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ProxyProfileType.Name, "port", value)
		}
		e.Port = decoded
		return nil
	case ProxyProfileUsername:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ProxyProfileType.Name, "username", value)
		}
		e.Username = decoded
		return nil
	case ProxyProfilePassword:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ProxyProfileType.Name, "password", value)
		}
		e.Password = decoded
		return nil
	}
	return mgmt.DecodeError(ProxyProfileType.Name, "<unknown>", value)
}

func (e *ProxyProfile) ManagementValue(field mgmt.Field[ProxyProfile]) any {
	switch field {
	case ProxyProfileName:
		return e.Name
	case ProxyProfileIdentity:
		return e.Identity
	case ProxyProfileTypeField:
		return e.Type
	case ProxyProfileHost:
		return e.Host
	case ProxyProfilePort:
		return e.Port
	case ProxyProfileUsername:
		return e.Username
	case ProxyProfilePassword:
		return e.Password
	}
	return nil
}

func (e *ProxyProfile) Equal(other *ProxyProfile, fields mgmt.FieldSet[ProxyProfile]) bool {
	if fields.Has(ProxyProfileName) && e.Name != other.Name {
		return false
	}
	if fields.Has(ProxyProfileIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(ProxyProfileTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(ProxyProfileHost) && e.Host != other.Host {
		return false
	}
	if fields.Has(ProxyProfilePort) && e.Port != other.Port {
		return false
	}
	if fields.Has(ProxyProfileUsername) && e.Username != other.Username {
		return false
	}
	if fields.Has(ProxyProfilePassword) && e.Password != other.Password {
		return false
	}
	return true
}

func (e *ProxyProfile) Diff(other *ProxyProfile, fields mgmt.FieldSet[ProxyProfile]) mgmt.FieldSet[ProxyProfile] {
	var result mgmt.FieldSet[ProxyProfile]
	if fields.Has(ProxyProfileName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(ProxyProfileName))
	}
	if fields.Has(ProxyProfileIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(ProxyProfileIdentity))
	}
	if fields.Has(ProxyProfileTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(ProxyProfileTypeField))
	}
	if fields.Has(ProxyProfileHost) && e.Host != other.Host {
		result = result.Union(mgmt.Fields(ProxyProfileHost))
	}
	if fields.Has(ProxyProfilePort) && e.Port != other.Port {
		result = result.Union(mgmt.Fields(ProxyProfilePort))
	}
	if fields.Has(ProxyProfileUsername) && e.Username != other.Username {
		result = result.Union(mgmt.Fields(ProxyProfileUsername))
	}
	if fields.Has(ProxyProfilePassword) && e.Password != other.Password {
		result = result.Union(mgmt.Fields(ProxyProfilePassword))
	}
	return result
}

func (e *ProxyProfile) ApplyDefaults(present mgmt.FieldSet[ProxyProfile]) {
	if !present.Has(ProxyProfileTypeField) {
		e.Type = "io.skupper.router.proxyProfile"
	}
}

func (e *ProxyProfile) NonZeroFields() mgmt.FieldSet[ProxyProfile] {
	var result mgmt.FieldSet[ProxyProfile]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(ProxyProfileName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(ProxyProfileIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(ProxyProfileTypeField))
	}
	if e.Host != "" {
		result = result.Union(mgmt.Fields(ProxyProfileHost))
	}
	if e.Port != "" {
		result = result.Union(mgmt.Fields(ProxyProfilePort))
	}
	if e.Username != "" {
		result = result.Union(mgmt.Fields(ProxyProfileUsername))
	}
	if e.Password != "" {
		result = result.Union(mgmt.Fields(ProxyProfilePassword))
	}
	return result
}
