// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type ConfigAddress struct {
	Name         string
	Identity     string
	Type         string
	Prefix       string
	Pattern      string
	Distribution Distribution
	Priority     int64
}

const (
	ConfigAddressName mgmt.Field[ConfigAddress] = iota
	ConfigAddressIdentity
	ConfigAddressTypeField
	ConfigAddressPrefix
	ConfigAddressPattern
	ConfigAddressDistribution
	ConfigAddressPriority
)

var ConfigAddressType = mgmt.NewType("io.skupper.router.router.config.address", "address", true, []string{"QUERY", "READ", "CREATE", "DELETE"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: true, Update: false, Default: "io.skupper.router.router.config.address", HasDefault: true},
	{Name: "prefix", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "pattern", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "distribution", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: Distribution("balanced"), HasDefault: true, Enum: distributionValues},
	{Name: "priority", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false},
})

var ConfigAddressAllFields = mgmt.Fields(ConfigAddressName, ConfigAddressIdentity, ConfigAddressTypeField, ConfigAddressPrefix, ConfigAddressPattern, ConfigAddressDistribution, ConfigAddressPriority)

var ConfigAddressCreateFields = mgmt.Fields(ConfigAddressName, ConfigAddressTypeField, ConfigAddressPrefix, ConfigAddressPattern, ConfigAddressDistribution, ConfigAddressPriority)

var ConfigAddressUpdateFields mgmt.FieldSet[ConfigAddress]

func (*ConfigAddress) ManagementType() *mgmt.Type { return ConfigAddressType }

func (e *ConfigAddress) SetManagementField(field mgmt.Field[ConfigAddress], value any) error {
	switch field {
	case ConfigAddressName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConfigAddressType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case ConfigAddressIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConfigAddressType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case ConfigAddressTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConfigAddressType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case ConfigAddressPrefix:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConfigAddressType.Name, "prefix", value)
		}
		e.Prefix = decoded
		return nil
	case ConfigAddressPattern:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConfigAddressType.Name, "pattern", value)
		}
		e.Pattern = decoded
		return nil
	case ConfigAddressDistribution:
		decoded, ok := mgmt.AsEnum(value, distributionValues)
		if !ok {
			return mgmt.DecodeError(ConfigAddressType.Name, "distribution", value)
		}
		e.Distribution = Distribution(decoded)
		return nil
	case ConfigAddressPriority:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ConfigAddressType.Name, "priority", value)
		}
		e.Priority = decoded
		return nil
	}
	return mgmt.DecodeError(ConfigAddressType.Name, "<unknown>", value)
}

func (e *ConfigAddress) ManagementValue(field mgmt.Field[ConfigAddress]) any {
	switch field {
	case ConfigAddressName:
		return e.Name
	case ConfigAddressIdentity:
		return e.Identity
	case ConfigAddressTypeField:
		return e.Type
	case ConfigAddressPrefix:
		return e.Prefix
	case ConfigAddressPattern:
		return e.Pattern
	case ConfigAddressDistribution:
		return string(e.Distribution)
	case ConfigAddressPriority:
		return e.Priority
	}
	return nil
}

func (e *ConfigAddress) Equal(other *ConfigAddress, fields mgmt.FieldSet[ConfigAddress]) bool {
	if fields.Has(ConfigAddressName) && e.Name != other.Name {
		return false
	}
	if fields.Has(ConfigAddressIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(ConfigAddressTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(ConfigAddressPrefix) && e.Prefix != other.Prefix {
		return false
	}
	if fields.Has(ConfigAddressPattern) && e.Pattern != other.Pattern {
		return false
	}
	if fields.Has(ConfigAddressDistribution) && e.Distribution != other.Distribution {
		return false
	}
	if fields.Has(ConfigAddressPriority) && e.Priority != other.Priority {
		return false
	}
	return true
}

func (e *ConfigAddress) Diff(other *ConfigAddress, fields mgmt.FieldSet[ConfigAddress]) mgmt.FieldSet[ConfigAddress] {
	var result mgmt.FieldSet[ConfigAddress]
	if fields.Has(ConfigAddressName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(ConfigAddressName))
	}
	if fields.Has(ConfigAddressIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(ConfigAddressIdentity))
	}
	if fields.Has(ConfigAddressTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(ConfigAddressTypeField))
	}
	if fields.Has(ConfigAddressPrefix) && e.Prefix != other.Prefix {
		result = result.Union(mgmt.Fields(ConfigAddressPrefix))
	}
	if fields.Has(ConfigAddressPattern) && e.Pattern != other.Pattern {
		result = result.Union(mgmt.Fields(ConfigAddressPattern))
	}
	if fields.Has(ConfigAddressDistribution) && e.Distribution != other.Distribution {
		result = result.Union(mgmt.Fields(ConfigAddressDistribution))
	}
	if fields.Has(ConfigAddressPriority) && e.Priority != other.Priority {
		result = result.Union(mgmt.Fields(ConfigAddressPriority))
	}
	return result
}

func (e *ConfigAddress) ApplyDefaults(present mgmt.FieldSet[ConfigAddress]) {
	if !present.Has(ConfigAddressTypeField) {
		e.Type = "io.skupper.router.router.config.address"
	}
	if !present.Has(ConfigAddressDistribution) {
		e.Distribution = Distribution("balanced")
	}
}

func (e *ConfigAddress) NonZeroFields() mgmt.FieldSet[ConfigAddress] {
	var result mgmt.FieldSet[ConfigAddress]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(ConfigAddressName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(ConfigAddressIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(ConfigAddressTypeField))
	}
	if e.Prefix != "" {
		result = result.Union(mgmt.Fields(ConfigAddressPrefix))
	}
	if e.Pattern != "" {
		result = result.Union(mgmt.Fields(ConfigAddressPattern))
	}
	if e.Distribution != "" {
		result = result.Union(mgmt.Fields(ConfigAddressDistribution))
	}
	if e.Priority != 0 {
		result = result.Union(mgmt.Fields(ConfigAddressPriority))
	}
	return result
}
