// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type Listener struct {
	Name                           string
	Identity                       string
	Type                           string
	Host                           string
	Port                           string
	SocketAddressFamily            SocketAddressFamily
	Role                           Role
	Cost                           int64
	SslProfile                     string
	SaslMechanisms                 string
	AuthenticatePeer               bool
	RequireEncryption              bool
	RequireSsl                     bool
	MaxFrameSize                   int64
	MaxSessions                    int64
	MaxSessionFrames               int64
	IdleTimeoutSeconds             int64
	InitialHandshakeTimeoutSeconds int64
	StripAnnotations               StripAnnotations
	LinkCapacity                   int64
	FailoverUrls                   string
	Healthz                        bool
	Metrics                        bool
	Websockets                     bool
	Http                           bool
	HttpRootDir                    string
	MessageLoggingComponents       string
	PolicyVhost                    string
	OpenProperties                 map[string]any
}

const (
	ListenerName mgmt.Field[Listener] = iota
	ListenerIdentity
	ListenerTypeField
	ListenerHost
	ListenerPort
	ListenerSocketAddressFamily
	ListenerRole
	ListenerCost
	ListenerSslProfile
	ListenerSaslMechanisms
	ListenerAuthenticatePeer
	ListenerRequireEncryption
	ListenerRequireSsl
	ListenerMaxFrameSize
	ListenerMaxSessions
	ListenerMaxSessionFrames
	ListenerIdleTimeoutSeconds
	ListenerInitialHandshakeTimeoutSeconds
	ListenerStripAnnotations
	ListenerLinkCapacity
	ListenerFailoverUrls
	ListenerHealthz
	ListenerMetrics
	ListenerWebsockets
	ListenerHttp
	ListenerHttpRootDir
	ListenerMessageLoggingComponents
	ListenerPolicyVhost
	ListenerOpenProperties
)

var ListenerType = mgmt.NewType("io.skupper.router.listener", "listener", false, []string{"QUERY", "READ", "CREATE", "DELETE"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: true, Update: false, Default: "io.skupper.router.listener", HasDefault: true},
	{Name: "host", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: "", HasDefault: true},
	{Name: "port", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: "amqp", HasDefault: true},
	{Name: "socketAddressFamily", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Enum: socketAddressFamilyValues},
	{Name: "role", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: Role("normal"), HasDefault: true, Enum: roleValues},
	{Name: "cost", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false, Default: int64(1), HasDefault: true},
	{Name: "sslProfile", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "saslMechanisms", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "authenticatePeer", Kind: mgmt.BoolAttribute, Required: false, Create: true, Update: false, Default: false, HasDefault: true},
	{Name: "requireEncryption", Kind: mgmt.BoolAttribute, Required: false, Create: true, Update: false, Default: false, HasDefault: true},
	{Name: "requireSsl", Kind: mgmt.BoolAttribute, Required: false, Create: true, Update: false, Default: false, HasDefault: true},
	{Name: "maxFrameSize", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false, Default: int64(16384), HasDefault: true},
	{Name: "maxSessions", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false, Default: int64(32768), HasDefault: true},
	{Name: "maxSessionFrames", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false},
	{Name: "idleTimeoutSeconds", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false, Default: int64(16), HasDefault: true},
	{Name: "initialHandshakeTimeoutSeconds", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false, Default: int64(0), HasDefault: true},
	{Name: "stripAnnotations", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: StripAnnotations("both"), HasDefault: true, Enum: stripAnnotationsValues},
	{Name: "linkCapacity", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false},
	{Name: "failoverUrls", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "healthz", Kind: mgmt.BoolAttribute, Required: false, Create: true, Update: false, Default: true, HasDefault: true},
	{Name: "metrics", Kind: mgmt.BoolAttribute, Required: false, Create: true, Update: false, Default: true, HasDefault: true},
	{Name: "websockets", Kind: mgmt.BoolAttribute, Required: false, Create: true, Update: false, Default: true, HasDefault: true},
	{Name: "http", Kind: mgmt.BoolAttribute, Required: false, Create: true, Update: false, Default: false, HasDefault: true},
	{Name: "httpRootDir", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "messageLoggingComponents", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: "none", HasDefault: true},
	{Name: "policyVhost", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "openProperties", Kind: mgmt.MapAttribute, Required: false, Create: true, Update: false},
})

var ListenerAllFields = mgmt.Fields(ListenerName, ListenerIdentity, ListenerTypeField, ListenerHost, ListenerPort, ListenerSocketAddressFamily, ListenerRole, ListenerCost, ListenerSslProfile, ListenerSaslMechanisms, ListenerAuthenticatePeer, ListenerRequireEncryption, ListenerRequireSsl, ListenerMaxFrameSize, ListenerMaxSessions, ListenerMaxSessionFrames, ListenerIdleTimeoutSeconds, ListenerInitialHandshakeTimeoutSeconds, ListenerStripAnnotations, ListenerLinkCapacity, ListenerFailoverUrls, ListenerHealthz, ListenerMetrics, ListenerWebsockets, ListenerHttp, ListenerHttpRootDir, ListenerMessageLoggingComponents, ListenerPolicyVhost, ListenerOpenProperties)

var ListenerCreateFields = mgmt.Fields(ListenerName, ListenerTypeField, ListenerHost, ListenerPort, ListenerSocketAddressFamily, ListenerRole, ListenerCost, ListenerSslProfile, ListenerSaslMechanisms, ListenerAuthenticatePeer, ListenerRequireEncryption, ListenerRequireSsl, ListenerMaxFrameSize, ListenerMaxSessions, ListenerMaxSessionFrames, ListenerIdleTimeoutSeconds, ListenerInitialHandshakeTimeoutSeconds, ListenerStripAnnotations, ListenerLinkCapacity, ListenerFailoverUrls, ListenerHealthz, ListenerMetrics, ListenerWebsockets, ListenerHttp, ListenerHttpRootDir, ListenerMessageLoggingComponents, ListenerPolicyVhost, ListenerOpenProperties)

var ListenerUpdateFields mgmt.FieldSet[Listener]

func (*Listener) ManagementType() *mgmt.Type { return ListenerType }

func (e *Listener) SetManagementField(field mgmt.Field[Listener], value any) error {
	switch field {
	case ListenerName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case ListenerIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case ListenerTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case ListenerHost:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "host", value)
		}
		e.Host = decoded
		return nil
	case ListenerPort:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "port", value)
		}
		e.Port = decoded
		return nil
	case ListenerSocketAddressFamily:
		decoded, ok := mgmt.AsEnum(value, socketAddressFamilyValues)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "socketAddressFamily", value)
		}
		e.SocketAddressFamily = SocketAddressFamily(decoded)
		return nil
	case ListenerRole:
		decoded, ok := mgmt.AsEnum(value, roleValues)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "role", value)
		}
		e.Role = Role(decoded)
		return nil
	case ListenerCost:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "cost", value)
		}
		e.Cost = decoded
		return nil
	case ListenerSslProfile:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "sslProfile", value)
		}
		e.SslProfile = decoded
		return nil
	case ListenerSaslMechanisms:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "saslMechanisms", value)
		}
		e.SaslMechanisms = decoded
		return nil
	case ListenerAuthenticatePeer:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "authenticatePeer", value)
		}
		e.AuthenticatePeer = decoded
		return nil
	case ListenerRequireEncryption:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "requireEncryption", value)
		}
		e.RequireEncryption = decoded
		return nil
	case ListenerRequireSsl:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "requireSsl", value)
		}
		e.RequireSsl = decoded
		return nil
	case ListenerMaxFrameSize:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "maxFrameSize", value)
		}
		e.MaxFrameSize = decoded
		return nil
	case ListenerMaxSessions:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "maxSessions", value)
		}
		e.MaxSessions = decoded
		return nil
	case ListenerMaxSessionFrames:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "maxSessionFrames", value)
		}
		e.MaxSessionFrames = decoded
		return nil
	case ListenerIdleTimeoutSeconds:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "idleTimeoutSeconds", value)
		}
		e.IdleTimeoutSeconds = decoded
		return nil
	case ListenerInitialHandshakeTimeoutSeconds:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "initialHandshakeTimeoutSeconds", value)
		}
		e.InitialHandshakeTimeoutSeconds = decoded
		return nil
	case ListenerStripAnnotations:
		decoded, ok := mgmt.AsEnum(value, stripAnnotationsValues)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "stripAnnotations", value)
		}
		e.StripAnnotations = StripAnnotations(decoded)
		return nil
	case ListenerLinkCapacity:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "linkCapacity", value)
		}
		e.LinkCapacity = decoded
		return nil
	case ListenerFailoverUrls:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "failoverUrls", value)
		}
		e.FailoverUrls = decoded
		return nil
	case ListenerHealthz:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "healthz", value)
		}
		e.Healthz = decoded
		return nil
	case ListenerMetrics:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "metrics", value)
		}
		e.Metrics = decoded
		return nil
	case ListenerWebsockets:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "websockets", value)
		}
		e.Websockets = decoded
		return nil
	case ListenerHttp:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "http", value)
		}
		e.Http = decoded
		return nil
	case ListenerHttpRootDir:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "httpRootDir", value)
		}
		e.HttpRootDir = decoded
		return nil
	case ListenerMessageLoggingComponents:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "messageLoggingComponents", value)
		}
		e.MessageLoggingComponents = decoded
		return nil
	case ListenerPolicyVhost:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "policyVhost", value)
		}
		e.PolicyVhost = decoded
		return nil
	case ListenerOpenProperties:
		decoded, ok := mgmt.AsMap(value)
		if !ok {
			return mgmt.DecodeError(ListenerType.Name, "openProperties", value)
		}
		e.OpenProperties = decoded
		return nil
	}
	return mgmt.DecodeError(ListenerType.Name, "<unknown>", value)
}

func (e *Listener) ManagementValue(field mgmt.Field[Listener]) any {
	switch field {
	case ListenerName:
		return e.Name
	case ListenerIdentity:
		return e.Identity
	case ListenerTypeField:
		return e.Type
	case ListenerHost:
		return e.Host
	case ListenerPort:
		return e.Port
	case ListenerSocketAddressFamily:
		return string(e.SocketAddressFamily)
	case ListenerRole:
		return string(e.Role)
	case ListenerCost:
		return e.Cost
	case ListenerSslProfile:
		return e.SslProfile
	case ListenerSaslMechanisms:
		return e.SaslMechanisms
	case ListenerAuthenticatePeer:
		return e.AuthenticatePeer
	case ListenerRequireEncryption:
		return e.RequireEncryption
	case ListenerRequireSsl:
		return e.RequireSsl
	case ListenerMaxFrameSize:
		return e.MaxFrameSize
	case ListenerMaxSessions:
		return e.MaxSessions
	case ListenerMaxSessionFrames:
		return e.MaxSessionFrames
	case ListenerIdleTimeoutSeconds:
		return e.IdleTimeoutSeconds
	case ListenerInitialHandshakeTimeoutSeconds:
		return e.InitialHandshakeTimeoutSeconds
	case ListenerStripAnnotations:
		return string(e.StripAnnotations)
	case ListenerLinkCapacity:
		return e.LinkCapacity
	case ListenerFailoverUrls:
		return e.FailoverUrls
	case ListenerHealthz:
		return e.Healthz
	case ListenerMetrics:
		return e.Metrics
	case ListenerWebsockets:
		return e.Websockets
	case ListenerHttp:
		return e.Http
	case ListenerHttpRootDir:
		return e.HttpRootDir
	case ListenerMessageLoggingComponents:
		return e.MessageLoggingComponents
	case ListenerPolicyVhost:
		return e.PolicyVhost
	case ListenerOpenProperties:
		return e.OpenProperties
	}
	return nil
}

func (e *Listener) Equal(other *Listener, fields mgmt.FieldSet[Listener]) bool {
	if fields.Has(ListenerName) && e.Name != other.Name {
		return false
	}
	if fields.Has(ListenerIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(ListenerTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(ListenerHost) && e.Host != other.Host {
		return false
	}
	if fields.Has(ListenerPort) && e.Port != other.Port {
		return false
	}
	if fields.Has(ListenerSocketAddressFamily) && e.SocketAddressFamily != other.SocketAddressFamily {
		return false
	}
	if fields.Has(ListenerRole) && e.Role != other.Role {
		return false
	}
	if fields.Has(ListenerCost) && e.Cost != other.Cost {
		return false
	}
	if fields.Has(ListenerSslProfile) && e.SslProfile != other.SslProfile {
		return false
	}
	if fields.Has(ListenerSaslMechanisms) && e.SaslMechanisms != other.SaslMechanisms {
		return false
	}
	if fields.Has(ListenerAuthenticatePeer) && e.AuthenticatePeer != other.AuthenticatePeer {
		return false
	}
	if fields.Has(ListenerRequireEncryption) && e.RequireEncryption != other.RequireEncryption {
		return false
	}
	if fields.Has(ListenerRequireSsl) && e.RequireSsl != other.RequireSsl {
		return false
	}
	if fields.Has(ListenerMaxFrameSize) && e.MaxFrameSize != other.MaxFrameSize {
		return false
	}
	if fields.Has(ListenerMaxSessions) && e.MaxSessions != other.MaxSessions {
		return false
	}
	if fields.Has(ListenerMaxSessionFrames) && e.MaxSessionFrames != other.MaxSessionFrames {
		return false
	}
	if fields.Has(ListenerIdleTimeoutSeconds) && e.IdleTimeoutSeconds != other.IdleTimeoutSeconds {
		return false
	}
	if fields.Has(ListenerInitialHandshakeTimeoutSeconds) && e.InitialHandshakeTimeoutSeconds != other.InitialHandshakeTimeoutSeconds {
		return false
	}
	if fields.Has(ListenerStripAnnotations) && e.StripAnnotations != other.StripAnnotations {
		return false
	}
	if fields.Has(ListenerLinkCapacity) && e.LinkCapacity != other.LinkCapacity {
		return false
	}
	if fields.Has(ListenerFailoverUrls) && e.FailoverUrls != other.FailoverUrls {
		return false
	}
	if fields.Has(ListenerHealthz) && e.Healthz != other.Healthz {
		return false
	}
	if fields.Has(ListenerMetrics) && e.Metrics != other.Metrics {
		return false
	}
	if fields.Has(ListenerWebsockets) && e.Websockets != other.Websockets {
		return false
	}
	if fields.Has(ListenerHttp) && e.Http != other.Http {
		return false
	}
	if fields.Has(ListenerHttpRootDir) && e.HttpRootDir != other.HttpRootDir {
		return false
	}
	if fields.Has(ListenerMessageLoggingComponents) && e.MessageLoggingComponents != other.MessageLoggingComponents {
		return false
	}
	if fields.Has(ListenerPolicyVhost) && e.PolicyVhost != other.PolicyVhost {
		return false
	}
	if fields.Has(ListenerOpenProperties) && !mgmt.EqualValues(e.OpenProperties, other.OpenProperties) {
		return false
	}
	return true
}

func (e *Listener) Diff(other *Listener, fields mgmt.FieldSet[Listener]) mgmt.FieldSet[Listener] {
	var result mgmt.FieldSet[Listener]
	if fields.Has(ListenerName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(ListenerName))
	}
	if fields.Has(ListenerIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(ListenerIdentity))
	}
	if fields.Has(ListenerTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(ListenerTypeField))
	}
	if fields.Has(ListenerHost) && e.Host != other.Host {
		result = result.Union(mgmt.Fields(ListenerHost))
	}
	if fields.Has(ListenerPort) && e.Port != other.Port {
		result = result.Union(mgmt.Fields(ListenerPort))
	}
	if fields.Has(ListenerSocketAddressFamily) && e.SocketAddressFamily != other.SocketAddressFamily {
		result = result.Union(mgmt.Fields(ListenerSocketAddressFamily))
	}
	if fields.Has(ListenerRole) && e.Role != other.Role {
		result = result.Union(mgmt.Fields(ListenerRole))
	}
	if fields.Has(ListenerCost) && e.Cost != other.Cost {
		result = result.Union(mgmt.Fields(ListenerCost))
	}
	if fields.Has(ListenerSslProfile) && e.SslProfile != other.SslProfile {
		result = result.Union(mgmt.Fields(ListenerSslProfile))
	}
	if fields.Has(ListenerSaslMechanisms) && e.SaslMechanisms != other.SaslMechanisms {
		result = result.Union(mgmt.Fields(ListenerSaslMechanisms))
	}
	if fields.Has(ListenerAuthenticatePeer) && e.AuthenticatePeer != other.AuthenticatePeer {
		result = result.Union(mgmt.Fields(ListenerAuthenticatePeer))
	}
	if fields.Has(ListenerRequireEncryption) && e.RequireEncryption != other.RequireEncryption {
		result = result.Union(mgmt.Fields(ListenerRequireEncryption))
	}
	if fields.Has(ListenerRequireSsl) && e.RequireSsl != other.RequireSsl {
		result = result.Union(mgmt.Fields(ListenerRequireSsl))
	}
	if fields.Has(ListenerMaxFrameSize) && e.MaxFrameSize != other.MaxFrameSize {
		result = result.Union(mgmt.Fields(ListenerMaxFrameSize))
	}
	if fields.Has(ListenerMaxSessions) && e.MaxSessions != other.MaxSessions {
		result = result.Union(mgmt.Fields(ListenerMaxSessions))
	}
	if fields.Has(ListenerMaxSessionFrames) && e.MaxSessionFrames != other.MaxSessionFrames {
		result = result.Union(mgmt.Fields(ListenerMaxSessionFrames))
	}
	if fields.Has(ListenerIdleTimeoutSeconds) && e.IdleTimeoutSeconds != other.IdleTimeoutSeconds {
		result = result.Union(mgmt.Fields(ListenerIdleTimeoutSeconds))
	}
	if fields.Has(ListenerInitialHandshakeTimeoutSeconds) && e.InitialHandshakeTimeoutSeconds != other.InitialHandshakeTimeoutSeconds {
		result = result.Union(mgmt.Fields(ListenerInitialHandshakeTimeoutSeconds))
	}
	if fields.Has(ListenerStripAnnotations) && e.StripAnnotations != other.StripAnnotations {
		result = result.Union(mgmt.Fields(ListenerStripAnnotations))
	}
	if fields.Has(ListenerLinkCapacity) && e.LinkCapacity != other.LinkCapacity {
		result = result.Union(mgmt.Fields(ListenerLinkCapacity))
	}
	if fields.Has(ListenerFailoverUrls) && e.FailoverUrls != other.FailoverUrls {
		result = result.Union(mgmt.Fields(ListenerFailoverUrls))
	}
	if fields.Has(ListenerHealthz) && e.Healthz != other.Healthz {
		result = result.Union(mgmt.Fields(ListenerHealthz))
	}
	if fields.Has(ListenerMetrics) && e.Metrics != other.Metrics {
		result = result.Union(mgmt.Fields(ListenerMetrics))
	}
	if fields.Has(ListenerWebsockets) && e.Websockets != other.Websockets {
		result = result.Union(mgmt.Fields(ListenerWebsockets))
	}
	if fields.Has(ListenerHttp) && e.Http != other.Http {
		result = result.Union(mgmt.Fields(ListenerHttp))
	}
	if fields.Has(ListenerHttpRootDir) && e.HttpRootDir != other.HttpRootDir {
		result = result.Union(mgmt.Fields(ListenerHttpRootDir))
	}
	if fields.Has(ListenerMessageLoggingComponents) && e.MessageLoggingComponents != other.MessageLoggingComponents {
		result = result.Union(mgmt.Fields(ListenerMessageLoggingComponents))
	}
	if fields.Has(ListenerPolicyVhost) && e.PolicyVhost != other.PolicyVhost {
		result = result.Union(mgmt.Fields(ListenerPolicyVhost))
	}
	if fields.Has(ListenerOpenProperties) && !mgmt.EqualValues(e.OpenProperties, other.OpenProperties) {
		result = result.Union(mgmt.Fields(ListenerOpenProperties))
	}
	return result
}

func (e *Listener) ApplyDefaults(present mgmt.FieldSet[Listener]) {
	if !present.Has(ListenerTypeField) {
		e.Type = "io.skupper.router.listener"
	}
	if !present.Has(ListenerHost) {
		e.Host = ""
	}
	if !present.Has(ListenerPort) {
		e.Port = "amqp"
	}
	if !present.Has(ListenerRole) {
		e.Role = Role("normal")
	}
	if !present.Has(ListenerCost) {
		e.Cost = int64(1)
	}
	if !present.Has(ListenerAuthenticatePeer) {
		e.AuthenticatePeer = false
	}
	if !present.Has(ListenerRequireEncryption) {
		e.RequireEncryption = false
	}
	if !present.Has(ListenerRequireSsl) {
		e.RequireSsl = false
	}
	if !present.Has(ListenerMaxFrameSize) {
		e.MaxFrameSize = int64(16384)
	}
	if !present.Has(ListenerMaxSessions) {
		e.MaxSessions = int64(32768)
	}
	if !present.Has(ListenerIdleTimeoutSeconds) {
		e.IdleTimeoutSeconds = int64(16)
	}
	if !present.Has(ListenerInitialHandshakeTimeoutSeconds) {
		e.InitialHandshakeTimeoutSeconds = int64(0)
	}
	if !present.Has(ListenerStripAnnotations) {
		e.StripAnnotations = StripAnnotations("both")
	}
	if !present.Has(ListenerHealthz) {
		e.Healthz = true
	}
	if !present.Has(ListenerMetrics) {
		e.Metrics = true
	}
	if !present.Has(ListenerWebsockets) {
		e.Websockets = true
	}
	if !present.Has(ListenerHttp) {
		e.Http = false
	}
	if !present.Has(ListenerMessageLoggingComponents) {
		e.MessageLoggingComponents = "none"
	}
}

func (e *Listener) NonZeroFields() mgmt.FieldSet[Listener] {
	var result mgmt.FieldSet[Listener]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(ListenerName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(ListenerIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(ListenerTypeField))
	}
	if e.Host != "" {
		result = result.Union(mgmt.Fields(ListenerHost))
	}
	if e.Port != "" {
		result = result.Union(mgmt.Fields(ListenerPort))
	}
	if e.SocketAddressFamily != "" {
		result = result.Union(mgmt.Fields(ListenerSocketAddressFamily))
	}
	if e.Role != "" {
		result = result.Union(mgmt.Fields(ListenerRole))
	}
	if e.Cost != 0 {
		result = result.Union(mgmt.Fields(ListenerCost))
	}
	if e.SslProfile != "" {
		result = result.Union(mgmt.Fields(ListenerSslProfile))
	}
	if e.SaslMechanisms != "" {
		result = result.Union(mgmt.Fields(ListenerSaslMechanisms))
	}
	if e.AuthenticatePeer {
		result = result.Union(mgmt.Fields(ListenerAuthenticatePeer))
	}
	if e.RequireEncryption {
		result = result.Union(mgmt.Fields(ListenerRequireEncryption))
	}
	if e.RequireSsl {
		result = result.Union(mgmt.Fields(ListenerRequireSsl))
	}
	if e.MaxFrameSize != 0 {
		result = result.Union(mgmt.Fields(ListenerMaxFrameSize))
	}
	if e.MaxSessions != 0 {
		result = result.Union(mgmt.Fields(ListenerMaxSessions))
	}
	if e.MaxSessionFrames != 0 {
		result = result.Union(mgmt.Fields(ListenerMaxSessionFrames))
	}
	if e.IdleTimeoutSeconds != 0 {
		result = result.Union(mgmt.Fields(ListenerIdleTimeoutSeconds))
	}
	if e.InitialHandshakeTimeoutSeconds != 0 {
		result = result.Union(mgmt.Fields(ListenerInitialHandshakeTimeoutSeconds))
	}
	if e.StripAnnotations != "" {
		result = result.Union(mgmt.Fields(ListenerStripAnnotations))
	}
	if e.LinkCapacity != 0 {
		result = result.Union(mgmt.Fields(ListenerLinkCapacity))
	}
	if e.FailoverUrls != "" {
		result = result.Union(mgmt.Fields(ListenerFailoverUrls))
	}
	if e.Healthz {
		result = result.Union(mgmt.Fields(ListenerHealthz))
	}
	if e.Metrics {
		result = result.Union(mgmt.Fields(ListenerMetrics))
	}
	if e.Websockets {
		result = result.Union(mgmt.Fields(ListenerWebsockets))
	}
	if e.Http {
		result = result.Union(mgmt.Fields(ListenerHttp))
	}
	if e.HttpRootDir != "" {
		result = result.Union(mgmt.Fields(ListenerHttpRootDir))
	}
	if e.MessageLoggingComponents != "" {
		result = result.Union(mgmt.Fields(ListenerMessageLoggingComponents))
	}
	if e.PolicyVhost != "" {
		result = result.Union(mgmt.Fields(ListenerPolicyVhost))
	}
	if len(e.OpenProperties) != 0 {
		result = result.Union(mgmt.Fields(ListenerOpenProperties))
	}
	return result
}
