// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

type RouterMode string

const (
	RouterModeStandalone RouterMode = "standalone"
	RouterModeInterior   RouterMode = "interior"
	RouterModeEdge       RouterMode = "edge"
)

var routerModeValues = []string{"standalone", "interior", "edge"}

type Distribution string

const (
	DistributionMulticast   Distribution = "multicast"
	DistributionClosest     Distribution = "closest"
	DistributionBalanced    Distribution = "balanced"
	DistributionUnavailable Distribution = "unavailable"
)

var distributionValues = []string{"multicast", "closest", "balanced", "unavailable"}

type SocketAddressFamily string

const (
	SocketAddressFamilyIPv4 SocketAddressFamily = "IPv4"
	SocketAddressFamilyIPv6 SocketAddressFamily = "IPv6"
)

var socketAddressFamilyValues = []string{"IPv4", "IPv6"}

type Role string

const (
	RoleNormal         Role = "normal"
	RoleInterRouter    Role = "inter-router"
	RoleRouteContainer Role = "route-container"
	RoleEdge           Role = "edge"
	RoleInterEdge      Role = "inter-edge"
	RoleInterNetwork   Role = "inter-network"
)

var roleValues = []string{"normal", "inter-router", "route-container", "edge", "inter-edge", "inter-network"}

type StripAnnotations string

const (
	StripAnnotationsIn   StripAnnotations = "in"
	StripAnnotationsOut  StripAnnotations = "out"
	StripAnnotationsBoth StripAnnotations = "both"
	StripAnnotationsNo   StripAnnotations = "no"
)

var stripAnnotationsValues = []string{"in", "out", "both", "no"}

type MultiAddressStrategy string

const (
	MultiAddressStrategyNone     MultiAddressStrategy = "none"
	MultiAddressStrategyPriority MultiAddressStrategy = "priority"
	MultiAddressStrategyWeighted MultiAddressStrategy = "weighted"
)

var multiAddressStrategyValues = []string{"none", "priority", "weighted"}

type TcpOperStatus string

const (
	TcpOperStatusUp   TcpOperStatus = "up"
	TcpOperStatusDown TcpOperStatus = "down"
)

var tcpOperStatusValues = []string{"up", "down"}

type Observer string

const (
	ObserverNone  Observer = "none"
	ObserverAuto  Observer = "auto"
	ObserverHttp1 Observer = "http1"
	ObserverHttp2 Observer = "http2"
)

var observerValues = []string{"none", "auto", "http1", "http2"}

type LogModule string

const (
	LogModuleRouter        LogModule = "ROUTER"
	LogModuleRouterCore    LogModule = "ROUTER_CORE"
	LogModuleRouterHello   LogModule = "ROUTER_HELLO"
	LogModuleRouterLs      LogModule = "ROUTER_LS"
	LogModuleRouterMa      LogModule = "ROUTER_MA"
	LogModuleMessage       LogModule = "MESSAGE"
	LogModuleServer        LogModule = "SERVER"
	LogModuleAgent         LogModule = "AGENT"
	LogModuleContainer     LogModule = "CONTAINER"
	LogModuleError         LogModule = "ERROR"
	LogModulePolicy        LogModule = "POLICY"
	LogModuleHttp          LogModule = "HTTP"
	LogModuleConnMgr       LogModule = "CONN_MGR"
	LogModulePython        LogModule = "PYTHON"
	LogModuleProtocol      LogModule = "PROTOCOL"
	LogModuleTcpAdaptor    LogModule = "TCP_ADAPTOR"
	LogModuleHttpAdaptor   LogModule = "HTTP_ADAPTOR"
	LogModuleFlowLog       LogModule = "FLOW_LOG"
	LogModuleAddressWatch  LogModule = "ADDRESS_WATCH"
	LogModuleHttp1Observer LogModule = "HTTP1_OBSERVER"
	LogModuleHttp2Observer LogModule = "HTTP2_OBSERVER"
	LogModuleHttp2Decoder  LogModule = "HTTP2_DECODER"
	LogModuleDefault       LogModule = "DEFAULT"
)

var logModuleValues = []string{"ROUTER", "ROUTER_CORE", "ROUTER_HELLO", "ROUTER_LS", "ROUTER_MA", "MESSAGE", "SERVER", "AGENT", "CONTAINER", "ERROR", "POLICY", "HTTP", "CONN_MGR", "PYTHON", "PROTOCOL", "TCP_ADAPTOR", "HTTP_ADAPTOR", "FLOW_LOG", "ADDRESS_WATCH", "HTTP1_OBSERVER", "HTTP2_OBSERVER", "HTTP2_DECODER", "DEFAULT"}

type Direction string

const (
	DirectionIn  Direction = "in"
	DirectionOut Direction = "out"
)

var directionValues = []string{"in", "out"}

type AutoLinkOperStatus string

const (
	AutoLinkOperStatusInactive  AutoLinkOperStatus = "inactive"
	AutoLinkOperStatusAttaching AutoLinkOperStatus = "attaching"
	AutoLinkOperStatusFailed    AutoLinkOperStatus = "failed"
	AutoLinkOperStatusActive    AutoLinkOperStatus = "active"
	AutoLinkOperStatusQuiescing AutoLinkOperStatus = "quiescing"
	AutoLinkOperStatusIdle      AutoLinkOperStatus = "idle"
)

var autoLinkOperStatusValues = []string{"inactive", "attaching", "failed", "active", "quiescing", "idle"}

type LinkOperStatus string

const (
	LinkOperStatusUp        LinkOperStatus = "up"
	LinkOperStatusDown      LinkOperStatus = "down"
	LinkOperStatusQuiescing LinkOperStatus = "quiescing"
	LinkOperStatusIdle      LinkOperStatus = "idle"
)

var linkOperStatusValues = []string{"up", "down", "quiescing", "idle"}

type LinkType string

const (
	LinkTypeEndpoint      LinkType = "endpoint"
	LinkTypeRouterControl LinkType = "router-control"
	LinkTypeInterRouter   LinkType = "inter-router"
	LinkTypeInterEdge     LinkType = "inter-edge"
)

var linkTypeValues = []string{"endpoint", "router-control", "inter-router", "inter-edge"}

type RouterDistribution string

const (
	RouterDistributionFlood        RouterDistribution = "flood"
	RouterDistributionMulticast    RouterDistribution = "multicast"
	RouterDistributionClosest      RouterDistribution = "closest"
	RouterDistributionBalanced     RouterDistribution = "balanced"
	RouterDistributionLinkBalanced RouterDistribution = "linkBalanced"
	RouterDistributionUnavailable  RouterDistribution = "unavailable"
)

var routerDistributionValues = []string{"flood", "multicast", "closest", "balanced", "linkBalanced", "unavailable"}

type AdminStatus string

const (
	AdminStatusEnabled AdminStatus = "enabled"
	AdminStatusDeleted AdminStatus = "deleted"
)

var adminStatusValues = []string{"enabled", "deleted"}

type ConnectionOperStatus string

const (
	ConnectionOperStatusUp      ConnectionOperStatus = "up"
	ConnectionOperStatusClosing ConnectionOperStatus = "closing"
)

var connectionOperStatusValues = []string{"up", "closing"}
