// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type Network struct {
	Name      string
	Identity  string
	Type      string
	NetworkId string
	TenantId  string
}

const (
	NetworkName mgmt.Field[Network] = iota
	NetworkIdentity
	NetworkTypeField
	NetworkNetworkId
	NetworkTenantId
)

var NetworkType = mgmt.NewType("io.skupper.router.network", "network", false, []string{"QUERY", "READ", "UPDATE"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: false, Update: false, Default: "io.skupper.router.network", HasDefault: true},
	{Name: "networkId", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: true},
	{Name: "tenantId", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
})

var NetworkAllFields = mgmt.Fields(NetworkName, NetworkIdentity, NetworkTypeField, NetworkNetworkId, NetworkTenantId)

var NetworkCreateFields mgmt.FieldSet[Network]

var NetworkUpdateFields = mgmt.Fields(NetworkNetworkId)

func (*Network) ManagementType() *mgmt.Type { return NetworkType }

func (e *Network) SetManagementField(field mgmt.Field[Network], value any) error {
	switch field {
	case NetworkName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(NetworkType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case NetworkIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(NetworkType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case NetworkTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(NetworkType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case NetworkNetworkId:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(NetworkType.Name, "networkId", value)
		}
		e.NetworkId = decoded
		return nil
	case NetworkTenantId:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(NetworkType.Name, "tenantId", value)
		}
		e.TenantId = decoded
		return nil
	}
	return mgmt.DecodeError(NetworkType.Name, "<unknown>", value)
}

func (e *Network) ManagementValue(field mgmt.Field[Network]) any {
	switch field {
	case NetworkName:
		return e.Name
	case NetworkIdentity:
		return e.Identity
	case NetworkTypeField:
		return e.Type
	case NetworkNetworkId:
		return e.NetworkId
	case NetworkTenantId:
		return e.TenantId
	}
	return nil
}

func (e *Network) Equal(other *Network, fields mgmt.FieldSet[Network]) bool {
	if fields.Has(NetworkName) && e.Name != other.Name {
		return false
	}
	if fields.Has(NetworkIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(NetworkTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(NetworkNetworkId) && e.NetworkId != other.NetworkId {
		return false
	}
	if fields.Has(NetworkTenantId) && e.TenantId != other.TenantId {
		return false
	}
	return true
}

func (e *Network) Diff(other *Network, fields mgmt.FieldSet[Network]) mgmt.FieldSet[Network] {
	var result mgmt.FieldSet[Network]
	if fields.Has(NetworkName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(NetworkName))
	}
	if fields.Has(NetworkIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(NetworkIdentity))
	}
	if fields.Has(NetworkTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(NetworkTypeField))
	}
	if fields.Has(NetworkNetworkId) && e.NetworkId != other.NetworkId {
		result = result.Union(mgmt.Fields(NetworkNetworkId))
	}
	if fields.Has(NetworkTenantId) && e.TenantId != other.TenantId {
		result = result.Union(mgmt.Fields(NetworkTenantId))
	}
	return result
}

func (e *Network) ApplyDefaults(present mgmt.FieldSet[Network]) {
	if !present.Has(NetworkTypeField) {
		e.Type = "io.skupper.router.network"
	}
}

func (e *Network) NonZeroFields() mgmt.FieldSet[Network] {
	var result mgmt.FieldSet[Network]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(NetworkName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(NetworkIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(NetworkTypeField))
	}
	if e.NetworkId != "" {
		result = result.Union(mgmt.Fields(NetworkNetworkId))
	}
	if e.TenantId != "" {
		result = result.Union(mgmt.Fields(NetworkTenantId))
	}
	return result
}
