// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type Allocator struct {
	Name                       string
	Identity                   string
	Type                       string
	TypeName                   string
	TypeSize                   int64
	TransferBatchSize          int64
	LocalFreeListMax           int64
	GlobalFreeListMax          int64
	TotalAllocFromHeap         int64
	TotalFreeToHeap            int64
	HeldByThreads              int64
	BatchesRebalancedToThreads int64
	BatchesRebalancedToGlobal  int64
}

const (
	AllocatorName mgmt.Field[Allocator] = iota
	AllocatorIdentity
	AllocatorTypeField
	AllocatorTypeName
	AllocatorTypeSize
	AllocatorTransferBatchSize
	AllocatorLocalFreeListMax
	AllocatorGlobalFreeListMax
	AllocatorTotalAllocFromHeap
	AllocatorTotalFreeToHeap
	AllocatorHeldByThreads
	AllocatorBatchesRebalancedToThreads
	AllocatorBatchesRebalancedToGlobal
)

var AllocatorType = mgmt.NewType("io.skupper.router.allocator", "allocator", false, []string{"QUERY", "READ"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: false, Update: false, Default: "io.skupper.router.allocator", HasDefault: true},
	{Name: "typeName", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "typeSize", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "transferBatchSize", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "localFreeListMax", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "globalFreeListMax", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "totalAllocFromHeap", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "totalFreeToHeap", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "heldByThreads", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "batchesRebalancedToThreads", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "batchesRebalancedToGlobal", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
})

var AllocatorAllFields = mgmt.Fields(AllocatorName, AllocatorIdentity, AllocatorTypeField, AllocatorTypeName, AllocatorTypeSize, AllocatorTransferBatchSize, AllocatorLocalFreeListMax, AllocatorGlobalFreeListMax, AllocatorTotalAllocFromHeap, AllocatorTotalFreeToHeap, AllocatorHeldByThreads, AllocatorBatchesRebalancedToThreads, AllocatorBatchesRebalancedToGlobal)

var AllocatorCreateFields mgmt.FieldSet[Allocator]

var AllocatorUpdateFields mgmt.FieldSet[Allocator]

func (*Allocator) ManagementType() *mgmt.Type { return AllocatorType }

func (e *Allocator) SetManagementField(field mgmt.Field[Allocator], value any) error {
	switch field {
	case AllocatorName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(AllocatorType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case AllocatorIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(AllocatorType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case AllocatorTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(AllocatorType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case AllocatorTypeName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(AllocatorType.Name, "typeName", value)
		}
		e.TypeName = decoded
		return nil
	case AllocatorTypeSize:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(AllocatorType.Name, "typeSize", value)
		}
		e.TypeSize = decoded
		return nil
	case AllocatorTransferBatchSize:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(AllocatorType.Name, "transferBatchSize", value)
		}
		e.TransferBatchSize = decoded
		return nil
	case AllocatorLocalFreeListMax:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(AllocatorType.Name, "localFreeListMax", value)
		}
		e.LocalFreeListMax = decoded
		return nil
	case AllocatorGlobalFreeListMax:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(AllocatorType.Name, "globalFreeListMax", value)
		}
		e.GlobalFreeListMax = decoded
		return nil
	case AllocatorTotalAllocFromHeap:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(AllocatorType.Name, "totalAllocFromHeap", value)
		}
		e.TotalAllocFromHeap = decoded
		return nil
	case AllocatorTotalFreeToHeap:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(AllocatorType.Name, "totalFreeToHeap", value)
		}
		e.TotalFreeToHeap = decoded
		return nil
	case AllocatorHeldByThreads:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(AllocatorType.Name, "heldByThreads", value)
		}
		e.HeldByThreads = decoded
		return nil
	case AllocatorBatchesRebalancedToThreads:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(AllocatorType.Name, "batchesRebalancedToThreads", value)
		}
		e.BatchesRebalancedToThreads = decoded
		return nil
	case AllocatorBatchesRebalancedToGlobal:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(AllocatorType.Name, "batchesRebalancedToGlobal", value)
		}
		e.BatchesRebalancedToGlobal = decoded
		return nil
	}
	return mgmt.DecodeError(AllocatorType.Name, "<unknown>", value)
}

func (e *Allocator) ManagementValue(field mgmt.Field[Allocator]) any {
	switch field {
	case AllocatorName:
		return e.Name
	case AllocatorIdentity:
		return e.Identity
	case AllocatorTypeField:
		return e.Type
	case AllocatorTypeName:
		return e.TypeName
	case AllocatorTypeSize:
		return e.TypeSize
	case AllocatorTransferBatchSize:
		return e.TransferBatchSize
	case AllocatorLocalFreeListMax:
		return e.LocalFreeListMax
	case AllocatorGlobalFreeListMax:
		return e.GlobalFreeListMax
	case AllocatorTotalAllocFromHeap:
		return e.TotalAllocFromHeap
	case AllocatorTotalFreeToHeap:
		return e.TotalFreeToHeap
	case AllocatorHeldByThreads:
		return e.HeldByThreads
	case AllocatorBatchesRebalancedToThreads:
		return e.BatchesRebalancedToThreads
	case AllocatorBatchesRebalancedToGlobal:
		return e.BatchesRebalancedToGlobal
	}
	return nil
}

func (e *Allocator) Equal(other *Allocator, fields mgmt.FieldSet[Allocator]) bool {
	if fields.Has(AllocatorName) && e.Name != other.Name {
		return false
	}
	if fields.Has(AllocatorIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(AllocatorTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(AllocatorTypeName) && e.TypeName != other.TypeName {
		return false
	}
	if fields.Has(AllocatorTypeSize) && e.TypeSize != other.TypeSize {
		return false
	}
	if fields.Has(AllocatorTransferBatchSize) && e.TransferBatchSize != other.TransferBatchSize {
		return false
	}
	if fields.Has(AllocatorLocalFreeListMax) && e.LocalFreeListMax != other.LocalFreeListMax {
		return false
	}
	if fields.Has(AllocatorGlobalFreeListMax) && e.GlobalFreeListMax != other.GlobalFreeListMax {
		return false
	}
	if fields.Has(AllocatorTotalAllocFromHeap) && e.TotalAllocFromHeap != other.TotalAllocFromHeap {
		return false
	}
	if fields.Has(AllocatorTotalFreeToHeap) && e.TotalFreeToHeap != other.TotalFreeToHeap {
		return false
	}
	if fields.Has(AllocatorHeldByThreads) && e.HeldByThreads != other.HeldByThreads {
		return false
	}
	if fields.Has(AllocatorBatchesRebalancedToThreads) && e.BatchesRebalancedToThreads != other.BatchesRebalancedToThreads {
		return false
	}
	if fields.Has(AllocatorBatchesRebalancedToGlobal) && e.BatchesRebalancedToGlobal != other.BatchesRebalancedToGlobal {
		return false
	}
	return true
}

func (e *Allocator) Diff(other *Allocator, fields mgmt.FieldSet[Allocator]) mgmt.FieldSet[Allocator] {
	var result mgmt.FieldSet[Allocator]
	if fields.Has(AllocatorName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(AllocatorName))
	}
	if fields.Has(AllocatorIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(AllocatorIdentity))
	}
	if fields.Has(AllocatorTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(AllocatorTypeField))
	}
	if fields.Has(AllocatorTypeName) && e.TypeName != other.TypeName {
		result = result.Union(mgmt.Fields(AllocatorTypeName))
	}
	if fields.Has(AllocatorTypeSize) && e.TypeSize != other.TypeSize {
		result = result.Union(mgmt.Fields(AllocatorTypeSize))
	}
	if fields.Has(AllocatorTransferBatchSize) && e.TransferBatchSize != other.TransferBatchSize {
		result = result.Union(mgmt.Fields(AllocatorTransferBatchSize))
	}
	if fields.Has(AllocatorLocalFreeListMax) && e.LocalFreeListMax != other.LocalFreeListMax {
		result = result.Union(mgmt.Fields(AllocatorLocalFreeListMax))
	}
	if fields.Has(AllocatorGlobalFreeListMax) && e.GlobalFreeListMax != other.GlobalFreeListMax {
		result = result.Union(mgmt.Fields(AllocatorGlobalFreeListMax))
	}
	if fields.Has(AllocatorTotalAllocFromHeap) && e.TotalAllocFromHeap != other.TotalAllocFromHeap {
		result = result.Union(mgmt.Fields(AllocatorTotalAllocFromHeap))
	}
	if fields.Has(AllocatorTotalFreeToHeap) && e.TotalFreeToHeap != other.TotalFreeToHeap {
		result = result.Union(mgmt.Fields(AllocatorTotalFreeToHeap))
	}
	if fields.Has(AllocatorHeldByThreads) && e.HeldByThreads != other.HeldByThreads {
		result = result.Union(mgmt.Fields(AllocatorHeldByThreads))
	}
	if fields.Has(AllocatorBatchesRebalancedToThreads) && e.BatchesRebalancedToThreads != other.BatchesRebalancedToThreads {
		result = result.Union(mgmt.Fields(AllocatorBatchesRebalancedToThreads))
	}
	if fields.Has(AllocatorBatchesRebalancedToGlobal) && e.BatchesRebalancedToGlobal != other.BatchesRebalancedToGlobal {
		result = result.Union(mgmt.Fields(AllocatorBatchesRebalancedToGlobal))
	}
	return result
}

func (e *Allocator) ApplyDefaults(present mgmt.FieldSet[Allocator]) {
	if !present.Has(AllocatorTypeField) {
		e.Type = "io.skupper.router.allocator"
	}
}

func (e *Allocator) NonZeroFields() mgmt.FieldSet[Allocator] {
	var result mgmt.FieldSet[Allocator]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(AllocatorName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(AllocatorIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(AllocatorTypeField))
	}
	if e.TypeName != "" {
		result = result.Union(mgmt.Fields(AllocatorTypeName))
	}
	if e.TypeSize != 0 {
		result = result.Union(mgmt.Fields(AllocatorTypeSize))
	}
	if e.TransferBatchSize != 0 {
		result = result.Union(mgmt.Fields(AllocatorTransferBatchSize))
	}
	if e.LocalFreeListMax != 0 {
		result = result.Union(mgmt.Fields(AllocatorLocalFreeListMax))
	}
	if e.GlobalFreeListMax != 0 {
		result = result.Union(mgmt.Fields(AllocatorGlobalFreeListMax))
	}
	if e.TotalAllocFromHeap != 0 {
		result = result.Union(mgmt.Fields(AllocatorTotalAllocFromHeap))
	}
	if e.TotalFreeToHeap != 0 {
		result = result.Union(mgmt.Fields(AllocatorTotalFreeToHeap))
	}
	if e.HeldByThreads != 0 {
		result = result.Union(mgmt.Fields(AllocatorHeldByThreads))
	}
	if e.BatchesRebalancedToThreads != 0 {
		result = result.Union(mgmt.Fields(AllocatorBatchesRebalancedToThreads))
	}
	if e.BatchesRebalancedToGlobal != 0 {
		result = result.Union(mgmt.Fields(AllocatorBatchesRebalancedToGlobal))
	}
	return result
}
