// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type RouterNode struct {
	Name            string
	Identity        string
	Type            string
	Id              string
	ProtocolVersion int64
	Instance        int64
	LinkState       []int64
	NextHop         string
	ValidOrigins    []string
	Address         string
	RouterLink      string
	Cost            int64
	LastTopoChange  int64
	Index           int64
}

const (
	RouterNodeName mgmt.Field[RouterNode] = iota
	RouterNodeIdentity
	RouterNodeTypeField
	RouterNodeId
	RouterNodeProtocolVersion
	RouterNodeInstance
	RouterNodeLinkState
	RouterNodeNextHop
	RouterNodeValidOrigins
	RouterNodeAddress
	RouterNodeRouterLink
	RouterNodeCost
	RouterNodeLastTopoChange
	RouterNodeIndex
)

var RouterNodeType = mgmt.NewType("io.skupper.router.router.node", "router.node", false, []string{"QUERY", "READ"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: false, Update: false, Default: "io.skupper.router.router.node", HasDefault: true},
	{Name: "id", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "protocolVersion", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "instance", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "linkState", Kind: mgmt.ListAttribute, Required: false, Create: false, Update: false},
	{Name: "nextHop", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "validOrigins", Kind: mgmt.ListAttribute, Required: false, Create: false, Update: false},
	{Name: "address", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "routerLink", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "cost", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "lastTopoChange", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "index", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
})

var RouterNodeAllFields = mgmt.Fields(RouterNodeName, RouterNodeIdentity, RouterNodeTypeField, RouterNodeId, RouterNodeProtocolVersion, RouterNodeInstance, RouterNodeLinkState, RouterNodeNextHop, RouterNodeValidOrigins, RouterNodeAddress, RouterNodeRouterLink, RouterNodeCost, RouterNodeLastTopoChange, RouterNodeIndex)

var RouterNodeCreateFields mgmt.FieldSet[RouterNode]

var RouterNodeUpdateFields mgmt.FieldSet[RouterNode]

func (*RouterNode) ManagementType() *mgmt.Type { return RouterNodeType }

func (e *RouterNode) SetManagementField(field mgmt.Field[RouterNode], value any) error {
	switch field {
	case RouterNodeName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case RouterNodeIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case RouterNodeTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case RouterNodeId:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "id", value)
		}
		e.Id = decoded
		return nil
	case RouterNodeProtocolVersion:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "protocolVersion", value)
		}
		e.ProtocolVersion = decoded
		return nil
	case RouterNodeInstance:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "instance", value)
		}
		e.Instance = decoded
		return nil
	case RouterNodeLinkState:
		decoded, ok := mgmt.AsInt64List(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "linkState", value)
		}
		e.LinkState = decoded
		return nil
	case RouterNodeNextHop:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "nextHop", value)
		}
		e.NextHop = decoded
		return nil
	case RouterNodeValidOrigins:
		decoded, ok := mgmt.AsStringList(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "validOrigins", value)
		}
		e.ValidOrigins = decoded
		return nil
	case RouterNodeAddress:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "address", value)
		}
		e.Address = decoded
		return nil
	case RouterNodeRouterLink:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "routerLink", value)
		}
		e.RouterLink = decoded
		return nil
	case RouterNodeCost:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "cost", value)
		}
		e.Cost = decoded
		return nil
	case RouterNodeLastTopoChange:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "lastTopoChange", value)
		}
		e.LastTopoChange = decoded
		return nil
	case RouterNodeIndex:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterNodeType.Name, "index", value)
		}
		e.Index = decoded
		return nil
	}
	return mgmt.DecodeError(RouterNodeType.Name, "<unknown>", value)
}

func (e *RouterNode) ManagementValue(field mgmt.Field[RouterNode]) any {
	switch field {
	case RouterNodeName:
		return e.Name
	case RouterNodeIdentity:
		return e.Identity
	case RouterNodeTypeField:
		return e.Type
	case RouterNodeId:
		return e.Id
	case RouterNodeProtocolVersion:
		return e.ProtocolVersion
	case RouterNodeInstance:
		return e.Instance
	case RouterNodeLinkState:
		return e.LinkState
	case RouterNodeNextHop:
		return e.NextHop
	case RouterNodeValidOrigins:
		return e.ValidOrigins
	case RouterNodeAddress:
		return e.Address
	case RouterNodeRouterLink:
		return e.RouterLink
	case RouterNodeCost:
		return e.Cost
	case RouterNodeLastTopoChange:
		return e.LastTopoChange
	case RouterNodeIndex:
		return e.Index
	}
	return nil
}

func (e *RouterNode) Equal(other *RouterNode, fields mgmt.FieldSet[RouterNode]) bool {
	if fields.Has(RouterNodeName) && e.Name != other.Name {
		return false
	}
	if fields.Has(RouterNodeIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(RouterNodeTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(RouterNodeId) && e.Id != other.Id {
		return false
	}
	if fields.Has(RouterNodeProtocolVersion) && e.ProtocolVersion != other.ProtocolVersion {
		return false
	}
	if fields.Has(RouterNodeInstance) && e.Instance != other.Instance {
		return false
	}
	if fields.Has(RouterNodeLinkState) && !mgmt.EqualValues(e.LinkState, other.LinkState) {
		return false
	}
	if fields.Has(RouterNodeNextHop) && e.NextHop != other.NextHop {
		return false
	}
	if fields.Has(RouterNodeValidOrigins) && !mgmt.EqualValues(e.ValidOrigins, other.ValidOrigins) {
		return false
	}
	if fields.Has(RouterNodeAddress) && e.Address != other.Address {
		return false
	}
	if fields.Has(RouterNodeRouterLink) && e.RouterLink != other.RouterLink {
		return false
	}
	if fields.Has(RouterNodeCost) && e.Cost != other.Cost {
		return false
	}
	if fields.Has(RouterNodeLastTopoChange) && e.LastTopoChange != other.LastTopoChange {
		return false
	}
	if fields.Has(RouterNodeIndex) && e.Index != other.Index {
		return false
	}
	return true
}

func (e *RouterNode) Diff(other *RouterNode, fields mgmt.FieldSet[RouterNode]) mgmt.FieldSet[RouterNode] {
	var result mgmt.FieldSet[RouterNode]
	if fields.Has(RouterNodeName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(RouterNodeName))
	}
	if fields.Has(RouterNodeIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(RouterNodeIdentity))
	}
	if fields.Has(RouterNodeTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(RouterNodeTypeField))
	}
	if fields.Has(RouterNodeId) && e.Id != other.Id {
		result = result.Union(mgmt.Fields(RouterNodeId))
	}
	if fields.Has(RouterNodeProtocolVersion) && e.ProtocolVersion != other.ProtocolVersion {
		result = result.Union(mgmt.Fields(RouterNodeProtocolVersion))
	}
	if fields.Has(RouterNodeInstance) && e.Instance != other.Instance {
		result = result.Union(mgmt.Fields(RouterNodeInstance))
	}
	if fields.Has(RouterNodeLinkState) && !mgmt.EqualValues(e.LinkState, other.LinkState) {
		result = result.Union(mgmt.Fields(RouterNodeLinkState))
	}
	if fields.Has(RouterNodeNextHop) && e.NextHop != other.NextHop {
		result = result.Union(mgmt.Fields(RouterNodeNextHop))
	}
	if fields.Has(RouterNodeValidOrigins) && !mgmt.EqualValues(e.ValidOrigins, other.ValidOrigins) {
		result = result.Union(mgmt.Fields(RouterNodeValidOrigins))
	}
	if fields.Has(RouterNodeAddress) && e.Address != other.Address {
		result = result.Union(mgmt.Fields(RouterNodeAddress))
	}
	if fields.Has(RouterNodeRouterLink) && e.RouterLink != other.RouterLink {
		result = result.Union(mgmt.Fields(RouterNodeRouterLink))
	}
	if fields.Has(RouterNodeCost) && e.Cost != other.Cost {
		result = result.Union(mgmt.Fields(RouterNodeCost))
	}
	if fields.Has(RouterNodeLastTopoChange) && e.LastTopoChange != other.LastTopoChange {
		result = result.Union(mgmt.Fields(RouterNodeLastTopoChange))
	}
	if fields.Has(RouterNodeIndex) && e.Index != other.Index {
		result = result.Union(mgmt.Fields(RouterNodeIndex))
	}
	return result
}

func (e *RouterNode) ApplyDefaults(present mgmt.FieldSet[RouterNode]) {
	if !present.Has(RouterNodeTypeField) {
		e.Type = "io.skupper.router.router.node"
	}
}

func (e *RouterNode) NonZeroFields() mgmt.FieldSet[RouterNode] {
	var result mgmt.FieldSet[RouterNode]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(RouterNodeName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(RouterNodeIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(RouterNodeTypeField))
	}
	if e.Id != "" {
		result = result.Union(mgmt.Fields(RouterNodeId))
	}
	if e.ProtocolVersion != 0 {
		result = result.Union(mgmt.Fields(RouterNodeProtocolVersion))
	}
	if e.Instance != 0 {
		result = result.Union(mgmt.Fields(RouterNodeInstance))
	}
	if len(e.LinkState) != 0 {
		result = result.Union(mgmt.Fields(RouterNodeLinkState))
	}
	if e.NextHop != "" {
		result = result.Union(mgmt.Fields(RouterNodeNextHop))
	}
	if len(e.ValidOrigins) != 0 {
		result = result.Union(mgmt.Fields(RouterNodeValidOrigins))
	}
	if e.Address != "" {
		result = result.Union(mgmt.Fields(RouterNodeAddress))
	}
	if e.RouterLink != "" {
		result = result.Union(mgmt.Fields(RouterNodeRouterLink))
	}
	if e.Cost != 0 {
		result = result.Union(mgmt.Fields(RouterNodeCost))
	}
	if e.LastTopoChange != 0 {
		result = result.Union(mgmt.Fields(RouterNodeLastTopoChange))
	}
	if e.Index != 0 {
		result = result.Union(mgmt.Fields(RouterNodeIndex))
	}
	return result
}
