// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type RouterMetrics struct {
	Name                            string
	Identity                        string
	Type                            string
	Id                              string
	Version                         string
	AddrCount                       int64
	LinkCount                       int64
	NodeCount                       int64
	AutoLinkCount                   int64
	ConnectionCount                 uint64
	PresettledDeliveries            int64
	DroppedPresettledDeliveries     int64
	AcceptedDeliveries              int64
	RejectedDeliveries              int64
	ReleasedDeliveries              int64
	ModifiedDeliveries              int64
	DeliveriesIngress               int64
	DeliveriesEgress                int64
	DeliveriesTransit               int64
	DeliveriesIngressRouteContainer int64
	DeliveriesEgressRouteContainer  int64
	DeliveriesIngressInterNetwork   int64
	DeliveriesEgressInterNetwork    int64
	ResidentMemoryUsage             int64
	MemoryUsage                     int64
	UptimeSeconds                   int64
	DeliveriesStuck                 int64
	DeliveriesDelayed10Sec          int64
	DeliveriesDelayed1Sec           int64
	ConnectionCounters              map[string]any
}

const (
	RouterMetricsName mgmt.Field[RouterMetrics] = iota
	RouterMetricsIdentity
	RouterMetricsTypeField
	RouterMetricsId
	RouterMetricsVersion
	RouterMetricsAddrCount
	RouterMetricsLinkCount
	RouterMetricsNodeCount
	RouterMetricsAutoLinkCount
	RouterMetricsConnectionCount
	RouterMetricsPresettledDeliveries
	RouterMetricsDroppedPresettledDeliveries
	RouterMetricsAcceptedDeliveries
	RouterMetricsRejectedDeliveries
	RouterMetricsReleasedDeliveries
	RouterMetricsModifiedDeliveries
	RouterMetricsDeliveriesIngress
	RouterMetricsDeliveriesEgress
	RouterMetricsDeliveriesTransit
	RouterMetricsDeliveriesIngressRouteContainer
	RouterMetricsDeliveriesEgressRouteContainer
	RouterMetricsDeliveriesIngressInterNetwork
	RouterMetricsDeliveriesEgressInterNetwork
	RouterMetricsResidentMemoryUsage
	RouterMetricsMemoryUsage
	RouterMetricsUptimeSeconds
	RouterMetricsDeliveriesStuck
	RouterMetricsDeliveriesDelayed10Sec
	RouterMetricsDeliveriesDelayed1Sec
	RouterMetricsConnectionCounters
)

var RouterMetricsType = mgmt.NewType("io.skupper.router.routerMetrics", "routerMetrics", true, []string{"QUERY", "READ"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: false, Update: false, Default: "io.skupper.router.routerMetrics", HasDefault: true},
	{Name: "id", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "version", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "addrCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "linkCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "nodeCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "autoLinkCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "connectionCount", Kind: mgmt.Uint64Attribute, Required: false, Create: false, Update: false},
	{Name: "presettledDeliveries", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "droppedPresettledDeliveries", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "acceptedDeliveries", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "rejectedDeliveries", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "releasedDeliveries", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "modifiedDeliveries", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesIngress", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesEgress", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesTransit", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesIngressRouteContainer", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesEgressRouteContainer", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesIngressInterNetwork", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesEgressInterNetwork", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "residentMemoryUsage", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "memoryUsage", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "uptimeSeconds", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesStuck", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesDelayed10Sec", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesDelayed1Sec", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "connectionCounters", Kind: mgmt.MapAttribute, Required: false, Create: false, Update: false},
})

var RouterMetricsAllFields = mgmt.Fields(RouterMetricsName, RouterMetricsIdentity, RouterMetricsTypeField, RouterMetricsId, RouterMetricsVersion, RouterMetricsAddrCount, RouterMetricsLinkCount, RouterMetricsNodeCount, RouterMetricsAutoLinkCount, RouterMetricsConnectionCount, RouterMetricsPresettledDeliveries, RouterMetricsDroppedPresettledDeliveries, RouterMetricsAcceptedDeliveries, RouterMetricsRejectedDeliveries, RouterMetricsReleasedDeliveries, RouterMetricsModifiedDeliveries, RouterMetricsDeliveriesIngress, RouterMetricsDeliveriesEgress, RouterMetricsDeliveriesTransit, RouterMetricsDeliveriesIngressRouteContainer, RouterMetricsDeliveriesEgressRouteContainer, RouterMetricsDeliveriesIngressInterNetwork, RouterMetricsDeliveriesEgressInterNetwork, RouterMetricsResidentMemoryUsage, RouterMetricsMemoryUsage, RouterMetricsUptimeSeconds, RouterMetricsDeliveriesStuck, RouterMetricsDeliveriesDelayed10Sec, RouterMetricsDeliveriesDelayed1Sec, RouterMetricsConnectionCounters)

var RouterMetricsCreateFields mgmt.FieldSet[RouterMetrics]

var RouterMetricsUpdateFields mgmt.FieldSet[RouterMetrics]

func (*RouterMetrics) ManagementType() *mgmt.Type { return RouterMetricsType }

func (e *RouterMetrics) SetManagementField(field mgmt.Field[RouterMetrics], value any) error {
	switch field {
	case RouterMetricsName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case RouterMetricsIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case RouterMetricsTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case RouterMetricsId:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "id", value)
		}
		e.Id = decoded
		return nil
	case RouterMetricsVersion:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "version", value)
		}
		e.Version = decoded
		return nil
	case RouterMetricsAddrCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "addrCount", value)
		}
		e.AddrCount = decoded
		return nil
	case RouterMetricsLinkCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "linkCount", value)
		}
		e.LinkCount = decoded
		return nil
	case RouterMetricsNodeCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "nodeCount", value)
		}
		e.NodeCount = decoded
		return nil
	case RouterMetricsAutoLinkCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "autoLinkCount", value)
		}
		e.AutoLinkCount = decoded
		return nil
	case RouterMetricsConnectionCount:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "connectionCount", value)
		}
		e.ConnectionCount = decoded
		return nil
	case RouterMetricsPresettledDeliveries:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "presettledDeliveries", value)
		}
		e.PresettledDeliveries = decoded
		return nil
	case RouterMetricsDroppedPresettledDeliveries:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "droppedPresettledDeliveries", value)
		}
		e.DroppedPresettledDeliveries = decoded
		return nil
	case RouterMetricsAcceptedDeliveries:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "acceptedDeliveries", value)
		}
		e.AcceptedDeliveries = decoded
		return nil
	case RouterMetricsRejectedDeliveries:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "rejectedDeliveries", value)
		}
		e.RejectedDeliveries = decoded
		return nil
	case RouterMetricsReleasedDeliveries:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "releasedDeliveries", value)
		}
		e.ReleasedDeliveries = decoded
		return nil
	case RouterMetricsModifiedDeliveries:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "modifiedDeliveries", value)
		}
		e.ModifiedDeliveries = decoded
		return nil
	case RouterMetricsDeliveriesIngress:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "deliveriesIngress", value)
		}
		e.DeliveriesIngress = decoded
		return nil
	case RouterMetricsDeliveriesEgress:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "deliveriesEgress", value)
		}
		e.DeliveriesEgress = decoded
		return nil
	case RouterMetricsDeliveriesTransit:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "deliveriesTransit", value)
		}
		e.DeliveriesTransit = decoded
		return nil
	case RouterMetricsDeliveriesIngressRouteContainer:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "deliveriesIngressRouteContainer", value)
		}
		e.DeliveriesIngressRouteContainer = decoded
		return nil
	case RouterMetricsDeliveriesEgressRouteContainer:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "deliveriesEgressRouteContainer", value)
		}
		e.DeliveriesEgressRouteContainer = decoded
		return nil
	case RouterMetricsDeliveriesIngressInterNetwork:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "deliveriesIngressInterNetwork", value)
		}
		e.DeliveriesIngressInterNetwork = decoded
		return nil
	case RouterMetricsDeliveriesEgressInterNetwork:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "deliveriesEgressInterNetwork", value)
		}
		e.DeliveriesEgressInterNetwork = decoded
		return nil
	case RouterMetricsResidentMemoryUsage:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "residentMemoryUsage", value)
		}
		e.ResidentMemoryUsage = decoded
		return nil
	case RouterMetricsMemoryUsage:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "memoryUsage", value)
		}
		e.MemoryUsage = decoded
		return nil
	case RouterMetricsUptimeSeconds:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "uptimeSeconds", value)
		}
		e.UptimeSeconds = decoded
		return nil
	case RouterMetricsDeliveriesStuck:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "deliveriesStuck", value)
		}
		e.DeliveriesStuck = decoded
		return nil
	case RouterMetricsDeliveriesDelayed10Sec:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "deliveriesDelayed10Sec", value)
		}
		e.DeliveriesDelayed10Sec = decoded
		return nil
	case RouterMetricsDeliveriesDelayed1Sec:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "deliveriesDelayed1Sec", value)
		}
		e.DeliveriesDelayed1Sec = decoded
		return nil
	case RouterMetricsConnectionCounters:
		decoded, ok := mgmt.AsMap(value)
		if !ok {
			return mgmt.DecodeError(RouterMetricsType.Name, "connectionCounters", value)
		}
		e.ConnectionCounters = decoded
		return nil
	}
	return mgmt.DecodeError(RouterMetricsType.Name, "<unknown>", value)
}

func (e *RouterMetrics) ManagementValue(field mgmt.Field[RouterMetrics]) any {
	switch field {
	case RouterMetricsName:
		return e.Name
	case RouterMetricsIdentity:
		return e.Identity
	case RouterMetricsTypeField:
		return e.Type
	case RouterMetricsId:
		return e.Id
	case RouterMetricsVersion:
		return e.Version
	case RouterMetricsAddrCount:
		return e.AddrCount
	case RouterMetricsLinkCount:
		return e.LinkCount
	case RouterMetricsNodeCount:
		return e.NodeCount
	case RouterMetricsAutoLinkCount:
		return e.AutoLinkCount
	case RouterMetricsConnectionCount:
		return e.ConnectionCount
	case RouterMetricsPresettledDeliveries:
		return e.PresettledDeliveries
	case RouterMetricsDroppedPresettledDeliveries:
		return e.DroppedPresettledDeliveries
	case RouterMetricsAcceptedDeliveries:
		return e.AcceptedDeliveries
	case RouterMetricsRejectedDeliveries:
		return e.RejectedDeliveries
	case RouterMetricsReleasedDeliveries:
		return e.ReleasedDeliveries
	case RouterMetricsModifiedDeliveries:
		return e.ModifiedDeliveries
	case RouterMetricsDeliveriesIngress:
		return e.DeliveriesIngress
	case RouterMetricsDeliveriesEgress:
		return e.DeliveriesEgress
	case RouterMetricsDeliveriesTransit:
		return e.DeliveriesTransit
	case RouterMetricsDeliveriesIngressRouteContainer:
		return e.DeliveriesIngressRouteContainer
	case RouterMetricsDeliveriesEgressRouteContainer:
		return e.DeliveriesEgressRouteContainer
	case RouterMetricsDeliveriesIngressInterNetwork:
		return e.DeliveriesIngressInterNetwork
	case RouterMetricsDeliveriesEgressInterNetwork:
		return e.DeliveriesEgressInterNetwork
	case RouterMetricsResidentMemoryUsage:
		return e.ResidentMemoryUsage
	case RouterMetricsMemoryUsage:
		return e.MemoryUsage
	case RouterMetricsUptimeSeconds:
		return e.UptimeSeconds
	case RouterMetricsDeliveriesStuck:
		return e.DeliveriesStuck
	case RouterMetricsDeliveriesDelayed10Sec:
		return e.DeliveriesDelayed10Sec
	case RouterMetricsDeliveriesDelayed1Sec:
		return e.DeliveriesDelayed1Sec
	case RouterMetricsConnectionCounters:
		return e.ConnectionCounters
	}
	return nil
}

func (e *RouterMetrics) Equal(other *RouterMetrics, fields mgmt.FieldSet[RouterMetrics]) bool {
	if fields.Has(RouterMetricsName) && e.Name != other.Name {
		return false
	}
	if fields.Has(RouterMetricsIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(RouterMetricsTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(RouterMetricsId) && e.Id != other.Id {
		return false
	}
	if fields.Has(RouterMetricsVersion) && e.Version != other.Version {
		return false
	}
	if fields.Has(RouterMetricsAddrCount) && e.AddrCount != other.AddrCount {
		return false
	}
	if fields.Has(RouterMetricsLinkCount) && e.LinkCount != other.LinkCount {
		return false
	}
	if fields.Has(RouterMetricsNodeCount) && e.NodeCount != other.NodeCount {
		return false
	}
	if fields.Has(RouterMetricsAutoLinkCount) && e.AutoLinkCount != other.AutoLinkCount {
		return false
	}
	if fields.Has(RouterMetricsConnectionCount) && e.ConnectionCount != other.ConnectionCount {
		return false
	}
	if fields.Has(RouterMetricsPresettledDeliveries) && e.PresettledDeliveries != other.PresettledDeliveries {
		return false
	}
	if fields.Has(RouterMetricsDroppedPresettledDeliveries) && e.DroppedPresettledDeliveries != other.DroppedPresettledDeliveries {
		return false
	}
	if fields.Has(RouterMetricsAcceptedDeliveries) && e.AcceptedDeliveries != other.AcceptedDeliveries {
		return false
	}
	if fields.Has(RouterMetricsRejectedDeliveries) && e.RejectedDeliveries != other.RejectedDeliveries {
		return false
	}
	if fields.Has(RouterMetricsReleasedDeliveries) && e.ReleasedDeliveries != other.ReleasedDeliveries {
		return false
	}
	if fields.Has(RouterMetricsModifiedDeliveries) && e.ModifiedDeliveries != other.ModifiedDeliveries {
		return false
	}
	if fields.Has(RouterMetricsDeliveriesIngress) && e.DeliveriesIngress != other.DeliveriesIngress {
		return false
	}
	if fields.Has(RouterMetricsDeliveriesEgress) && e.DeliveriesEgress != other.DeliveriesEgress {
		return false
	}
	if fields.Has(RouterMetricsDeliveriesTransit) && e.DeliveriesTransit != other.DeliveriesTransit {
		return false
	}
	if fields.Has(RouterMetricsDeliveriesIngressRouteContainer) && e.DeliveriesIngressRouteContainer != other.DeliveriesIngressRouteContainer {
		return false
	}
	if fields.Has(RouterMetricsDeliveriesEgressRouteContainer) && e.DeliveriesEgressRouteContainer != other.DeliveriesEgressRouteContainer {
		return false
	}
	if fields.Has(RouterMetricsDeliveriesIngressInterNetwork) && e.DeliveriesIngressInterNetwork != other.DeliveriesIngressInterNetwork {
		return false
	}
	if fields.Has(RouterMetricsDeliveriesEgressInterNetwork) && e.DeliveriesEgressInterNetwork != other.DeliveriesEgressInterNetwork {
		return false
	}
	if fields.Has(RouterMetricsResidentMemoryUsage) && e.ResidentMemoryUsage != other.ResidentMemoryUsage {
		return false
	}
	if fields.Has(RouterMetricsMemoryUsage) && e.MemoryUsage != other.MemoryUsage {
		return false
	}
	if fields.Has(RouterMetricsUptimeSeconds) && e.UptimeSeconds != other.UptimeSeconds {
		return false
	}
	if fields.Has(RouterMetricsDeliveriesStuck) && e.DeliveriesStuck != other.DeliveriesStuck {
		return false
	}
	if fields.Has(RouterMetricsDeliveriesDelayed10Sec) && e.DeliveriesDelayed10Sec != other.DeliveriesDelayed10Sec {
		return false
	}
	if fields.Has(RouterMetricsDeliveriesDelayed1Sec) && e.DeliveriesDelayed1Sec != other.DeliveriesDelayed1Sec {
		return false
	}
	if fields.Has(RouterMetricsConnectionCounters) && !mgmt.EqualValues(e.ConnectionCounters, other.ConnectionCounters) {
		return false
	}
	return true
}

func (e *RouterMetrics) Diff(other *RouterMetrics, fields mgmt.FieldSet[RouterMetrics]) mgmt.FieldSet[RouterMetrics] {
	var result mgmt.FieldSet[RouterMetrics]
	if fields.Has(RouterMetricsName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(RouterMetricsName))
	}
	if fields.Has(RouterMetricsIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(RouterMetricsIdentity))
	}
	if fields.Has(RouterMetricsTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(RouterMetricsTypeField))
	}
	if fields.Has(RouterMetricsId) && e.Id != other.Id {
		result = result.Union(mgmt.Fields(RouterMetricsId))
	}
	if fields.Has(RouterMetricsVersion) && e.Version != other.Version {
		result = result.Union(mgmt.Fields(RouterMetricsVersion))
	}
	if fields.Has(RouterMetricsAddrCount) && e.AddrCount != other.AddrCount {
		result = result.Union(mgmt.Fields(RouterMetricsAddrCount))
	}
	if fields.Has(RouterMetricsLinkCount) && e.LinkCount != other.LinkCount {
		result = result.Union(mgmt.Fields(RouterMetricsLinkCount))
	}
	if fields.Has(RouterMetricsNodeCount) && e.NodeCount != other.NodeCount {
		result = result.Union(mgmt.Fields(RouterMetricsNodeCount))
	}
	if fields.Has(RouterMetricsAutoLinkCount) && e.AutoLinkCount != other.AutoLinkCount {
		result = result.Union(mgmt.Fields(RouterMetricsAutoLinkCount))
	}
	if fields.Has(RouterMetricsConnectionCount) && e.ConnectionCount != other.ConnectionCount {
		result = result.Union(mgmt.Fields(RouterMetricsConnectionCount))
	}
	if fields.Has(RouterMetricsPresettledDeliveries) && e.PresettledDeliveries != other.PresettledDeliveries {
		result = result.Union(mgmt.Fields(RouterMetricsPresettledDeliveries))
	}
	if fields.Has(RouterMetricsDroppedPresettledDeliveries) && e.DroppedPresettledDeliveries != other.DroppedPresettledDeliveries {
		result = result.Union(mgmt.Fields(RouterMetricsDroppedPresettledDeliveries))
	}
	if fields.Has(RouterMetricsAcceptedDeliveries) && e.AcceptedDeliveries != other.AcceptedDeliveries {
		result = result.Union(mgmt.Fields(RouterMetricsAcceptedDeliveries))
	}
	if fields.Has(RouterMetricsRejectedDeliveries) && e.RejectedDeliveries != other.RejectedDeliveries {
		result = result.Union(mgmt.Fields(RouterMetricsRejectedDeliveries))
	}
	if fields.Has(RouterMetricsReleasedDeliveries) && e.ReleasedDeliveries != other.ReleasedDeliveries {
		result = result.Union(mgmt.Fields(RouterMetricsReleasedDeliveries))
	}
	if fields.Has(RouterMetricsModifiedDeliveries) && e.ModifiedDeliveries != other.ModifiedDeliveries {
		result = result.Union(mgmt.Fields(RouterMetricsModifiedDeliveries))
	}
	if fields.Has(RouterMetricsDeliveriesIngress) && e.DeliveriesIngress != other.DeliveriesIngress {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesIngress))
	}
	if fields.Has(RouterMetricsDeliveriesEgress) && e.DeliveriesEgress != other.DeliveriesEgress {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesEgress))
	}
	if fields.Has(RouterMetricsDeliveriesTransit) && e.DeliveriesTransit != other.DeliveriesTransit {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesTransit))
	}
	if fields.Has(RouterMetricsDeliveriesIngressRouteContainer) && e.DeliveriesIngressRouteContainer != other.DeliveriesIngressRouteContainer {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesIngressRouteContainer))
	}
	if fields.Has(RouterMetricsDeliveriesEgressRouteContainer) && e.DeliveriesEgressRouteContainer != other.DeliveriesEgressRouteContainer {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesEgressRouteContainer))
	}
	if fields.Has(RouterMetricsDeliveriesIngressInterNetwork) && e.DeliveriesIngressInterNetwork != other.DeliveriesIngressInterNetwork {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesIngressInterNetwork))
	}
	if fields.Has(RouterMetricsDeliveriesEgressInterNetwork) && e.DeliveriesEgressInterNetwork != other.DeliveriesEgressInterNetwork {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesEgressInterNetwork))
	}
	if fields.Has(RouterMetricsResidentMemoryUsage) && e.ResidentMemoryUsage != other.ResidentMemoryUsage {
		result = result.Union(mgmt.Fields(RouterMetricsResidentMemoryUsage))
	}
	if fields.Has(RouterMetricsMemoryUsage) && e.MemoryUsage != other.MemoryUsage {
		result = result.Union(mgmt.Fields(RouterMetricsMemoryUsage))
	}
	if fields.Has(RouterMetricsUptimeSeconds) && e.UptimeSeconds != other.UptimeSeconds {
		result = result.Union(mgmt.Fields(RouterMetricsUptimeSeconds))
	}
	if fields.Has(RouterMetricsDeliveriesStuck) && e.DeliveriesStuck != other.DeliveriesStuck {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesStuck))
	}
	if fields.Has(RouterMetricsDeliveriesDelayed10Sec) && e.DeliveriesDelayed10Sec != other.DeliveriesDelayed10Sec {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesDelayed10Sec))
	}
	if fields.Has(RouterMetricsDeliveriesDelayed1Sec) && e.DeliveriesDelayed1Sec != other.DeliveriesDelayed1Sec {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesDelayed1Sec))
	}
	if fields.Has(RouterMetricsConnectionCounters) && !mgmt.EqualValues(e.ConnectionCounters, other.ConnectionCounters) {
		result = result.Union(mgmt.Fields(RouterMetricsConnectionCounters))
	}
	return result
}

func (e *RouterMetrics) ApplyDefaults(present mgmt.FieldSet[RouterMetrics]) {
	if !present.Has(RouterMetricsTypeField) {
		e.Type = "io.skupper.router.routerMetrics"
	}
}

func (e *RouterMetrics) NonZeroFields() mgmt.FieldSet[RouterMetrics] {
	var result mgmt.FieldSet[RouterMetrics]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(RouterMetricsName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(RouterMetricsIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(RouterMetricsTypeField))
	}
	if e.Id != "" {
		result = result.Union(mgmt.Fields(RouterMetricsId))
	}
	if e.Version != "" {
		result = result.Union(mgmt.Fields(RouterMetricsVersion))
	}
	if e.AddrCount != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsAddrCount))
	}
	if e.LinkCount != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsLinkCount))
	}
	if e.NodeCount != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsNodeCount))
	}
	if e.AutoLinkCount != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsAutoLinkCount))
	}
	if e.ConnectionCount != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsConnectionCount))
	}
	if e.PresettledDeliveries != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsPresettledDeliveries))
	}
	if e.DroppedPresettledDeliveries != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsDroppedPresettledDeliveries))
	}
	if e.AcceptedDeliveries != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsAcceptedDeliveries))
	}
	if e.RejectedDeliveries != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsRejectedDeliveries))
	}
	if e.ReleasedDeliveries != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsReleasedDeliveries))
	}
	if e.ModifiedDeliveries != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsModifiedDeliveries))
	}
	if e.DeliveriesIngress != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesIngress))
	}
	if e.DeliveriesEgress != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesEgress))
	}
	if e.DeliveriesTransit != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesTransit))
	}
	if e.DeliveriesIngressRouteContainer != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesIngressRouteContainer))
	}
	if e.DeliveriesEgressRouteContainer != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesEgressRouteContainer))
	}
	if e.DeliveriesIngressInterNetwork != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesIngressInterNetwork))
	}
	if e.DeliveriesEgressInterNetwork != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesEgressInterNetwork))
	}
	if e.ResidentMemoryUsage != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsResidentMemoryUsage))
	}
	if e.MemoryUsage != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsMemoryUsage))
	}
	if e.UptimeSeconds != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsUptimeSeconds))
	}
	if e.DeliveriesStuck != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesStuck))
	}
	if e.DeliveriesDelayed10Sec != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesDelayed10Sec))
	}
	if e.DeliveriesDelayed1Sec != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsDeliveriesDelayed1Sec))
	}
	if len(e.ConnectionCounters) != 0 {
		result = result.Union(mgmt.Fields(RouterMetricsConnectionCounters))
	}
	return result
}
