// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type TcpConnector struct {
	Name              string
	Identity          string
	Type              string
	Address           string
	Host              string
	Port              string
	SiteId            string
	ProcessId         string
	ConnectionsOpened uint64
	ConnectionsClosed uint64
	BytesIn           uint64
	BytesOut          uint64
	SslProfile        string
	VerifyHostname    bool
}

const (
	TcpConnectorName mgmt.Field[TcpConnector] = iota
	TcpConnectorIdentity
	TcpConnectorTypeField
	TcpConnectorAddress
	TcpConnectorHost
	TcpConnectorPort
	TcpConnectorSiteId
	TcpConnectorProcessId
	TcpConnectorConnectionsOpened
	TcpConnectorConnectionsClosed
	TcpConnectorBytesIn
	TcpConnectorBytesOut
	TcpConnectorSslProfile
	TcpConnectorVerifyHostname
)

var TcpConnectorType = mgmt.NewType("io.skupper.router.tcpConnector", "tcpConnector", false, []string{"QUERY", "READ", "CREATE", "DELETE"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: true, Update: false, Default: "io.skupper.router.tcpConnector", HasDefault: true},
	{Name: "address", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "host", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: "127.0.0.1", HasDefault: true},
	{Name: "port", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "siteId", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "processId", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "connectionsOpened", Kind: mgmt.Uint64Attribute, Required: false, Create: false, Update: false},
	{Name: "connectionsClosed", Kind: mgmt.Uint64Attribute, Required: false, Create: false, Update: false},
	{Name: "bytesIn", Kind: mgmt.Uint64Attribute, Required: false, Create: false, Update: false},
	{Name: "bytesOut", Kind: mgmt.Uint64Attribute, Required: false, Create: false, Update: false},
	{Name: "sslProfile", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "verifyHostname", Kind: mgmt.BoolAttribute, Required: false, Create: true, Update: false, Default: true, HasDefault: true},
})

var TcpConnectorAllFields = mgmt.Fields(TcpConnectorName, TcpConnectorIdentity, TcpConnectorTypeField, TcpConnectorAddress, TcpConnectorHost, TcpConnectorPort, TcpConnectorSiteId, TcpConnectorProcessId, TcpConnectorConnectionsOpened, TcpConnectorConnectionsClosed, TcpConnectorBytesIn, TcpConnectorBytesOut, TcpConnectorSslProfile, TcpConnectorVerifyHostname)

var TcpConnectorCreateFields = mgmt.Fields(TcpConnectorName, TcpConnectorTypeField, TcpConnectorAddress, TcpConnectorHost, TcpConnectorPort, TcpConnectorSiteId, TcpConnectorProcessId, TcpConnectorSslProfile, TcpConnectorVerifyHostname)

var TcpConnectorUpdateFields mgmt.FieldSet[TcpConnector]

func (*TcpConnector) ManagementType() *mgmt.Type { return TcpConnectorType }

func (e *TcpConnector) SetManagementField(field mgmt.Field[TcpConnector], value any) error {
	switch field {
	case TcpConnectorName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case TcpConnectorIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case TcpConnectorTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case TcpConnectorAddress:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "address", value)
		}
		e.Address = decoded
		return nil
	case TcpConnectorHost:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "host", value)
		}
		e.Host = decoded
		return nil
	case TcpConnectorPort:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "port", value)
		}
		e.Port = decoded
		return nil
	case TcpConnectorSiteId:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "siteId", value)
		}
		e.SiteId = decoded
		return nil
	case TcpConnectorProcessId:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "processId", value)
		}
		e.ProcessId = decoded
		return nil
	case TcpConnectorConnectionsOpened:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "connectionsOpened", value)
		}
		e.ConnectionsOpened = decoded
		return nil
	case TcpConnectorConnectionsClosed:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "connectionsClosed", value)
		}
		e.ConnectionsClosed = decoded
		return nil
	case TcpConnectorBytesIn:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "bytesIn", value)
		}
		e.BytesIn = decoded
		return nil
	case TcpConnectorBytesOut:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "bytesOut", value)
		}
		e.BytesOut = decoded
		return nil
	case TcpConnectorSslProfile:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "sslProfile", value)
		}
		e.SslProfile = decoded
		return nil
	case TcpConnectorVerifyHostname:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(TcpConnectorType.Name, "verifyHostname", value)
		}
		e.VerifyHostname = decoded
		return nil
	}
	return mgmt.DecodeError(TcpConnectorType.Name, "<unknown>", value)
}

func (e *TcpConnector) ManagementValue(field mgmt.Field[TcpConnector]) any {
	switch field {
	case TcpConnectorName:
		return e.Name
	case TcpConnectorIdentity:
		return e.Identity
	case TcpConnectorTypeField:
		return e.Type
	case TcpConnectorAddress:
		return e.Address
	case TcpConnectorHost:
		return e.Host
	case TcpConnectorPort:
		return e.Port
	case TcpConnectorSiteId:
		return e.SiteId
	case TcpConnectorProcessId:
		return e.ProcessId
	case TcpConnectorConnectionsOpened:
		return e.ConnectionsOpened
	case TcpConnectorConnectionsClosed:
		return e.ConnectionsClosed
	case TcpConnectorBytesIn:
		return e.BytesIn
	case TcpConnectorBytesOut:
		return e.BytesOut
	case TcpConnectorSslProfile:
		return e.SslProfile
	case TcpConnectorVerifyHostname:
		return e.VerifyHostname
	}
	return nil
}

func (e *TcpConnector) Equal(other *TcpConnector, fields mgmt.FieldSet[TcpConnector]) bool {
	if fields.Has(TcpConnectorName) && e.Name != other.Name {
		return false
	}
	if fields.Has(TcpConnectorIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(TcpConnectorTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(TcpConnectorAddress) && e.Address != other.Address {
		return false
	}
	if fields.Has(TcpConnectorHost) && e.Host != other.Host {
		return false
	}
	if fields.Has(TcpConnectorPort) && e.Port != other.Port {
		return false
	}
	if fields.Has(TcpConnectorSiteId) && e.SiteId != other.SiteId {
		return false
	}
	if fields.Has(TcpConnectorProcessId) && e.ProcessId != other.ProcessId {
		return false
	}
	if fields.Has(TcpConnectorConnectionsOpened) && e.ConnectionsOpened != other.ConnectionsOpened {
		return false
	}
	if fields.Has(TcpConnectorConnectionsClosed) && e.ConnectionsClosed != other.ConnectionsClosed {
		return false
	}
	if fields.Has(TcpConnectorBytesIn) && e.BytesIn != other.BytesIn {
		return false
	}
	if fields.Has(TcpConnectorBytesOut) && e.BytesOut != other.BytesOut {
		return false
	}
	if fields.Has(TcpConnectorSslProfile) && e.SslProfile != other.SslProfile {
		return false
	}
	if fields.Has(TcpConnectorVerifyHostname) && e.VerifyHostname != other.VerifyHostname {
		return false
	}
	return true
}

func (e *TcpConnector) Diff(other *TcpConnector, fields mgmt.FieldSet[TcpConnector]) mgmt.FieldSet[TcpConnector] {
	var result mgmt.FieldSet[TcpConnector]
	if fields.Has(TcpConnectorName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(TcpConnectorName))
	}
	if fields.Has(TcpConnectorIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(TcpConnectorIdentity))
	}
	if fields.Has(TcpConnectorTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(TcpConnectorTypeField))
	}
	if fields.Has(TcpConnectorAddress) && e.Address != other.Address {
		result = result.Union(mgmt.Fields(TcpConnectorAddress))
	}
	if fields.Has(TcpConnectorHost) && e.Host != other.Host {
		result = result.Union(mgmt.Fields(TcpConnectorHost))
	}
	if fields.Has(TcpConnectorPort) && e.Port != other.Port {
		result = result.Union(mgmt.Fields(TcpConnectorPort))
	}
	if fields.Has(TcpConnectorSiteId) && e.SiteId != other.SiteId {
		result = result.Union(mgmt.Fields(TcpConnectorSiteId))
	}
	if fields.Has(TcpConnectorProcessId) && e.ProcessId != other.ProcessId {
		result = result.Union(mgmt.Fields(TcpConnectorProcessId))
	}
	if fields.Has(TcpConnectorConnectionsOpened) && e.ConnectionsOpened != other.ConnectionsOpened {
		result = result.Union(mgmt.Fields(TcpConnectorConnectionsOpened))
	}
	if fields.Has(TcpConnectorConnectionsClosed) && e.ConnectionsClosed != other.ConnectionsClosed {
		result = result.Union(mgmt.Fields(TcpConnectorConnectionsClosed))
	}
	if fields.Has(TcpConnectorBytesIn) && e.BytesIn != other.BytesIn {
		result = result.Union(mgmt.Fields(TcpConnectorBytesIn))
	}
	if fields.Has(TcpConnectorBytesOut) && e.BytesOut != other.BytesOut {
		result = result.Union(mgmt.Fields(TcpConnectorBytesOut))
	}
	if fields.Has(TcpConnectorSslProfile) && e.SslProfile != other.SslProfile {
		result = result.Union(mgmt.Fields(TcpConnectorSslProfile))
	}
	if fields.Has(TcpConnectorVerifyHostname) && e.VerifyHostname != other.VerifyHostname {
		result = result.Union(mgmt.Fields(TcpConnectorVerifyHostname))
	}
	return result
}

func (e *TcpConnector) ApplyDefaults(present mgmt.FieldSet[TcpConnector]) {
	if !present.Has(TcpConnectorTypeField) {
		e.Type = "io.skupper.router.tcpConnector"
	}
	if !present.Has(TcpConnectorHost) {
		e.Host = "127.0.0.1"
	}
	if !present.Has(TcpConnectorVerifyHostname) {
		e.VerifyHostname = true
	}
}

func (e *TcpConnector) NonZeroFields() mgmt.FieldSet[TcpConnector] {
	var result mgmt.FieldSet[TcpConnector]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(TcpConnectorName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(TcpConnectorIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(TcpConnectorTypeField))
	}
	if e.Address != "" {
		result = result.Union(mgmt.Fields(TcpConnectorAddress))
	}
	if e.Host != "" {
		result = result.Union(mgmt.Fields(TcpConnectorHost))
	}
	if e.Port != "" {
		result = result.Union(mgmt.Fields(TcpConnectorPort))
	}
	if e.SiteId != "" {
		result = result.Union(mgmt.Fields(TcpConnectorSiteId))
	}
	if e.ProcessId != "" {
		result = result.Union(mgmt.Fields(TcpConnectorProcessId))
	}
	if e.ConnectionsOpened != 0 {
		result = result.Union(mgmt.Fields(TcpConnectorConnectionsOpened))
	}
	if e.ConnectionsClosed != 0 {
		result = result.Union(mgmt.Fields(TcpConnectorConnectionsClosed))
	}
	if e.BytesIn != 0 {
		result = result.Union(mgmt.Fields(TcpConnectorBytesIn))
	}
	if e.BytesOut != 0 {
		result = result.Union(mgmt.Fields(TcpConnectorBytesOut))
	}
	if e.SslProfile != "" {
		result = result.Union(mgmt.Fields(TcpConnectorSslProfile))
	}
	if e.VerifyHostname {
		result = result.Union(mgmt.Fields(TcpConnectorVerifyHostname))
	}
	return result
}
