// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type RouterAddress struct {
	Name                            string
	Identity                        string
	Type                            string
	Distribution                    RouterDistribution
	InProcess                       int64
	SubscriberCount                 int64
	RemoteCount                     int64
	ContainerCount                  int64
	DeliveriesIngress               int64
	DeliveriesEgress                int64
	DeliveriesTransit               int64
	DeliveriesToContainer           int64
	DeliveriesFromContainer         int64
	DeliveriesIngressRouteContainer int64
	DeliveriesEgressRouteContainer  int64
	DeliveriesIngressInterNetwork   int64
	DeliveriesEgressInterNetwork    int64
	Key                             string
	RemoteHostRouters               []string
	TransitOutstanding              []int64
	TrackedDeliveries               int64
	Priority                        int64
	Watch                           bool
}

const (
	RouterAddressName mgmt.Field[RouterAddress] = iota
	RouterAddressIdentity
	RouterAddressTypeField
	RouterAddressDistribution
	RouterAddressInProcess
	RouterAddressSubscriberCount
	RouterAddressRemoteCount
	RouterAddressContainerCount
	RouterAddressDeliveriesIngress
	RouterAddressDeliveriesEgress
	RouterAddressDeliveriesTransit
	RouterAddressDeliveriesToContainer
	RouterAddressDeliveriesFromContainer
	RouterAddressDeliveriesIngressRouteContainer
	RouterAddressDeliveriesEgressRouteContainer
	RouterAddressDeliveriesIngressInterNetwork
	RouterAddressDeliveriesEgressInterNetwork
	RouterAddressKey
	RouterAddressRemoteHostRouters
	RouterAddressTransitOutstanding
	RouterAddressTrackedDeliveries
	RouterAddressPriority
	RouterAddressWatch
)

var RouterAddressType = mgmt.NewType("io.skupper.router.router.address", "router.address", true, []string{"QUERY", "READ"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: false, Update: false, Default: "io.skupper.router.router.address", HasDefault: true},
	{Name: "distribution", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false, Enum: routerDistributionValues},
	{Name: "inProcess", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "subscriberCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "remoteCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "containerCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesIngress", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesEgress", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesTransit", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesToContainer", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesFromContainer", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesIngressRouteContainer", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesEgressRouteContainer", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesIngressInterNetwork", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesEgressInterNetwork", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "key", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "remoteHostRouters", Kind: mgmt.ListAttribute, Required: false, Create: false, Update: false},
	{Name: "transitOutstanding", Kind: mgmt.ListAttribute, Required: false, Create: false, Update: false},
	{Name: "trackedDeliveries", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "priority", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "watch", Kind: mgmt.BoolAttribute, Required: false, Create: false, Update: false},
})

var RouterAddressAllFields = mgmt.Fields(RouterAddressName, RouterAddressIdentity, RouterAddressTypeField, RouterAddressDistribution, RouterAddressInProcess, RouterAddressSubscriberCount, RouterAddressRemoteCount, RouterAddressContainerCount, RouterAddressDeliveriesIngress, RouterAddressDeliveriesEgress, RouterAddressDeliveriesTransit, RouterAddressDeliveriesToContainer, RouterAddressDeliveriesFromContainer, RouterAddressDeliveriesIngressRouteContainer, RouterAddressDeliveriesEgressRouteContainer, RouterAddressDeliveriesIngressInterNetwork, RouterAddressDeliveriesEgressInterNetwork, RouterAddressKey, RouterAddressRemoteHostRouters, RouterAddressTransitOutstanding, RouterAddressTrackedDeliveries, RouterAddressPriority, RouterAddressWatch)

var RouterAddressCreateFields mgmt.FieldSet[RouterAddress]

var RouterAddressUpdateFields mgmt.FieldSet[RouterAddress]

func (*RouterAddress) ManagementType() *mgmt.Type { return RouterAddressType }

func (e *RouterAddress) SetManagementField(field mgmt.Field[RouterAddress], value any) error {
	switch field {
	case RouterAddressName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case RouterAddressIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case RouterAddressTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case RouterAddressDistribution:
		decoded, ok := mgmt.AsEnum(value, routerDistributionValues)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "distribution", value)
		}
		e.Distribution = RouterDistribution(decoded)
		return nil
	case RouterAddressInProcess:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "inProcess", value)
		}
		e.InProcess = decoded
		return nil
	case RouterAddressSubscriberCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "subscriberCount", value)
		}
		e.SubscriberCount = decoded
		return nil
	case RouterAddressRemoteCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "remoteCount", value)
		}
		e.RemoteCount = decoded
		return nil
	case RouterAddressContainerCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "containerCount", value)
		}
		e.ContainerCount = decoded
		return nil
	case RouterAddressDeliveriesIngress:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "deliveriesIngress", value)
		}
		e.DeliveriesIngress = decoded
		return nil
	case RouterAddressDeliveriesEgress:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "deliveriesEgress", value)
		}
		e.DeliveriesEgress = decoded
		return nil
	case RouterAddressDeliveriesTransit:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "deliveriesTransit", value)
		}
		e.DeliveriesTransit = decoded
		return nil
	case RouterAddressDeliveriesToContainer:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "deliveriesToContainer", value)
		}
		e.DeliveriesToContainer = decoded
		return nil
	case RouterAddressDeliveriesFromContainer:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "deliveriesFromContainer", value)
		}
		e.DeliveriesFromContainer = decoded
		return nil
	case RouterAddressDeliveriesIngressRouteContainer:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "deliveriesIngressRouteContainer", value)
		}
		e.DeliveriesIngressRouteContainer = decoded
		return nil
	case RouterAddressDeliveriesEgressRouteContainer:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "deliveriesEgressRouteContainer", value)
		}
		e.DeliveriesEgressRouteContainer = decoded
		return nil
	case RouterAddressDeliveriesIngressInterNetwork:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "deliveriesIngressInterNetwork", value)
		}
		e.DeliveriesIngressInterNetwork = decoded
		return nil
	case RouterAddressDeliveriesEgressInterNetwork:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "deliveriesEgressInterNetwork", value)
		}
		e.DeliveriesEgressInterNetwork = decoded
		return nil
	case RouterAddressKey:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "key", value)
		}
		e.Key = decoded
		return nil
	case RouterAddressRemoteHostRouters:
		decoded, ok := mgmt.AsStringList(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "remoteHostRouters", value)
		}
		e.RemoteHostRouters = decoded
		return nil
	case RouterAddressTransitOutstanding:
		decoded, ok := mgmt.AsInt64List(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "transitOutstanding", value)
		}
		e.TransitOutstanding = decoded
		return nil
	case RouterAddressTrackedDeliveries:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "trackedDeliveries", value)
		}
		e.TrackedDeliveries = decoded
		return nil
	case RouterAddressPriority:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "priority", value)
		}
		e.Priority = decoded
		return nil
	case RouterAddressWatch:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(RouterAddressType.Name, "watch", value)
		}
		e.Watch = decoded
		return nil
	}
	return mgmt.DecodeError(RouterAddressType.Name, "<unknown>", value)
}

func (e *RouterAddress) ManagementValue(field mgmt.Field[RouterAddress]) any {
	switch field {
	case RouterAddressName:
		return e.Name
	case RouterAddressIdentity:
		return e.Identity
	case RouterAddressTypeField:
		return e.Type
	case RouterAddressDistribution:
		return string(e.Distribution)
	case RouterAddressInProcess:
		return e.InProcess
	case RouterAddressSubscriberCount:
		return e.SubscriberCount
	case RouterAddressRemoteCount:
		return e.RemoteCount
	case RouterAddressContainerCount:
		return e.ContainerCount
	case RouterAddressDeliveriesIngress:
		return e.DeliveriesIngress
	case RouterAddressDeliveriesEgress:
		return e.DeliveriesEgress
	case RouterAddressDeliveriesTransit:
		return e.DeliveriesTransit
	case RouterAddressDeliveriesToContainer:
		return e.DeliveriesToContainer
	case RouterAddressDeliveriesFromContainer:
		return e.DeliveriesFromContainer
	case RouterAddressDeliveriesIngressRouteContainer:
		return e.DeliveriesIngressRouteContainer
	case RouterAddressDeliveriesEgressRouteContainer:
		return e.DeliveriesEgressRouteContainer
	case RouterAddressDeliveriesIngressInterNetwork:
		return e.DeliveriesIngressInterNetwork
	case RouterAddressDeliveriesEgressInterNetwork:
		return e.DeliveriesEgressInterNetwork
	case RouterAddressKey:
		return e.Key
	case RouterAddressRemoteHostRouters:
		return e.RemoteHostRouters
	case RouterAddressTransitOutstanding:
		return e.TransitOutstanding
	case RouterAddressTrackedDeliveries:
		return e.TrackedDeliveries
	case RouterAddressPriority:
		return e.Priority
	case RouterAddressWatch:
		return e.Watch
	}
	return nil
}

func (e *RouterAddress) Equal(other *RouterAddress, fields mgmt.FieldSet[RouterAddress]) bool {
	if fields.Has(RouterAddressName) && e.Name != other.Name {
		return false
	}
	if fields.Has(RouterAddressIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(RouterAddressTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(RouterAddressDistribution) && e.Distribution != other.Distribution {
		return false
	}
	if fields.Has(RouterAddressInProcess) && e.InProcess != other.InProcess {
		return false
	}
	if fields.Has(RouterAddressSubscriberCount) && e.SubscriberCount != other.SubscriberCount {
		return false
	}
	if fields.Has(RouterAddressRemoteCount) && e.RemoteCount != other.RemoteCount {
		return false
	}
	if fields.Has(RouterAddressContainerCount) && e.ContainerCount != other.ContainerCount {
		return false
	}
	if fields.Has(RouterAddressDeliveriesIngress) && e.DeliveriesIngress != other.DeliveriesIngress {
		return false
	}
	if fields.Has(RouterAddressDeliveriesEgress) && e.DeliveriesEgress != other.DeliveriesEgress {
		return false
	}
	if fields.Has(RouterAddressDeliveriesTransit) && e.DeliveriesTransit != other.DeliveriesTransit {
		return false
	}
	if fields.Has(RouterAddressDeliveriesToContainer) && e.DeliveriesToContainer != other.DeliveriesToContainer {
		return false
	}
	if fields.Has(RouterAddressDeliveriesFromContainer) && e.DeliveriesFromContainer != other.DeliveriesFromContainer {
		return false
	}
	if fields.Has(RouterAddressDeliveriesIngressRouteContainer) && e.DeliveriesIngressRouteContainer != other.DeliveriesIngressRouteContainer {
		return false
	}
	if fields.Has(RouterAddressDeliveriesEgressRouteContainer) && e.DeliveriesEgressRouteContainer != other.DeliveriesEgressRouteContainer {
		return false
	}
	if fields.Has(RouterAddressDeliveriesIngressInterNetwork) && e.DeliveriesIngressInterNetwork != other.DeliveriesIngressInterNetwork {
		return false
	}
	if fields.Has(RouterAddressDeliveriesEgressInterNetwork) && e.DeliveriesEgressInterNetwork != other.DeliveriesEgressInterNetwork {
		return false
	}
	if fields.Has(RouterAddressKey) && e.Key != other.Key {
		return false
	}
	if fields.Has(RouterAddressRemoteHostRouters) && !mgmt.EqualValues(e.RemoteHostRouters, other.RemoteHostRouters) {
		return false
	}
	if fields.Has(RouterAddressTransitOutstanding) && !mgmt.EqualValues(e.TransitOutstanding, other.TransitOutstanding) {
		return false
	}
	if fields.Has(RouterAddressTrackedDeliveries) && e.TrackedDeliveries != other.TrackedDeliveries {
		return false
	}
	if fields.Has(RouterAddressPriority) && e.Priority != other.Priority {
		return false
	}
	if fields.Has(RouterAddressWatch) && e.Watch != other.Watch {
		return false
	}
	return true
}

func (e *RouterAddress) Diff(other *RouterAddress, fields mgmt.FieldSet[RouterAddress]) mgmt.FieldSet[RouterAddress] {
	var result mgmt.FieldSet[RouterAddress]
	if fields.Has(RouterAddressName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(RouterAddressName))
	}
	if fields.Has(RouterAddressIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(RouterAddressIdentity))
	}
	if fields.Has(RouterAddressTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(RouterAddressTypeField))
	}
	if fields.Has(RouterAddressDistribution) && e.Distribution != other.Distribution {
		result = result.Union(mgmt.Fields(RouterAddressDistribution))
	}
	if fields.Has(RouterAddressInProcess) && e.InProcess != other.InProcess {
		result = result.Union(mgmt.Fields(RouterAddressInProcess))
	}
	if fields.Has(RouterAddressSubscriberCount) && e.SubscriberCount != other.SubscriberCount {
		result = result.Union(mgmt.Fields(RouterAddressSubscriberCount))
	}
	if fields.Has(RouterAddressRemoteCount) && e.RemoteCount != other.RemoteCount {
		result = result.Union(mgmt.Fields(RouterAddressRemoteCount))
	}
	if fields.Has(RouterAddressContainerCount) && e.ContainerCount != other.ContainerCount {
		result = result.Union(mgmt.Fields(RouterAddressContainerCount))
	}
	if fields.Has(RouterAddressDeliveriesIngress) && e.DeliveriesIngress != other.DeliveriesIngress {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesIngress))
	}
	if fields.Has(RouterAddressDeliveriesEgress) && e.DeliveriesEgress != other.DeliveriesEgress {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesEgress))
	}
	if fields.Has(RouterAddressDeliveriesTransit) && e.DeliveriesTransit != other.DeliveriesTransit {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesTransit))
	}
	if fields.Has(RouterAddressDeliveriesToContainer) && e.DeliveriesToContainer != other.DeliveriesToContainer {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesToContainer))
	}
	if fields.Has(RouterAddressDeliveriesFromContainer) && e.DeliveriesFromContainer != other.DeliveriesFromContainer {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesFromContainer))
	}
	if fields.Has(RouterAddressDeliveriesIngressRouteContainer) && e.DeliveriesIngressRouteContainer != other.DeliveriesIngressRouteContainer {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesIngressRouteContainer))
	}
	if fields.Has(RouterAddressDeliveriesEgressRouteContainer) && e.DeliveriesEgressRouteContainer != other.DeliveriesEgressRouteContainer {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesEgressRouteContainer))
	}
	if fields.Has(RouterAddressDeliveriesIngressInterNetwork) && e.DeliveriesIngressInterNetwork != other.DeliveriesIngressInterNetwork {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesIngressInterNetwork))
	}
	if fields.Has(RouterAddressDeliveriesEgressInterNetwork) && e.DeliveriesEgressInterNetwork != other.DeliveriesEgressInterNetwork {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesEgressInterNetwork))
	}
	if fields.Has(RouterAddressKey) && e.Key != other.Key {
		result = result.Union(mgmt.Fields(RouterAddressKey))
	}
	if fields.Has(RouterAddressRemoteHostRouters) && !mgmt.EqualValues(e.RemoteHostRouters, other.RemoteHostRouters) {
		result = result.Union(mgmt.Fields(RouterAddressRemoteHostRouters))
	}
	if fields.Has(RouterAddressTransitOutstanding) && !mgmt.EqualValues(e.TransitOutstanding, other.TransitOutstanding) {
		result = result.Union(mgmt.Fields(RouterAddressTransitOutstanding))
	}
	if fields.Has(RouterAddressTrackedDeliveries) && e.TrackedDeliveries != other.TrackedDeliveries {
		result = result.Union(mgmt.Fields(RouterAddressTrackedDeliveries))
	}
	if fields.Has(RouterAddressPriority) && e.Priority != other.Priority {
		result = result.Union(mgmt.Fields(RouterAddressPriority))
	}
	if fields.Has(RouterAddressWatch) && e.Watch != other.Watch {
		result = result.Union(mgmt.Fields(RouterAddressWatch))
	}
	return result
}

func (e *RouterAddress) ApplyDefaults(present mgmt.FieldSet[RouterAddress]) {
	if !present.Has(RouterAddressTypeField) {
		e.Type = "io.skupper.router.router.address"
	}
}

func (e *RouterAddress) NonZeroFields() mgmt.FieldSet[RouterAddress] {
	var result mgmt.FieldSet[RouterAddress]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(RouterAddressName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(RouterAddressIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(RouterAddressTypeField))
	}
	if e.Distribution != "" {
		result = result.Union(mgmt.Fields(RouterAddressDistribution))
	}
	if e.InProcess != 0 {
		result = result.Union(mgmt.Fields(RouterAddressInProcess))
	}
	if e.SubscriberCount != 0 {
		result = result.Union(mgmt.Fields(RouterAddressSubscriberCount))
	}
	if e.RemoteCount != 0 {
		result = result.Union(mgmt.Fields(RouterAddressRemoteCount))
	}
	if e.ContainerCount != 0 {
		result = result.Union(mgmt.Fields(RouterAddressContainerCount))
	}
	if e.DeliveriesIngress != 0 {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesIngress))
	}
	if e.DeliveriesEgress != 0 {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesEgress))
	}
	if e.DeliveriesTransit != 0 {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesTransit))
	}
	if e.DeliveriesToContainer != 0 {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesToContainer))
	}
	if e.DeliveriesFromContainer != 0 {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesFromContainer))
	}
	if e.DeliveriesIngressRouteContainer != 0 {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesIngressRouteContainer))
	}
	if e.DeliveriesEgressRouteContainer != 0 {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesEgressRouteContainer))
	}
	if e.DeliveriesIngressInterNetwork != 0 {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesIngressInterNetwork))
	}
	if e.DeliveriesEgressInterNetwork != 0 {
		result = result.Union(mgmt.Fields(RouterAddressDeliveriesEgressInterNetwork))
	}
	if e.Key != "" {
		result = result.Union(mgmt.Fields(RouterAddressKey))
	}
	if len(e.RemoteHostRouters) != 0 {
		result = result.Union(mgmt.Fields(RouterAddressRemoteHostRouters))
	}
	if len(e.TransitOutstanding) != 0 {
		result = result.Union(mgmt.Fields(RouterAddressTransitOutstanding))
	}
	if e.TrackedDeliveries != 0 {
		result = result.Union(mgmt.Fields(RouterAddressTrackedDeliveries))
	}
	if e.Priority != 0 {
		result = result.Union(mgmt.Fields(RouterAddressPriority))
	}
	if e.Watch {
		result = result.Union(mgmt.Fields(RouterAddressWatch))
	}
	return result
}
