// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type LogStats struct {
	Name          string
	Identity      string
	Type          string
	DebugCount    int64
	InfoCount     int64
	NoticeCount   int64
	WarningCount  int64
	ErrorCount    int64
	CriticalCount int64
}

const (
	LogStatsName mgmt.Field[LogStats] = iota
	LogStatsIdentity
	LogStatsTypeField
	LogStatsDebugCount
	LogStatsInfoCount
	LogStatsNoticeCount
	LogStatsWarningCount
	LogStatsErrorCount
	LogStatsCriticalCount
)

var LogStatsType = mgmt.NewType("io.skupper.router.logStats", "logStats", false, []string{"QUERY", "READ"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: false, Update: false, Default: "io.skupper.router.logStats", HasDefault: true},
	{Name: "debugCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "infoCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "noticeCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "warningCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "errorCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "criticalCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
})

var LogStatsAllFields = mgmt.Fields(LogStatsName, LogStatsIdentity, LogStatsTypeField, LogStatsDebugCount, LogStatsInfoCount, LogStatsNoticeCount, LogStatsWarningCount, LogStatsErrorCount, LogStatsCriticalCount)

var LogStatsCreateFields mgmt.FieldSet[LogStats]

var LogStatsUpdateFields mgmt.FieldSet[LogStats]

func (*LogStats) ManagementType() *mgmt.Type { return LogStatsType }

func (e *LogStats) SetManagementField(field mgmt.Field[LogStats], value any) error {
	switch field {
	case LogStatsName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(LogStatsType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case LogStatsIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(LogStatsType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case LogStatsTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(LogStatsType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case LogStatsDebugCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(LogStatsType.Name, "debugCount", value)
		}
		e.DebugCount = decoded
		return nil
	case LogStatsInfoCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(LogStatsType.Name, "infoCount", value)
		}
		e.InfoCount = decoded
		return nil
	case LogStatsNoticeCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(LogStatsType.Name, "noticeCount", value)
		}
		e.NoticeCount = decoded
		return nil
	case LogStatsWarningCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(LogStatsType.Name, "warningCount", value)
		}
		e.WarningCount = decoded
		return nil
	case LogStatsErrorCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(LogStatsType.Name, "errorCount", value)
		}
		e.ErrorCount = decoded
		return nil
	case LogStatsCriticalCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(LogStatsType.Name, "criticalCount", value)
		}
		e.CriticalCount = decoded
		return nil
	}
	return mgmt.DecodeError(LogStatsType.Name, "<unknown>", value)
}

func (e *LogStats) ManagementValue(field mgmt.Field[LogStats]) any {
	switch field {
	case LogStatsName:
		return e.Name
	case LogStatsIdentity:
		return e.Identity
	case LogStatsTypeField:
		return e.Type
	case LogStatsDebugCount:
		return e.DebugCount
	case LogStatsInfoCount:
		return e.InfoCount
	case LogStatsNoticeCount:
		return e.NoticeCount
	case LogStatsWarningCount:
		return e.WarningCount
	case LogStatsErrorCount:
		return e.ErrorCount
	case LogStatsCriticalCount:
		return e.CriticalCount
	}
	return nil
}

func (e *LogStats) Equal(other *LogStats, fields mgmt.FieldSet[LogStats]) bool {
	if fields.Has(LogStatsName) && e.Name != other.Name {
		return false
	}
	if fields.Has(LogStatsIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(LogStatsTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(LogStatsDebugCount) && e.DebugCount != other.DebugCount {
		return false
	}
	if fields.Has(LogStatsInfoCount) && e.InfoCount != other.InfoCount {
		return false
	}
	if fields.Has(LogStatsNoticeCount) && e.NoticeCount != other.NoticeCount {
		return false
	}
	if fields.Has(LogStatsWarningCount) && e.WarningCount != other.WarningCount {
		return false
	}
	if fields.Has(LogStatsErrorCount) && e.ErrorCount != other.ErrorCount {
		return false
	}
	if fields.Has(LogStatsCriticalCount) && e.CriticalCount != other.CriticalCount {
		return false
	}
	return true
}

func (e *LogStats) Diff(other *LogStats, fields mgmt.FieldSet[LogStats]) mgmt.FieldSet[LogStats] {
	var result mgmt.FieldSet[LogStats]
	if fields.Has(LogStatsName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(LogStatsName))
	}
	if fields.Has(LogStatsIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(LogStatsIdentity))
	}
	if fields.Has(LogStatsTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(LogStatsTypeField))
	}
	if fields.Has(LogStatsDebugCount) && e.DebugCount != other.DebugCount {
		result = result.Union(mgmt.Fields(LogStatsDebugCount))
	}
	if fields.Has(LogStatsInfoCount) && e.InfoCount != other.InfoCount {
		result = result.Union(mgmt.Fields(LogStatsInfoCount))
	}
	if fields.Has(LogStatsNoticeCount) && e.NoticeCount != other.NoticeCount {
		result = result.Union(mgmt.Fields(LogStatsNoticeCount))
	}
	if fields.Has(LogStatsWarningCount) && e.WarningCount != other.WarningCount {
		result = result.Union(mgmt.Fields(LogStatsWarningCount))
	}
	if fields.Has(LogStatsErrorCount) && e.ErrorCount != other.ErrorCount {
		result = result.Union(mgmt.Fields(LogStatsErrorCount))
	}
	if fields.Has(LogStatsCriticalCount) && e.CriticalCount != other.CriticalCount {
		result = result.Union(mgmt.Fields(LogStatsCriticalCount))
	}
	return result
}

func (e *LogStats) ApplyDefaults(present mgmt.FieldSet[LogStats]) {
	if !present.Has(LogStatsTypeField) {
		e.Type = "io.skupper.router.logStats"
	}
}

func (e *LogStats) NonZeroFields() mgmt.FieldSet[LogStats] {
	var result mgmt.FieldSet[LogStats]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(LogStatsName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(LogStatsIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(LogStatsTypeField))
	}
	if e.DebugCount != 0 {
		result = result.Union(mgmt.Fields(LogStatsDebugCount))
	}
	if e.InfoCount != 0 {
		result = result.Union(mgmt.Fields(LogStatsInfoCount))
	}
	if e.NoticeCount != 0 {
		result = result.Union(mgmt.Fields(LogStatsNoticeCount))
	}
	if e.WarningCount != 0 {
		result = result.Union(mgmt.Fields(LogStatsWarningCount))
	}
	if e.ErrorCount != 0 {
		result = result.Union(mgmt.Fields(LogStatsErrorCount))
	}
	if e.CriticalCount != 0 {
		result = result.Union(mgmt.Fields(LogStatsCriticalCount))
	}
	return result
}
