// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type TcpListener struct {
	Name                 string
	Identity             string
	Type                 string
	Address              string
	Host                 string
	Backlog              int64
	Port                 string
	MultiAddressStrategy MultiAddressStrategy
	SiteId               string
	ConnectionsOpened    uint64
	ConnectionsClosed    uint64
	BytesIn              uint64
	BytesOut             uint64
	SslProfile           string
	AuthenticatePeer     bool
	OperStatus           TcpOperStatus
	ConnectionMsg        string
	Observer             Observer
}

const (
	TcpListenerName mgmt.Field[TcpListener] = iota
	TcpListenerIdentity
	TcpListenerTypeField
	TcpListenerAddress
	TcpListenerHost
	TcpListenerBacklog
	TcpListenerPort
	TcpListenerMultiAddressStrategy
	TcpListenerSiteId
	TcpListenerConnectionsOpened
	TcpListenerConnectionsClosed
	TcpListenerBytesIn
	TcpListenerBytesOut
	TcpListenerSslProfile
	TcpListenerAuthenticatePeer
	TcpListenerOperStatus
	TcpListenerConnectionMsg
	TcpListenerObserver
)

var TcpListenerType = mgmt.NewType("io.skupper.router.tcpListener", "tcpListener", false, []string{"QUERY", "READ", "CREATE", "UPDATE", "DELETE"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: true, Update: false, Default: "io.skupper.router.tcpListener", HasDefault: true},
	{Name: "address", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "host", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: "", HasDefault: true},
	{Name: "backlog", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false, Default: int64(0), HasDefault: true},
	{Name: "port", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "multiAddressStrategy", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: MultiAddressStrategy("none"), HasDefault: true, Enum: multiAddressStrategyValues},
	{Name: "siteId", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "connectionsOpened", Kind: mgmt.Uint64Attribute, Required: false, Create: false, Update: false},
	{Name: "connectionsClosed", Kind: mgmt.Uint64Attribute, Required: false, Create: false, Update: false},
	{Name: "bytesIn", Kind: mgmt.Uint64Attribute, Required: false, Create: false, Update: false},
	{Name: "bytesOut", Kind: mgmt.Uint64Attribute, Required: false, Create: false, Update: false},
	{Name: "sslProfile", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "authenticatePeer", Kind: mgmt.BoolAttribute, Required: false, Create: true, Update: false, Default: false, HasDefault: true},
	{Name: "operStatus", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false, Enum: tcpOperStatusValues},
	{Name: "connectionMsg", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "observer", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: true, Default: Observer("auto"), HasDefault: true, Enum: observerValues},
})

var TcpListenerAllFields = mgmt.Fields(TcpListenerName, TcpListenerIdentity, TcpListenerTypeField, TcpListenerAddress, TcpListenerHost, TcpListenerBacklog, TcpListenerPort, TcpListenerMultiAddressStrategy, TcpListenerSiteId, TcpListenerConnectionsOpened, TcpListenerConnectionsClosed, TcpListenerBytesIn, TcpListenerBytesOut, TcpListenerSslProfile, TcpListenerAuthenticatePeer, TcpListenerOperStatus, TcpListenerConnectionMsg, TcpListenerObserver)

var TcpListenerCreateFields = mgmt.Fields(TcpListenerName, TcpListenerTypeField, TcpListenerAddress, TcpListenerHost, TcpListenerBacklog, TcpListenerPort, TcpListenerMultiAddressStrategy, TcpListenerSiteId, TcpListenerSslProfile, TcpListenerAuthenticatePeer, TcpListenerObserver)

var TcpListenerUpdateFields = mgmt.Fields(TcpListenerObserver)

func (*TcpListener) ManagementType() *mgmt.Type { return TcpListenerType }

func (e *TcpListener) SetManagementField(field mgmt.Field[TcpListener], value any) error {
	switch field {
	case TcpListenerName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case TcpListenerIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case TcpListenerTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case TcpListenerAddress:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "address", value)
		}
		e.Address = decoded
		return nil
	case TcpListenerHost:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "host", value)
		}
		e.Host = decoded
		return nil
	case TcpListenerBacklog:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "backlog", value)
		}
		e.Backlog = decoded
		return nil
	case TcpListenerPort:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "port", value)
		}
		e.Port = decoded
		return nil
	case TcpListenerMultiAddressStrategy:
		decoded, ok := mgmt.AsEnum(value, multiAddressStrategyValues)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "multiAddressStrategy", value)
		}
		e.MultiAddressStrategy = MultiAddressStrategy(decoded)
		return nil
	case TcpListenerSiteId:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "siteId", value)
		}
		e.SiteId = decoded
		return nil
	case TcpListenerConnectionsOpened:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "connectionsOpened", value)
		}
		e.ConnectionsOpened = decoded
		return nil
	case TcpListenerConnectionsClosed:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "connectionsClosed", value)
		}
		e.ConnectionsClosed = decoded
		return nil
	case TcpListenerBytesIn:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "bytesIn", value)
		}
		e.BytesIn = decoded
		return nil
	case TcpListenerBytesOut:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "bytesOut", value)
		}
		e.BytesOut = decoded
		return nil
	case TcpListenerSslProfile:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "sslProfile", value)
		}
		e.SslProfile = decoded
		return nil
	case TcpListenerAuthenticatePeer:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "authenticatePeer", value)
		}
		e.AuthenticatePeer = decoded
		return nil
	case TcpListenerOperStatus:
		decoded, ok := mgmt.AsEnum(value, tcpOperStatusValues)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "operStatus", value)
		}
		e.OperStatus = TcpOperStatus(decoded)
		return nil
	case TcpListenerConnectionMsg:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "connectionMsg", value)
		}
		e.ConnectionMsg = decoded
		return nil
	case TcpListenerObserver:
		decoded, ok := mgmt.AsEnum(value, observerValues)
		if !ok {
			return mgmt.DecodeError(TcpListenerType.Name, "observer", value)
		}
		e.Observer = Observer(decoded)
		return nil
	}
	return mgmt.DecodeError(TcpListenerType.Name, "<unknown>", value)
}

func (e *TcpListener) ManagementValue(field mgmt.Field[TcpListener]) any {
	switch field {
	case TcpListenerName:
		return e.Name
	case TcpListenerIdentity:
		return e.Identity
	case TcpListenerTypeField:
		return e.Type
	case TcpListenerAddress:
		return e.Address
	case TcpListenerHost:
		return e.Host
	case TcpListenerBacklog:
		return e.Backlog
	case TcpListenerPort:
		return e.Port
	case TcpListenerMultiAddressStrategy:
		return string(e.MultiAddressStrategy)
	case TcpListenerSiteId:
		return e.SiteId
	case TcpListenerConnectionsOpened:
		return e.ConnectionsOpened
	case TcpListenerConnectionsClosed:
		return e.ConnectionsClosed
	case TcpListenerBytesIn:
		return e.BytesIn
	case TcpListenerBytesOut:
		return e.BytesOut
	case TcpListenerSslProfile:
		return e.SslProfile
	case TcpListenerAuthenticatePeer:
		return e.AuthenticatePeer
	case TcpListenerOperStatus:
		return string(e.OperStatus)
	case TcpListenerConnectionMsg:
		return e.ConnectionMsg
	case TcpListenerObserver:
		return string(e.Observer)
	}
	return nil
}

func (e *TcpListener) Equal(other *TcpListener, fields mgmt.FieldSet[TcpListener]) bool {
	if fields.Has(TcpListenerName) && e.Name != other.Name {
		return false
	}
	if fields.Has(TcpListenerIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(TcpListenerTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(TcpListenerAddress) && e.Address != other.Address {
		return false
	}
	if fields.Has(TcpListenerHost) && e.Host != other.Host {
		return false
	}
	if fields.Has(TcpListenerBacklog) && e.Backlog != other.Backlog {
		return false
	}
	if fields.Has(TcpListenerPort) && e.Port != other.Port {
		return false
	}
	if fields.Has(TcpListenerMultiAddressStrategy) && e.MultiAddressStrategy != other.MultiAddressStrategy {
		return false
	}
	if fields.Has(TcpListenerSiteId) && e.SiteId != other.SiteId {
		return false
	}
	if fields.Has(TcpListenerConnectionsOpened) && e.ConnectionsOpened != other.ConnectionsOpened {
		return false
	}
	if fields.Has(TcpListenerConnectionsClosed) && e.ConnectionsClosed != other.ConnectionsClosed {
		return false
	}
	if fields.Has(TcpListenerBytesIn) && e.BytesIn != other.BytesIn {
		return false
	}
	if fields.Has(TcpListenerBytesOut) && e.BytesOut != other.BytesOut {
		return false
	}
	if fields.Has(TcpListenerSslProfile) && e.SslProfile != other.SslProfile {
		return false
	}
	if fields.Has(TcpListenerAuthenticatePeer) && e.AuthenticatePeer != other.AuthenticatePeer {
		return false
	}
	if fields.Has(TcpListenerOperStatus) && e.OperStatus != other.OperStatus {
		return false
	}
	if fields.Has(TcpListenerConnectionMsg) && e.ConnectionMsg != other.ConnectionMsg {
		return false
	}
	if fields.Has(TcpListenerObserver) && e.Observer != other.Observer {
		return false
	}
	return true
}

func (e *TcpListener) Diff(other *TcpListener, fields mgmt.FieldSet[TcpListener]) mgmt.FieldSet[TcpListener] {
	var result mgmt.FieldSet[TcpListener]
	if fields.Has(TcpListenerName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(TcpListenerName))
	}
	if fields.Has(TcpListenerIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(TcpListenerIdentity))
	}
	if fields.Has(TcpListenerTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(TcpListenerTypeField))
	}
	if fields.Has(TcpListenerAddress) && e.Address != other.Address {
		result = result.Union(mgmt.Fields(TcpListenerAddress))
	}
	if fields.Has(TcpListenerHost) && e.Host != other.Host {
		result = result.Union(mgmt.Fields(TcpListenerHost))
	}
	if fields.Has(TcpListenerBacklog) && e.Backlog != other.Backlog {
		result = result.Union(mgmt.Fields(TcpListenerBacklog))
	}
	if fields.Has(TcpListenerPort) && e.Port != other.Port {
		result = result.Union(mgmt.Fields(TcpListenerPort))
	}
	if fields.Has(TcpListenerMultiAddressStrategy) && e.MultiAddressStrategy != other.MultiAddressStrategy {
		result = result.Union(mgmt.Fields(TcpListenerMultiAddressStrategy))
	}
	if fields.Has(TcpListenerSiteId) && e.SiteId != other.SiteId {
		result = result.Union(mgmt.Fields(TcpListenerSiteId))
	}
	if fields.Has(TcpListenerConnectionsOpened) && e.ConnectionsOpened != other.ConnectionsOpened {
		result = result.Union(mgmt.Fields(TcpListenerConnectionsOpened))
	}
	if fields.Has(TcpListenerConnectionsClosed) && e.ConnectionsClosed != other.ConnectionsClosed {
		result = result.Union(mgmt.Fields(TcpListenerConnectionsClosed))
	}
	if fields.Has(TcpListenerBytesIn) && e.BytesIn != other.BytesIn {
		result = result.Union(mgmt.Fields(TcpListenerBytesIn))
	}
	if fields.Has(TcpListenerBytesOut) && e.BytesOut != other.BytesOut {
		result = result.Union(mgmt.Fields(TcpListenerBytesOut))
	}
	if fields.Has(TcpListenerSslProfile) && e.SslProfile != other.SslProfile {
		result = result.Union(mgmt.Fields(TcpListenerSslProfile))
	}
	if fields.Has(TcpListenerAuthenticatePeer) && e.AuthenticatePeer != other.AuthenticatePeer {
		result = result.Union(mgmt.Fields(TcpListenerAuthenticatePeer))
	}
	if fields.Has(TcpListenerOperStatus) && e.OperStatus != other.OperStatus {
		result = result.Union(mgmt.Fields(TcpListenerOperStatus))
	}
	if fields.Has(TcpListenerConnectionMsg) && e.ConnectionMsg != other.ConnectionMsg {
		result = result.Union(mgmt.Fields(TcpListenerConnectionMsg))
	}
	if fields.Has(TcpListenerObserver) && e.Observer != other.Observer {
		result = result.Union(mgmt.Fields(TcpListenerObserver))
	}
	return result
}

func (e *TcpListener) ApplyDefaults(present mgmt.FieldSet[TcpListener]) {
	if !present.Has(TcpListenerTypeField) {
		e.Type = "io.skupper.router.tcpListener"
	}
	if !present.Has(TcpListenerHost) {
		e.Host = ""
	}
	if !present.Has(TcpListenerBacklog) {
		e.Backlog = int64(0)
	}
	if !present.Has(TcpListenerMultiAddressStrategy) {
		e.MultiAddressStrategy = MultiAddressStrategy("none")
	}
	if !present.Has(TcpListenerAuthenticatePeer) {
		e.AuthenticatePeer = false
	}
	if !present.Has(TcpListenerObserver) {
		e.Observer = Observer("auto")
	}
}

func (e *TcpListener) NonZeroFields() mgmt.FieldSet[TcpListener] {
	var result mgmt.FieldSet[TcpListener]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(TcpListenerName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(TcpListenerIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(TcpListenerTypeField))
	}
	if e.Address != "" {
		result = result.Union(mgmt.Fields(TcpListenerAddress))
	}
	if e.Host != "" {
		result = result.Union(mgmt.Fields(TcpListenerHost))
	}
	if e.Backlog != 0 {
		result = result.Union(mgmt.Fields(TcpListenerBacklog))
	}
	if e.Port != "" {
		result = result.Union(mgmt.Fields(TcpListenerPort))
	}
	if e.MultiAddressStrategy != "" {
		result = result.Union(mgmt.Fields(TcpListenerMultiAddressStrategy))
	}
	if e.SiteId != "" {
		result = result.Union(mgmt.Fields(TcpListenerSiteId))
	}
	if e.ConnectionsOpened != 0 {
		result = result.Union(mgmt.Fields(TcpListenerConnectionsOpened))
	}
	if e.ConnectionsClosed != 0 {
		result = result.Union(mgmt.Fields(TcpListenerConnectionsClosed))
	}
	if e.BytesIn != 0 {
		result = result.Union(mgmt.Fields(TcpListenerBytesIn))
	}
	if e.BytesOut != 0 {
		result = result.Union(mgmt.Fields(TcpListenerBytesOut))
	}
	if e.SslProfile != "" {
		result = result.Union(mgmt.Fields(TcpListenerSslProfile))
	}
	if e.AuthenticatePeer {
		result = result.Union(mgmt.Fields(TcpListenerAuthenticatePeer))
	}
	if e.OperStatus != "" {
		result = result.Union(mgmt.Fields(TcpListenerOperStatus))
	}
	if e.ConnectionMsg != "" {
		result = result.Union(mgmt.Fields(TcpListenerConnectionMsg))
	}
	if e.Observer != "" {
		result = result.Union(mgmt.Fields(TcpListenerObserver))
	}
	return result
}
