// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type SslProfile struct {
	Name               string
	Identity           string
	Type               string
	Ciphers            string
	Protocols          string
	CaCertFile         string
	CertFile           string
	PrivateKeyFile     string
	Password           string
	UidFormat          string
	UidNameMappingFile string
	Ordinal            uint64
	OldestValidOrdinal uint64
}

const (
	SslProfileName mgmt.Field[SslProfile] = iota
	SslProfileIdentity
	SslProfileTypeField
	SslProfileCiphers
	SslProfileProtocols
	SslProfileCaCertFile
	SslProfileCertFile
	SslProfilePrivateKeyFile
	SslProfilePassword
	SslProfileUidFormat
	SslProfileUidNameMappingFile
	SslProfileOrdinal
	SslProfileOldestValidOrdinal
)

var SslProfileType = mgmt.NewType("io.skupper.router.sslProfile", "sslProfile", false, []string{"QUERY", "READ", "CREATE", "UPDATE", "DELETE"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: true, Update: false, Default: "io.skupper.router.sslProfile", HasDefault: true},
	{Name: "ciphers", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: true},
	{Name: "protocols", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: true},
	{Name: "caCertFile", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: true},
	{Name: "certFile", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: true},
	{Name: "privateKeyFile", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: true},
	{Name: "password", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: true},
	{Name: "uidFormat", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "uidNameMappingFile", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "ordinal", Kind: mgmt.Uint64Attribute, Required: false, Create: true, Update: true},
	{Name: "oldestValidOrdinal", Kind: mgmt.Uint64Attribute, Required: false, Create: true, Update: true},
})

var SslProfileAllFields = mgmt.Fields(SslProfileName, SslProfileIdentity, SslProfileTypeField, SslProfileCiphers, SslProfileProtocols, SslProfileCaCertFile, SslProfileCertFile, SslProfilePrivateKeyFile, SslProfilePassword, SslProfileUidFormat, SslProfileUidNameMappingFile, SslProfileOrdinal, SslProfileOldestValidOrdinal)

var SslProfileCreateFields = mgmt.Fields(SslProfileName, SslProfileTypeField, SslProfileCiphers, SslProfileProtocols, SslProfileCaCertFile, SslProfileCertFile, SslProfilePrivateKeyFile, SslProfilePassword, SslProfileUidFormat, SslProfileUidNameMappingFile, SslProfileOrdinal, SslProfileOldestValidOrdinal)

var SslProfileUpdateFields = mgmt.Fields(SslProfileCiphers, SslProfileProtocols, SslProfileCaCertFile, SslProfileCertFile, SslProfilePrivateKeyFile, SslProfilePassword, SslProfileOrdinal, SslProfileOldestValidOrdinal)

func (*SslProfile) ManagementType() *mgmt.Type { return SslProfileType }

func (e *SslProfile) SetManagementField(field mgmt.Field[SslProfile], value any) error {
	switch field {
	case SslProfileName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SslProfileType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case SslProfileIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SslProfileType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case SslProfileTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SslProfileType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case SslProfileCiphers:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SslProfileType.Name, "ciphers", value)
		}
		e.Ciphers = decoded
		return nil
	case SslProfileProtocols:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SslProfileType.Name, "protocols", value)
		}
		e.Protocols = decoded
		return nil
	case SslProfileCaCertFile:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SslProfileType.Name, "caCertFile", value)
		}
		e.CaCertFile = decoded
		return nil
	case SslProfileCertFile:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SslProfileType.Name, "certFile", value)
		}
		e.CertFile = decoded
		return nil
	case SslProfilePrivateKeyFile:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SslProfileType.Name, "privateKeyFile", value)
		}
		e.PrivateKeyFile = decoded
		return nil
	case SslProfilePassword:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SslProfileType.Name, "password", value)
		}
		e.Password = decoded
		return nil
	case SslProfileUidFormat:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SslProfileType.Name, "uidFormat", value)
		}
		e.UidFormat = decoded
		return nil
	case SslProfileUidNameMappingFile:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(SslProfileType.Name, "uidNameMappingFile", value)
		}
		e.UidNameMappingFile = decoded
		return nil
	case SslProfileOrdinal:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(SslProfileType.Name, "ordinal", value)
		}
		e.Ordinal = decoded
		return nil
	case SslProfileOldestValidOrdinal:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(SslProfileType.Name, "oldestValidOrdinal", value)
		}
		e.OldestValidOrdinal = decoded
		return nil
	}
	return mgmt.DecodeError(SslProfileType.Name, "<unknown>", value)
}

func (e *SslProfile) ManagementValue(field mgmt.Field[SslProfile]) any {
	switch field {
	case SslProfileName:
		return e.Name
	case SslProfileIdentity:
		return e.Identity
	case SslProfileTypeField:
		return e.Type
	case SslProfileCiphers:
		return e.Ciphers
	case SslProfileProtocols:
		return e.Protocols
	case SslProfileCaCertFile:
		return e.CaCertFile
	case SslProfileCertFile:
		return e.CertFile
	case SslProfilePrivateKeyFile:
		return e.PrivateKeyFile
	case SslProfilePassword:
		return e.Password
	case SslProfileUidFormat:
		return e.UidFormat
	case SslProfileUidNameMappingFile:
		return e.UidNameMappingFile
	case SslProfileOrdinal:
		return e.Ordinal
	case SslProfileOldestValidOrdinal:
		return e.OldestValidOrdinal
	}
	return nil
}

func (e *SslProfile) Equal(other *SslProfile, fields mgmt.FieldSet[SslProfile]) bool {
	if fields.Has(SslProfileName) && e.Name != other.Name {
		return false
	}
	if fields.Has(SslProfileIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(SslProfileTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(SslProfileCiphers) && e.Ciphers != other.Ciphers {
		return false
	}
	if fields.Has(SslProfileProtocols) && e.Protocols != other.Protocols {
		return false
	}
	if fields.Has(SslProfileCaCertFile) && e.CaCertFile != other.CaCertFile {
		return false
	}
	if fields.Has(SslProfileCertFile) && e.CertFile != other.CertFile {
		return false
	}
	if fields.Has(SslProfilePrivateKeyFile) && e.PrivateKeyFile != other.PrivateKeyFile {
		return false
	}
	if fields.Has(SslProfilePassword) && e.Password != other.Password {
		return false
	}
	if fields.Has(SslProfileUidFormat) && e.UidFormat != other.UidFormat {
		return false
	}
	if fields.Has(SslProfileUidNameMappingFile) && e.UidNameMappingFile != other.UidNameMappingFile {
		return false
	}
	if fields.Has(SslProfileOrdinal) && e.Ordinal != other.Ordinal {
		return false
	}
	if fields.Has(SslProfileOldestValidOrdinal) && e.OldestValidOrdinal != other.OldestValidOrdinal {
		return false
	}
	return true
}

func (e *SslProfile) Diff(other *SslProfile, fields mgmt.FieldSet[SslProfile]) mgmt.FieldSet[SslProfile] {
	var result mgmt.FieldSet[SslProfile]
	if fields.Has(SslProfileName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(SslProfileName))
	}
	if fields.Has(SslProfileIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(SslProfileIdentity))
	}
	if fields.Has(SslProfileTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(SslProfileTypeField))
	}
	if fields.Has(SslProfileCiphers) && e.Ciphers != other.Ciphers {
		result = result.Union(mgmt.Fields(SslProfileCiphers))
	}
	if fields.Has(SslProfileProtocols) && e.Protocols != other.Protocols {
		result = result.Union(mgmt.Fields(SslProfileProtocols))
	}
	if fields.Has(SslProfileCaCertFile) && e.CaCertFile != other.CaCertFile {
		result = result.Union(mgmt.Fields(SslProfileCaCertFile))
	}
	if fields.Has(SslProfileCertFile) && e.CertFile != other.CertFile {
		result = result.Union(mgmt.Fields(SslProfileCertFile))
	}
	if fields.Has(SslProfilePrivateKeyFile) && e.PrivateKeyFile != other.PrivateKeyFile {
		result = result.Union(mgmt.Fields(SslProfilePrivateKeyFile))
	}
	if fields.Has(SslProfilePassword) && e.Password != other.Password {
		result = result.Union(mgmt.Fields(SslProfilePassword))
	}
	if fields.Has(SslProfileUidFormat) && e.UidFormat != other.UidFormat {
		result = result.Union(mgmt.Fields(SslProfileUidFormat))
	}
	if fields.Has(SslProfileUidNameMappingFile) && e.UidNameMappingFile != other.UidNameMappingFile {
		result = result.Union(mgmt.Fields(SslProfileUidNameMappingFile))
	}
	if fields.Has(SslProfileOrdinal) && e.Ordinal != other.Ordinal {
		result = result.Union(mgmt.Fields(SslProfileOrdinal))
	}
	if fields.Has(SslProfileOldestValidOrdinal) && e.OldestValidOrdinal != other.OldestValidOrdinal {
		result = result.Union(mgmt.Fields(SslProfileOldestValidOrdinal))
	}
	return result
}

func (e *SslProfile) ApplyDefaults(present mgmt.FieldSet[SslProfile]) {
	if !present.Has(SslProfileTypeField) {
		e.Type = "io.skupper.router.sslProfile"
	}
}

func (e *SslProfile) NonZeroFields() mgmt.FieldSet[SslProfile] {
	var result mgmt.FieldSet[SslProfile]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(SslProfileName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(SslProfileIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(SslProfileTypeField))
	}
	if e.Ciphers != "" {
		result = result.Union(mgmt.Fields(SslProfileCiphers))
	}
	if e.Protocols != "" {
		result = result.Union(mgmt.Fields(SslProfileProtocols))
	}
	if e.CaCertFile != "" {
		result = result.Union(mgmt.Fields(SslProfileCaCertFile))
	}
	if e.CertFile != "" {
		result = result.Union(mgmt.Fields(SslProfileCertFile))
	}
	if e.PrivateKeyFile != "" {
		result = result.Union(mgmt.Fields(SslProfilePrivateKeyFile))
	}
	if e.Password != "" {
		result = result.Union(mgmt.Fields(SslProfilePassword))
	}
	if e.UidFormat != "" {
		result = result.Union(mgmt.Fields(SslProfileUidFormat))
	}
	if e.UidNameMappingFile != "" {
		result = result.Union(mgmt.Fields(SslProfileUidNameMappingFile))
	}
	if e.Ordinal != 0 {
		result = result.Union(mgmt.Fields(SslProfileOrdinal))
	}
	if e.OldestValidOrdinal != 0 {
		result = result.Union(mgmt.Fields(SslProfileOldestValidOrdinal))
	}
	return result
}
