// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type Connector struct {
	Name                     string
	Identity                 string
	Type                     string
	Host                     string
	Port                     string
	SocketAddressFamily      SocketAddressFamily
	Role                     Role
	Cost                     int64
	SslProfile               string
	ProxyProfile             string
	SaslMechanisms           string
	AllowRedirect            bool
	MaxFrameSize             int64
	MaxSessions              int64
	MaxSessionFrames         int64
	IdleTimeoutSeconds       int64
	StripAnnotations         StripAnnotations
	LinkCapacity             int64
	VerifyHostname           bool
	SaslUsername             string
	SaslPassword             string
	MessageLoggingComponents string
	FailoverUrls             string
	ConnectionStatus         string
	ConnectionMsg            string
	PolicyVhost              string
	OpenProperties           map[string]any
}

const (
	ConnectorName mgmt.Field[Connector] = iota
	ConnectorIdentity
	ConnectorTypeField
	ConnectorHost
	ConnectorPort
	ConnectorSocketAddressFamily
	ConnectorRole
	ConnectorCost
	ConnectorSslProfile
	ConnectorProxyProfile
	ConnectorSaslMechanisms
	ConnectorAllowRedirect
	ConnectorMaxFrameSize
	ConnectorMaxSessions
	ConnectorMaxSessionFrames
	ConnectorIdleTimeoutSeconds
	ConnectorStripAnnotations
	ConnectorLinkCapacity
	ConnectorVerifyHostname
	ConnectorSaslUsername
	ConnectorSaslPassword
	ConnectorMessageLoggingComponents
	ConnectorFailoverUrls
	ConnectorConnectionStatus
	ConnectorConnectionMsg
	ConnectorPolicyVhost
	ConnectorOpenProperties
)

var ConnectorType = mgmt.NewType("io.skupper.router.connector", "connector", false, []string{"QUERY", "READ", "CREATE", "DELETE"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: true, Update: false, Default: "io.skupper.router.connector", HasDefault: true},
	{Name: "host", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: "127.0.0.1", HasDefault: true},
	{Name: "port", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: "amqp", HasDefault: true},
	{Name: "socketAddressFamily", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Enum: socketAddressFamilyValues},
	{Name: "role", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: Role("normal"), HasDefault: true, Enum: roleValues},
	{Name: "cost", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false, Default: int64(1), HasDefault: true},
	{Name: "sslProfile", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "proxyProfile", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "saslMechanisms", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "allowRedirect", Kind: mgmt.BoolAttribute, Required: false, Create: true, Update: false, Default: true, HasDefault: true},
	{Name: "maxFrameSize", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false, Default: int64(16384), HasDefault: true},
	{Name: "maxSessions", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false, Default: int64(32768), HasDefault: true},
	{Name: "maxSessionFrames", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false},
	{Name: "idleTimeoutSeconds", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false, Default: int64(16), HasDefault: true},
	{Name: "stripAnnotations", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: StripAnnotations("both"), HasDefault: true, Enum: stripAnnotationsValues},
	{Name: "linkCapacity", Kind: mgmt.Int64Attribute, Required: false, Create: true, Update: false},
	{Name: "verifyHostname", Kind: mgmt.BoolAttribute, Required: false, Create: true, Update: false, Default: true, HasDefault: true},
	{Name: "saslUsername", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "saslPassword", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "messageLoggingComponents", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false, Default: "none", HasDefault: true},
	{Name: "failoverUrls", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "connectionStatus", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "connectionMsg", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "policyVhost", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "openProperties", Kind: mgmt.MapAttribute, Required: false, Create: true, Update: false},
})

var ConnectorAllFields = mgmt.Fields(ConnectorName, ConnectorIdentity, ConnectorTypeField, ConnectorHost, ConnectorPort, ConnectorSocketAddressFamily, ConnectorRole, ConnectorCost, ConnectorSslProfile, ConnectorProxyProfile, ConnectorSaslMechanisms, ConnectorAllowRedirect, ConnectorMaxFrameSize, ConnectorMaxSessions, ConnectorMaxSessionFrames, ConnectorIdleTimeoutSeconds, ConnectorStripAnnotations, ConnectorLinkCapacity, ConnectorVerifyHostname, ConnectorSaslUsername, ConnectorSaslPassword, ConnectorMessageLoggingComponents, ConnectorFailoverUrls, ConnectorConnectionStatus, ConnectorConnectionMsg, ConnectorPolicyVhost, ConnectorOpenProperties)

var ConnectorCreateFields = mgmt.Fields(ConnectorName, ConnectorTypeField, ConnectorHost, ConnectorPort, ConnectorSocketAddressFamily, ConnectorRole, ConnectorCost, ConnectorSslProfile, ConnectorProxyProfile, ConnectorSaslMechanisms, ConnectorAllowRedirect, ConnectorMaxFrameSize, ConnectorMaxSessions, ConnectorMaxSessionFrames, ConnectorIdleTimeoutSeconds, ConnectorStripAnnotations, ConnectorLinkCapacity, ConnectorVerifyHostname, ConnectorSaslUsername, ConnectorSaslPassword, ConnectorMessageLoggingComponents, ConnectorPolicyVhost, ConnectorOpenProperties)

var ConnectorUpdateFields mgmt.FieldSet[Connector]

func (*Connector) ManagementType() *mgmt.Type { return ConnectorType }

func (e *Connector) SetManagementField(field mgmt.Field[Connector], value any) error {
	switch field {
	case ConnectorName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case ConnectorIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case ConnectorTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case ConnectorHost:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "host", value)
		}
		e.Host = decoded
		return nil
	case ConnectorPort:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "port", value)
		}
		e.Port = decoded
		return nil
	case ConnectorSocketAddressFamily:
		decoded, ok := mgmt.AsEnum(value, socketAddressFamilyValues)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "socketAddressFamily", value)
		}
		e.SocketAddressFamily = SocketAddressFamily(decoded)
		return nil
	case ConnectorRole:
		decoded, ok := mgmt.AsEnum(value, roleValues)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "role", value)
		}
		e.Role = Role(decoded)
		return nil
	case ConnectorCost:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "cost", value)
		}
		e.Cost = decoded
		return nil
	case ConnectorSslProfile:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "sslProfile", value)
		}
		e.SslProfile = decoded
		return nil
	case ConnectorProxyProfile:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "proxyProfile", value)
		}
		e.ProxyProfile = decoded
		return nil
	case ConnectorSaslMechanisms:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "saslMechanisms", value)
		}
		e.SaslMechanisms = decoded
		return nil
	case ConnectorAllowRedirect:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "allowRedirect", value)
		}
		e.AllowRedirect = decoded
		return nil
	case ConnectorMaxFrameSize:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "maxFrameSize", value)
		}
		e.MaxFrameSize = decoded
		return nil
	case ConnectorMaxSessions:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "maxSessions", value)
		}
		e.MaxSessions = decoded
		return nil
	case ConnectorMaxSessionFrames:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "maxSessionFrames", value)
		}
		e.MaxSessionFrames = decoded
		return nil
	case ConnectorIdleTimeoutSeconds:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "idleTimeoutSeconds", value)
		}
		e.IdleTimeoutSeconds = decoded
		return nil
	case ConnectorStripAnnotations:
		decoded, ok := mgmt.AsEnum(value, stripAnnotationsValues)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "stripAnnotations", value)
		}
		e.StripAnnotations = StripAnnotations(decoded)
		return nil
	case ConnectorLinkCapacity:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "linkCapacity", value)
		}
		e.LinkCapacity = decoded
		return nil
	case ConnectorVerifyHostname:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "verifyHostname", value)
		}
		e.VerifyHostname = decoded
		return nil
	case ConnectorSaslUsername:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "saslUsername", value)
		}
		e.SaslUsername = decoded
		return nil
	case ConnectorSaslPassword:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "saslPassword", value)
		}
		e.SaslPassword = decoded
		return nil
	case ConnectorMessageLoggingComponents:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "messageLoggingComponents", value)
		}
		e.MessageLoggingComponents = decoded
		return nil
	case ConnectorFailoverUrls:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "failoverUrls", value)
		}
		e.FailoverUrls = decoded
		return nil
	case ConnectorConnectionStatus:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "connectionStatus", value)
		}
		e.ConnectionStatus = decoded
		return nil
	case ConnectorConnectionMsg:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "connectionMsg", value)
		}
		e.ConnectionMsg = decoded
		return nil
	case ConnectorPolicyVhost:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "policyVhost", value)
		}
		e.PolicyVhost = decoded
		return nil
	case ConnectorOpenProperties:
		decoded, ok := mgmt.AsMap(value)
		if !ok {
			return mgmt.DecodeError(ConnectorType.Name, "openProperties", value)
		}
		e.OpenProperties = decoded
		return nil
	}
	return mgmt.DecodeError(ConnectorType.Name, "<unknown>", value)
}

func (e *Connector) ManagementValue(field mgmt.Field[Connector]) any {
	switch field {
	case ConnectorName:
		return e.Name
	case ConnectorIdentity:
		return e.Identity
	case ConnectorTypeField:
		return e.Type
	case ConnectorHost:
		return e.Host
	case ConnectorPort:
		return e.Port
	case ConnectorSocketAddressFamily:
		return string(e.SocketAddressFamily)
	case ConnectorRole:
		return string(e.Role)
	case ConnectorCost:
		return e.Cost
	case ConnectorSslProfile:
		return e.SslProfile
	case ConnectorProxyProfile:
		return e.ProxyProfile
	case ConnectorSaslMechanisms:
		return e.SaslMechanisms
	case ConnectorAllowRedirect:
		return e.AllowRedirect
	case ConnectorMaxFrameSize:
		return e.MaxFrameSize
	case ConnectorMaxSessions:
		return e.MaxSessions
	case ConnectorMaxSessionFrames:
		return e.MaxSessionFrames
	case ConnectorIdleTimeoutSeconds:
		return e.IdleTimeoutSeconds
	case ConnectorStripAnnotations:
		return string(e.StripAnnotations)
	case ConnectorLinkCapacity:
		return e.LinkCapacity
	case ConnectorVerifyHostname:
		return e.VerifyHostname
	case ConnectorSaslUsername:
		return e.SaslUsername
	case ConnectorSaslPassword:
		return e.SaslPassword
	case ConnectorMessageLoggingComponents:
		return e.MessageLoggingComponents
	case ConnectorFailoverUrls:
		return e.FailoverUrls
	case ConnectorConnectionStatus:
		return e.ConnectionStatus
	case ConnectorConnectionMsg:
		return e.ConnectionMsg
	case ConnectorPolicyVhost:
		return e.PolicyVhost
	case ConnectorOpenProperties:
		return e.OpenProperties
	}
	return nil
}

func (e *Connector) Equal(other *Connector, fields mgmt.FieldSet[Connector]) bool {
	if fields.Has(ConnectorName) && e.Name != other.Name {
		return false
	}
	if fields.Has(ConnectorIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(ConnectorTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(ConnectorHost) && e.Host != other.Host {
		return false
	}
	if fields.Has(ConnectorPort) && e.Port != other.Port {
		return false
	}
	if fields.Has(ConnectorSocketAddressFamily) && e.SocketAddressFamily != other.SocketAddressFamily {
		return false
	}
	if fields.Has(ConnectorRole) && e.Role != other.Role {
		return false
	}
	if fields.Has(ConnectorCost) && e.Cost != other.Cost {
		return false
	}
	if fields.Has(ConnectorSslProfile) && e.SslProfile != other.SslProfile {
		return false
	}
	if fields.Has(ConnectorProxyProfile) && e.ProxyProfile != other.ProxyProfile {
		return false
	}
	if fields.Has(ConnectorSaslMechanisms) && e.SaslMechanisms != other.SaslMechanisms {
		return false
	}
	if fields.Has(ConnectorAllowRedirect) && e.AllowRedirect != other.AllowRedirect {
		return false
	}
	if fields.Has(ConnectorMaxFrameSize) && e.MaxFrameSize != other.MaxFrameSize {
		return false
	}
	if fields.Has(ConnectorMaxSessions) && e.MaxSessions != other.MaxSessions {
		return false
	}
	if fields.Has(ConnectorMaxSessionFrames) && e.MaxSessionFrames != other.MaxSessionFrames {
		return false
	}
	if fields.Has(ConnectorIdleTimeoutSeconds) && e.IdleTimeoutSeconds != other.IdleTimeoutSeconds {
		return false
	}
	if fields.Has(ConnectorStripAnnotations) && e.StripAnnotations != other.StripAnnotations {
		return false
	}
	if fields.Has(ConnectorLinkCapacity) && e.LinkCapacity != other.LinkCapacity {
		return false
	}
	if fields.Has(ConnectorVerifyHostname) && e.VerifyHostname != other.VerifyHostname {
		return false
	}
	if fields.Has(ConnectorSaslUsername) && e.SaslUsername != other.SaslUsername {
		return false
	}
	if fields.Has(ConnectorSaslPassword) && e.SaslPassword != other.SaslPassword {
		return false
	}
	if fields.Has(ConnectorMessageLoggingComponents) && e.MessageLoggingComponents != other.MessageLoggingComponents {
		return false
	}
	if fields.Has(ConnectorFailoverUrls) && e.FailoverUrls != other.FailoverUrls {
		return false
	}
	if fields.Has(ConnectorConnectionStatus) && e.ConnectionStatus != other.ConnectionStatus {
		return false
	}
	if fields.Has(ConnectorConnectionMsg) && e.ConnectionMsg != other.ConnectionMsg {
		return false
	}
	if fields.Has(ConnectorPolicyVhost) && e.PolicyVhost != other.PolicyVhost {
		return false
	}
	if fields.Has(ConnectorOpenProperties) && !mgmt.EqualValues(e.OpenProperties, other.OpenProperties) {
		return false
	}
	return true
}

func (e *Connector) Diff(other *Connector, fields mgmt.FieldSet[Connector]) mgmt.FieldSet[Connector] {
	var result mgmt.FieldSet[Connector]
	if fields.Has(ConnectorName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(ConnectorName))
	}
	if fields.Has(ConnectorIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(ConnectorIdentity))
	}
	if fields.Has(ConnectorTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(ConnectorTypeField))
	}
	if fields.Has(ConnectorHost) && e.Host != other.Host {
		result = result.Union(mgmt.Fields(ConnectorHost))
	}
	if fields.Has(ConnectorPort) && e.Port != other.Port {
		result = result.Union(mgmt.Fields(ConnectorPort))
	}
	if fields.Has(ConnectorSocketAddressFamily) && e.SocketAddressFamily != other.SocketAddressFamily {
		result = result.Union(mgmt.Fields(ConnectorSocketAddressFamily))
	}
	if fields.Has(ConnectorRole) && e.Role != other.Role {
		result = result.Union(mgmt.Fields(ConnectorRole))
	}
	if fields.Has(ConnectorCost) && e.Cost != other.Cost {
		result = result.Union(mgmt.Fields(ConnectorCost))
	}
	if fields.Has(ConnectorSslProfile) && e.SslProfile != other.SslProfile {
		result = result.Union(mgmt.Fields(ConnectorSslProfile))
	}
	if fields.Has(ConnectorProxyProfile) && e.ProxyProfile != other.ProxyProfile {
		result = result.Union(mgmt.Fields(ConnectorProxyProfile))
	}
	if fields.Has(ConnectorSaslMechanisms) && e.SaslMechanisms != other.SaslMechanisms {
		result = result.Union(mgmt.Fields(ConnectorSaslMechanisms))
	}
	if fields.Has(ConnectorAllowRedirect) && e.AllowRedirect != other.AllowRedirect {
		result = result.Union(mgmt.Fields(ConnectorAllowRedirect))
	}
	if fields.Has(ConnectorMaxFrameSize) && e.MaxFrameSize != other.MaxFrameSize {
		result = result.Union(mgmt.Fields(ConnectorMaxFrameSize))
	}
	if fields.Has(ConnectorMaxSessions) && e.MaxSessions != other.MaxSessions {
		result = result.Union(mgmt.Fields(ConnectorMaxSessions))
	}
	if fields.Has(ConnectorMaxSessionFrames) && e.MaxSessionFrames != other.MaxSessionFrames {
		result = result.Union(mgmt.Fields(ConnectorMaxSessionFrames))
	}
	if fields.Has(ConnectorIdleTimeoutSeconds) && e.IdleTimeoutSeconds != other.IdleTimeoutSeconds {
		result = result.Union(mgmt.Fields(ConnectorIdleTimeoutSeconds))
	}
	if fields.Has(ConnectorStripAnnotations) && e.StripAnnotations != other.StripAnnotations {
		result = result.Union(mgmt.Fields(ConnectorStripAnnotations))
	}
	if fields.Has(ConnectorLinkCapacity) && e.LinkCapacity != other.LinkCapacity {
		result = result.Union(mgmt.Fields(ConnectorLinkCapacity))
	}
	if fields.Has(ConnectorVerifyHostname) && e.VerifyHostname != other.VerifyHostname {
		result = result.Union(mgmt.Fields(ConnectorVerifyHostname))
	}
	if fields.Has(ConnectorSaslUsername) && e.SaslUsername != other.SaslUsername {
		result = result.Union(mgmt.Fields(ConnectorSaslUsername))
	}
	if fields.Has(ConnectorSaslPassword) && e.SaslPassword != other.SaslPassword {
		result = result.Union(mgmt.Fields(ConnectorSaslPassword))
	}
	if fields.Has(ConnectorMessageLoggingComponents) && e.MessageLoggingComponents != other.MessageLoggingComponents {
		result = result.Union(mgmt.Fields(ConnectorMessageLoggingComponents))
	}
	if fields.Has(ConnectorFailoverUrls) && e.FailoverUrls != other.FailoverUrls {
		result = result.Union(mgmt.Fields(ConnectorFailoverUrls))
	}
	if fields.Has(ConnectorConnectionStatus) && e.ConnectionStatus != other.ConnectionStatus {
		result = result.Union(mgmt.Fields(ConnectorConnectionStatus))
	}
	if fields.Has(ConnectorConnectionMsg) && e.ConnectionMsg != other.ConnectionMsg {
		result = result.Union(mgmt.Fields(ConnectorConnectionMsg))
	}
	if fields.Has(ConnectorPolicyVhost) && e.PolicyVhost != other.PolicyVhost {
		result = result.Union(mgmt.Fields(ConnectorPolicyVhost))
	}
	if fields.Has(ConnectorOpenProperties) && !mgmt.EqualValues(e.OpenProperties, other.OpenProperties) {
		result = result.Union(mgmt.Fields(ConnectorOpenProperties))
	}
	return result
}

func (e *Connector) ApplyDefaults(present mgmt.FieldSet[Connector]) {
	if !present.Has(ConnectorTypeField) {
		e.Type = "io.skupper.router.connector"
	}
	if !present.Has(ConnectorHost) {
		e.Host = "127.0.0.1"
	}
	if !present.Has(ConnectorPort) {
		e.Port = "amqp"
	}
	if !present.Has(ConnectorRole) {
		e.Role = Role("normal")
	}
	if !present.Has(ConnectorCost) {
		e.Cost = int64(1)
	}
	if !present.Has(ConnectorAllowRedirect) {
		e.AllowRedirect = true
	}
	if !present.Has(ConnectorMaxFrameSize) {
		e.MaxFrameSize = int64(16384)
	}
	if !present.Has(ConnectorMaxSessions) {
		e.MaxSessions = int64(32768)
	}
	if !present.Has(ConnectorIdleTimeoutSeconds) {
		e.IdleTimeoutSeconds = int64(16)
	}
	if !present.Has(ConnectorStripAnnotations) {
		e.StripAnnotations = StripAnnotations("both")
	}
	if !present.Has(ConnectorVerifyHostname) {
		e.VerifyHostname = true
	}
	if !present.Has(ConnectorMessageLoggingComponents) {
		e.MessageLoggingComponents = "none"
	}
}

func (e *Connector) NonZeroFields() mgmt.FieldSet[Connector] {
	var result mgmt.FieldSet[Connector]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(ConnectorName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(ConnectorIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(ConnectorTypeField))
	}
	if e.Host != "" {
		result = result.Union(mgmt.Fields(ConnectorHost))
	}
	if e.Port != "" {
		result = result.Union(mgmt.Fields(ConnectorPort))
	}
	if e.SocketAddressFamily != "" {
		result = result.Union(mgmt.Fields(ConnectorSocketAddressFamily))
	}
	if e.Role != "" {
		result = result.Union(mgmt.Fields(ConnectorRole))
	}
	if e.Cost != 0 {
		result = result.Union(mgmt.Fields(ConnectorCost))
	}
	if e.SslProfile != "" {
		result = result.Union(mgmt.Fields(ConnectorSslProfile))
	}
	if e.ProxyProfile != "" {
		result = result.Union(mgmt.Fields(ConnectorProxyProfile))
	}
	if e.SaslMechanisms != "" {
		result = result.Union(mgmt.Fields(ConnectorSaslMechanisms))
	}
	if e.AllowRedirect {
		result = result.Union(mgmt.Fields(ConnectorAllowRedirect))
	}
	if e.MaxFrameSize != 0 {
		result = result.Union(mgmt.Fields(ConnectorMaxFrameSize))
	}
	if e.MaxSessions != 0 {
		result = result.Union(mgmt.Fields(ConnectorMaxSessions))
	}
	if e.MaxSessionFrames != 0 {
		result = result.Union(mgmt.Fields(ConnectorMaxSessionFrames))
	}
	if e.IdleTimeoutSeconds != 0 {
		result = result.Union(mgmt.Fields(ConnectorIdleTimeoutSeconds))
	}
	if e.StripAnnotations != "" {
		result = result.Union(mgmt.Fields(ConnectorStripAnnotations))
	}
	if e.LinkCapacity != 0 {
		result = result.Union(mgmt.Fields(ConnectorLinkCapacity))
	}
	if e.VerifyHostname {
		result = result.Union(mgmt.Fields(ConnectorVerifyHostname))
	}
	if e.SaslUsername != "" {
		result = result.Union(mgmt.Fields(ConnectorSaslUsername))
	}
	if e.SaslPassword != "" {
		result = result.Union(mgmt.Fields(ConnectorSaslPassword))
	}
	if e.MessageLoggingComponents != "" {
		result = result.Union(mgmt.Fields(ConnectorMessageLoggingComponents))
	}
	if e.FailoverUrls != "" {
		result = result.Union(mgmt.Fields(ConnectorFailoverUrls))
	}
	if e.ConnectionStatus != "" {
		result = result.Union(mgmt.Fields(ConnectorConnectionStatus))
	}
	if e.ConnectionMsg != "" {
		result = result.Union(mgmt.Fields(ConnectorConnectionMsg))
	}
	if e.PolicyVhost != "" {
		result = result.Union(mgmt.Fields(ConnectorPolicyVhost))
	}
	if len(e.OpenProperties) != 0 {
		result = result.Union(mgmt.Fields(ConnectorOpenProperties))
	}
	return result
}
