// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type ListenerAddress struct {
	Name              string
	Identity          string
	Type              string
	Address           string
	Value             int64
	Listener          string
	ConnectionsOpened uint64
}

const (
	ListenerAddressName mgmt.Field[ListenerAddress] = iota
	ListenerAddressIdentity
	ListenerAddressTypeField
	ListenerAddressAddress
	ListenerAddressValue
	ListenerAddressListener
	ListenerAddressConnectionsOpened
)

var ListenerAddressType = mgmt.NewType("io.skupper.router.listenerAddress", "listenerAddress", false, []string{"QUERY", "READ", "CREATE", "DELETE"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: true, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: true, Update: false, Default: "io.skupper.router.listenerAddress", HasDefault: true},
	{Name: "address", Kind: mgmt.StringAttribute, Required: true, Create: true, Update: false},
	{Name: "value", Kind: mgmt.Int64Attribute, Required: true, Create: true, Update: false},
	{Name: "listener", Kind: mgmt.StringAttribute, Required: true, Create: true, Update: false},
	{Name: "connectionsOpened", Kind: mgmt.Uint64Attribute, Required: false, Create: false, Update: false},
})

var ListenerAddressAllFields = mgmt.Fields(ListenerAddressName, ListenerAddressIdentity, ListenerAddressTypeField, ListenerAddressAddress, ListenerAddressValue, ListenerAddressListener, ListenerAddressConnectionsOpened)

var ListenerAddressCreateFields = mgmt.Fields(ListenerAddressName, ListenerAddressTypeField, ListenerAddressAddress, ListenerAddressValue, ListenerAddressListener)

var ListenerAddressUpdateFields mgmt.FieldSet[ListenerAddress]

func (*ListenerAddress) ManagementType() *mgmt.Type { return ListenerAddressType }

func (e *ListenerAddress) SetManagementField(field mgmt.Field[ListenerAddress], value any) error {
	switch field {
	case ListenerAddressName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerAddressType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case ListenerAddressIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerAddressType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case ListenerAddressTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerAddressType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case ListenerAddressAddress:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerAddressType.Name, "address", value)
		}
		e.Address = decoded
		return nil
	case ListenerAddressValue:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ListenerAddressType.Name, "value", value)
		}
		e.Value = decoded
		return nil
	case ListenerAddressListener:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ListenerAddressType.Name, "listener", value)
		}
		e.Listener = decoded
		return nil
	case ListenerAddressConnectionsOpened:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(ListenerAddressType.Name, "connectionsOpened", value)
		}
		e.ConnectionsOpened = decoded
		return nil
	}
	return mgmt.DecodeError(ListenerAddressType.Name, "<unknown>", value)
}

func (e *ListenerAddress) ManagementValue(field mgmt.Field[ListenerAddress]) any {
	switch field {
	case ListenerAddressName:
		return e.Name
	case ListenerAddressIdentity:
		return e.Identity
	case ListenerAddressTypeField:
		return e.Type
	case ListenerAddressAddress:
		return e.Address
	case ListenerAddressValue:
		return e.Value
	case ListenerAddressListener:
		return e.Listener
	case ListenerAddressConnectionsOpened:
		return e.ConnectionsOpened
	}
	return nil
}

func (e *ListenerAddress) Equal(other *ListenerAddress, fields mgmt.FieldSet[ListenerAddress]) bool {
	if fields.Has(ListenerAddressName) && e.Name != other.Name {
		return false
	}
	if fields.Has(ListenerAddressIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(ListenerAddressTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(ListenerAddressAddress) && e.Address != other.Address {
		return false
	}
	if fields.Has(ListenerAddressValue) && e.Value != other.Value {
		return false
	}
	if fields.Has(ListenerAddressListener) && e.Listener != other.Listener {
		return false
	}
	if fields.Has(ListenerAddressConnectionsOpened) && e.ConnectionsOpened != other.ConnectionsOpened {
		return false
	}
	return true
}

func (e *ListenerAddress) Diff(other *ListenerAddress, fields mgmt.FieldSet[ListenerAddress]) mgmt.FieldSet[ListenerAddress] {
	var result mgmt.FieldSet[ListenerAddress]
	if fields.Has(ListenerAddressName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(ListenerAddressName))
	}
	if fields.Has(ListenerAddressIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(ListenerAddressIdentity))
	}
	if fields.Has(ListenerAddressTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(ListenerAddressTypeField))
	}
	if fields.Has(ListenerAddressAddress) && e.Address != other.Address {
		result = result.Union(mgmt.Fields(ListenerAddressAddress))
	}
	if fields.Has(ListenerAddressValue) && e.Value != other.Value {
		result = result.Union(mgmt.Fields(ListenerAddressValue))
	}
	if fields.Has(ListenerAddressListener) && e.Listener != other.Listener {
		result = result.Union(mgmt.Fields(ListenerAddressListener))
	}
	if fields.Has(ListenerAddressConnectionsOpened) && e.ConnectionsOpened != other.ConnectionsOpened {
		result = result.Union(mgmt.Fields(ListenerAddressConnectionsOpened))
	}
	return result
}

func (e *ListenerAddress) ApplyDefaults(present mgmt.FieldSet[ListenerAddress]) {
	if !present.Has(ListenerAddressTypeField) {
		e.Type = "io.skupper.router.listenerAddress"
	}
}

func (e *ListenerAddress) NonZeroFields() mgmt.FieldSet[ListenerAddress] {
	var result mgmt.FieldSet[ListenerAddress]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(ListenerAddressName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(ListenerAddressIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(ListenerAddressTypeField))
	}
	if e.Address != "" {
		result = result.Union(mgmt.Fields(ListenerAddressAddress))
	}
	if e.Value != 0 {
		result = result.Union(mgmt.Fields(ListenerAddressValue))
	}
	if e.Listener != "" {
		result = result.Union(mgmt.Fields(ListenerAddressListener))
	}
	if e.ConnectionsOpened != 0 {
		result = result.Union(mgmt.Fields(ListenerAddressConnectionsOpened))
	}
	return result
}
