// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type Connection struct {
	Name                string
	Identity            string
	Type                string
	AdminStatus         AdminStatus
	OperStatus          ConnectionOperStatus
	Protocol            string
	Container           string
	Opened              bool
	Host                string
	LocalSocket         string
	Dir                 Direction
	Role                string
	MeshId              string
	IsAuthenticated     bool
	IsEncrypted         bool
	EnableProtocolTrace bool
	Sasl                string
	User                string
	Ssl                 bool
	SslProto            string
	SslCipher           string
	SslSsf              int64
	UptimeSeconds       int64
	Properties          map[string]any
	LastDlvSeconds      int64
	TlsOrdinal          uint64
	GroupCorrelationId  string
	GroupOrdinal        uint64
}

const (
	ConnectionName mgmt.Field[Connection] = iota
	ConnectionIdentity
	ConnectionTypeField
	ConnectionAdminStatus
	ConnectionOperStatusField
	ConnectionProtocol
	ConnectionContainer
	ConnectionOpened
	ConnectionHost
	ConnectionLocalSocket
	ConnectionDir
	ConnectionRole
	ConnectionMeshId
	ConnectionIsAuthenticated
	ConnectionIsEncrypted
	ConnectionEnableProtocolTrace
	ConnectionSasl
	ConnectionUser
	ConnectionSsl
	ConnectionSslProto
	ConnectionSslCipher
	ConnectionSslSsf
	ConnectionUptimeSeconds
	ConnectionProperties
	ConnectionLastDlvSeconds
	ConnectionTlsOrdinal
	ConnectionGroupCorrelationId
	ConnectionGroupOrdinal
)

var ConnectionType = mgmt.NewType("io.skupper.router.connection", "connection", true, []string{"QUERY", "READ", "UPDATE"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: false, Update: false, Default: "io.skupper.router.connection", HasDefault: true},
	{Name: "adminStatus", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: true, Default: AdminStatus("enabled"), HasDefault: true, Enum: adminStatusValues},
	{Name: "operStatus", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false, Enum: connectionOperStatusValues},
	{Name: "protocol", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "container", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "opened", Kind: mgmt.BoolAttribute, Required: false, Create: false, Update: false},
	{Name: "host", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "localSocket", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "dir", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false, Enum: directionValues},
	{Name: "role", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "meshId", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "isAuthenticated", Kind: mgmt.BoolAttribute, Required: false, Create: false, Update: false},
	{Name: "isEncrypted", Kind: mgmt.BoolAttribute, Required: false, Create: false, Update: false},
	{Name: "enableProtocolTrace", Kind: mgmt.BoolAttribute, Required: false, Create: false, Update: true, Default: false, HasDefault: true},
	{Name: "sasl", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "user", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "ssl", Kind: mgmt.BoolAttribute, Required: false, Create: false, Update: false},
	{Name: "sslProto", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "sslCipher", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "sslSsf", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "uptimeSeconds", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "properties", Kind: mgmt.MapAttribute, Required: false, Create: false, Update: false},
	{Name: "lastDlvSeconds", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "tlsOrdinal", Kind: mgmt.Uint64Attribute, Required: false, Create: false, Update: false},
	{Name: "groupCorrelationId", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "groupOrdinal", Kind: mgmt.Uint64Attribute, Required: false, Create: false, Update: false},
})

var ConnectionAllFields = mgmt.Fields(ConnectionName, ConnectionIdentity, ConnectionTypeField, ConnectionAdminStatus, ConnectionOperStatusField, ConnectionProtocol, ConnectionContainer, ConnectionOpened, ConnectionHost, ConnectionLocalSocket, ConnectionDir, ConnectionRole, ConnectionMeshId, ConnectionIsAuthenticated, ConnectionIsEncrypted, ConnectionEnableProtocolTrace, ConnectionSasl, ConnectionUser, ConnectionSsl, ConnectionSslProto, ConnectionSslCipher, ConnectionSslSsf, ConnectionUptimeSeconds, ConnectionProperties, ConnectionLastDlvSeconds, ConnectionTlsOrdinal, ConnectionGroupCorrelationId, ConnectionGroupOrdinal)

var ConnectionCreateFields mgmt.FieldSet[Connection]

var ConnectionUpdateFields = mgmt.Fields(ConnectionAdminStatus, ConnectionEnableProtocolTrace)

func (*Connection) ManagementType() *mgmt.Type { return ConnectionType }

func (e *Connection) SetManagementField(field mgmt.Field[Connection], value any) error {
	switch field {
	case ConnectionName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case ConnectionIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case ConnectionTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case ConnectionAdminStatus:
		decoded, ok := mgmt.AsEnum(value, adminStatusValues)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "adminStatus", value)
		}
		e.AdminStatus = AdminStatus(decoded)
		return nil
	case ConnectionOperStatusField:
		decoded, ok := mgmt.AsEnum(value, connectionOperStatusValues)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "operStatus", value)
		}
		e.OperStatus = ConnectionOperStatus(decoded)
		return nil
	case ConnectionProtocol:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "protocol", value)
		}
		e.Protocol = decoded
		return nil
	case ConnectionContainer:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "container", value)
		}
		e.Container = decoded
		return nil
	case ConnectionOpened:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "opened", value)
		}
		e.Opened = decoded
		return nil
	case ConnectionHost:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "host", value)
		}
		e.Host = decoded
		return nil
	case ConnectionLocalSocket:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "localSocket", value)
		}
		e.LocalSocket = decoded
		return nil
	case ConnectionDir:
		decoded, ok := mgmt.AsEnum(value, directionValues)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "dir", value)
		}
		e.Dir = Direction(decoded)
		return nil
	case ConnectionRole:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "role", value)
		}
		e.Role = decoded
		return nil
	case ConnectionMeshId:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "meshId", value)
		}
		e.MeshId = decoded
		return nil
	case ConnectionIsAuthenticated:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "isAuthenticated", value)
		}
		e.IsAuthenticated = decoded
		return nil
	case ConnectionIsEncrypted:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "isEncrypted", value)
		}
		e.IsEncrypted = decoded
		return nil
	case ConnectionEnableProtocolTrace:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "enableProtocolTrace", value)
		}
		e.EnableProtocolTrace = decoded
		return nil
	case ConnectionSasl:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "sasl", value)
		}
		e.Sasl = decoded
		return nil
	case ConnectionUser:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "user", value)
		}
		e.User = decoded
		return nil
	case ConnectionSsl:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "ssl", value)
		}
		e.Ssl = decoded
		return nil
	case ConnectionSslProto:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "sslProto", value)
		}
		e.SslProto = decoded
		return nil
	case ConnectionSslCipher:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "sslCipher", value)
		}
		e.SslCipher = decoded
		return nil
	case ConnectionSslSsf:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "sslSsf", value)
		}
		e.SslSsf = decoded
		return nil
	case ConnectionUptimeSeconds:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "uptimeSeconds", value)
		}
		e.UptimeSeconds = decoded
		return nil
	case ConnectionProperties:
		decoded, ok := mgmt.AsMap(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "properties", value)
		}
		e.Properties = decoded
		return nil
	case ConnectionLastDlvSeconds:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "lastDlvSeconds", value)
		}
		e.LastDlvSeconds = decoded
		return nil
	case ConnectionTlsOrdinal:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "tlsOrdinal", value)
		}
		e.TlsOrdinal = decoded
		return nil
	case ConnectionGroupCorrelationId:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "groupCorrelationId", value)
		}
		e.GroupCorrelationId = decoded
		return nil
	case ConnectionGroupOrdinal:
		decoded, ok := mgmt.AsUint64(value)
		if !ok {
			return mgmt.DecodeError(ConnectionType.Name, "groupOrdinal", value)
		}
		e.GroupOrdinal = decoded
		return nil
	}
	return mgmt.DecodeError(ConnectionType.Name, "<unknown>", value)
}

func (e *Connection) ManagementValue(field mgmt.Field[Connection]) any {
	switch field {
	case ConnectionName:
		return e.Name
	case ConnectionIdentity:
		return e.Identity
	case ConnectionTypeField:
		return e.Type
	case ConnectionAdminStatus:
		return string(e.AdminStatus)
	case ConnectionOperStatusField:
		return string(e.OperStatus)
	case ConnectionProtocol:
		return e.Protocol
	case ConnectionContainer:
		return e.Container
	case ConnectionOpened:
		return e.Opened
	case ConnectionHost:
		return e.Host
	case ConnectionLocalSocket:
		return e.LocalSocket
	case ConnectionDir:
		return string(e.Dir)
	case ConnectionRole:
		return e.Role
	case ConnectionMeshId:
		return e.MeshId
	case ConnectionIsAuthenticated:
		return e.IsAuthenticated
	case ConnectionIsEncrypted:
		return e.IsEncrypted
	case ConnectionEnableProtocolTrace:
		return e.EnableProtocolTrace
	case ConnectionSasl:
		return e.Sasl
	case ConnectionUser:
		return e.User
	case ConnectionSsl:
		return e.Ssl
	case ConnectionSslProto:
		return e.SslProto
	case ConnectionSslCipher:
		return e.SslCipher
	case ConnectionSslSsf:
		return e.SslSsf
	case ConnectionUptimeSeconds:
		return e.UptimeSeconds
	case ConnectionProperties:
		return e.Properties
	case ConnectionLastDlvSeconds:
		return e.LastDlvSeconds
	case ConnectionTlsOrdinal:
		return e.TlsOrdinal
	case ConnectionGroupCorrelationId:
		return e.GroupCorrelationId
	case ConnectionGroupOrdinal:
		return e.GroupOrdinal
	}
	return nil
}

func (e *Connection) Equal(other *Connection, fields mgmt.FieldSet[Connection]) bool {
	if fields.Has(ConnectionName) && e.Name != other.Name {
		return false
	}
	if fields.Has(ConnectionIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(ConnectionTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(ConnectionAdminStatus) && e.AdminStatus != other.AdminStatus {
		return false
	}
	if fields.Has(ConnectionOperStatusField) && e.OperStatus != other.OperStatus {
		return false
	}
	if fields.Has(ConnectionProtocol) && e.Protocol != other.Protocol {
		return false
	}
	if fields.Has(ConnectionContainer) && e.Container != other.Container {
		return false
	}
	if fields.Has(ConnectionOpened) && e.Opened != other.Opened {
		return false
	}
	if fields.Has(ConnectionHost) && e.Host != other.Host {
		return false
	}
	if fields.Has(ConnectionLocalSocket) && e.LocalSocket != other.LocalSocket {
		return false
	}
	if fields.Has(ConnectionDir) && e.Dir != other.Dir {
		return false
	}
	if fields.Has(ConnectionRole) && e.Role != other.Role {
		return false
	}
	if fields.Has(ConnectionMeshId) && e.MeshId != other.MeshId {
		return false
	}
	if fields.Has(ConnectionIsAuthenticated) && e.IsAuthenticated != other.IsAuthenticated {
		return false
	}
	if fields.Has(ConnectionIsEncrypted) && e.IsEncrypted != other.IsEncrypted {
		return false
	}
	if fields.Has(ConnectionEnableProtocolTrace) && e.EnableProtocolTrace != other.EnableProtocolTrace {
		return false
	}
	if fields.Has(ConnectionSasl) && e.Sasl != other.Sasl {
		return false
	}
	if fields.Has(ConnectionUser) && e.User != other.User {
		return false
	}
	if fields.Has(ConnectionSsl) && e.Ssl != other.Ssl {
		return false
	}
	if fields.Has(ConnectionSslProto) && e.SslProto != other.SslProto {
		return false
	}
	if fields.Has(ConnectionSslCipher) && e.SslCipher != other.SslCipher {
		return false
	}
	if fields.Has(ConnectionSslSsf) && e.SslSsf != other.SslSsf {
		return false
	}
	if fields.Has(ConnectionUptimeSeconds) && e.UptimeSeconds != other.UptimeSeconds {
		return false
	}
	if fields.Has(ConnectionProperties) && !mgmt.EqualValues(e.Properties, other.Properties) {
		return false
	}
	if fields.Has(ConnectionLastDlvSeconds) && e.LastDlvSeconds != other.LastDlvSeconds {
		return false
	}
	if fields.Has(ConnectionTlsOrdinal) && e.TlsOrdinal != other.TlsOrdinal {
		return false
	}
	if fields.Has(ConnectionGroupCorrelationId) && e.GroupCorrelationId != other.GroupCorrelationId {
		return false
	}
	if fields.Has(ConnectionGroupOrdinal) && e.GroupOrdinal != other.GroupOrdinal {
		return false
	}
	return true
}

func (e *Connection) Diff(other *Connection, fields mgmt.FieldSet[Connection]) mgmt.FieldSet[Connection] {
	var result mgmt.FieldSet[Connection]
	if fields.Has(ConnectionName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(ConnectionName))
	}
	if fields.Has(ConnectionIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(ConnectionIdentity))
	}
	if fields.Has(ConnectionTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(ConnectionTypeField))
	}
	if fields.Has(ConnectionAdminStatus) && e.AdminStatus != other.AdminStatus {
		result = result.Union(mgmt.Fields(ConnectionAdminStatus))
	}
	if fields.Has(ConnectionOperStatusField) && e.OperStatus != other.OperStatus {
		result = result.Union(mgmt.Fields(ConnectionOperStatusField))
	}
	if fields.Has(ConnectionProtocol) && e.Protocol != other.Protocol {
		result = result.Union(mgmt.Fields(ConnectionProtocol))
	}
	if fields.Has(ConnectionContainer) && e.Container != other.Container {
		result = result.Union(mgmt.Fields(ConnectionContainer))
	}
	if fields.Has(ConnectionOpened) && e.Opened != other.Opened {
		result = result.Union(mgmt.Fields(ConnectionOpened))
	}
	if fields.Has(ConnectionHost) && e.Host != other.Host {
		result = result.Union(mgmt.Fields(ConnectionHost))
	}
	if fields.Has(ConnectionLocalSocket) && e.LocalSocket != other.LocalSocket {
		result = result.Union(mgmt.Fields(ConnectionLocalSocket))
	}
	if fields.Has(ConnectionDir) && e.Dir != other.Dir {
		result = result.Union(mgmt.Fields(ConnectionDir))
	}
	if fields.Has(ConnectionRole) && e.Role != other.Role {
		result = result.Union(mgmt.Fields(ConnectionRole))
	}
	if fields.Has(ConnectionMeshId) && e.MeshId != other.MeshId {
		result = result.Union(mgmt.Fields(ConnectionMeshId))
	}
	if fields.Has(ConnectionIsAuthenticated) && e.IsAuthenticated != other.IsAuthenticated {
		result = result.Union(mgmt.Fields(ConnectionIsAuthenticated))
	}
	if fields.Has(ConnectionIsEncrypted) && e.IsEncrypted != other.IsEncrypted {
		result = result.Union(mgmt.Fields(ConnectionIsEncrypted))
	}
	if fields.Has(ConnectionEnableProtocolTrace) && e.EnableProtocolTrace != other.EnableProtocolTrace {
		result = result.Union(mgmt.Fields(ConnectionEnableProtocolTrace))
	}
	if fields.Has(ConnectionSasl) && e.Sasl != other.Sasl {
		result = result.Union(mgmt.Fields(ConnectionSasl))
	}
	if fields.Has(ConnectionUser) && e.User != other.User {
		result = result.Union(mgmt.Fields(ConnectionUser))
	}
	if fields.Has(ConnectionSsl) && e.Ssl != other.Ssl {
		result = result.Union(mgmt.Fields(ConnectionSsl))
	}
	if fields.Has(ConnectionSslProto) && e.SslProto != other.SslProto {
		result = result.Union(mgmt.Fields(ConnectionSslProto))
	}
	if fields.Has(ConnectionSslCipher) && e.SslCipher != other.SslCipher {
		result = result.Union(mgmt.Fields(ConnectionSslCipher))
	}
	if fields.Has(ConnectionSslSsf) && e.SslSsf != other.SslSsf {
		result = result.Union(mgmt.Fields(ConnectionSslSsf))
	}
	if fields.Has(ConnectionUptimeSeconds) && e.UptimeSeconds != other.UptimeSeconds {
		result = result.Union(mgmt.Fields(ConnectionUptimeSeconds))
	}
	if fields.Has(ConnectionProperties) && !mgmt.EqualValues(e.Properties, other.Properties) {
		result = result.Union(mgmt.Fields(ConnectionProperties))
	}
	if fields.Has(ConnectionLastDlvSeconds) && e.LastDlvSeconds != other.LastDlvSeconds {
		result = result.Union(mgmt.Fields(ConnectionLastDlvSeconds))
	}
	if fields.Has(ConnectionTlsOrdinal) && e.TlsOrdinal != other.TlsOrdinal {
		result = result.Union(mgmt.Fields(ConnectionTlsOrdinal))
	}
	if fields.Has(ConnectionGroupCorrelationId) && e.GroupCorrelationId != other.GroupCorrelationId {
		result = result.Union(mgmt.Fields(ConnectionGroupCorrelationId))
	}
	if fields.Has(ConnectionGroupOrdinal) && e.GroupOrdinal != other.GroupOrdinal {
		result = result.Union(mgmt.Fields(ConnectionGroupOrdinal))
	}
	return result
}

func (e *Connection) ApplyDefaults(present mgmt.FieldSet[Connection]) {
	if !present.Has(ConnectionTypeField) {
		e.Type = "io.skupper.router.connection"
	}
	if !present.Has(ConnectionAdminStatus) {
		e.AdminStatus = AdminStatus("enabled")
	}
	if !present.Has(ConnectionEnableProtocolTrace) {
		e.EnableProtocolTrace = false
	}
}

func (e *Connection) NonZeroFields() mgmt.FieldSet[Connection] {
	var result mgmt.FieldSet[Connection]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(ConnectionName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(ConnectionIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(ConnectionTypeField))
	}
	if e.AdminStatus != "" {
		result = result.Union(mgmt.Fields(ConnectionAdminStatus))
	}
	if e.OperStatus != "" {
		result = result.Union(mgmt.Fields(ConnectionOperStatusField))
	}
	if e.Protocol != "" {
		result = result.Union(mgmt.Fields(ConnectionProtocol))
	}
	if e.Container != "" {
		result = result.Union(mgmt.Fields(ConnectionContainer))
	}
	if e.Opened {
		result = result.Union(mgmt.Fields(ConnectionOpened))
	}
	if e.Host != "" {
		result = result.Union(mgmt.Fields(ConnectionHost))
	}
	if e.LocalSocket != "" {
		result = result.Union(mgmt.Fields(ConnectionLocalSocket))
	}
	if e.Dir != "" {
		result = result.Union(mgmt.Fields(ConnectionDir))
	}
	if e.Role != "" {
		result = result.Union(mgmt.Fields(ConnectionRole))
	}
	if e.MeshId != "" {
		result = result.Union(mgmt.Fields(ConnectionMeshId))
	}
	if e.IsAuthenticated {
		result = result.Union(mgmt.Fields(ConnectionIsAuthenticated))
	}
	if e.IsEncrypted {
		result = result.Union(mgmt.Fields(ConnectionIsEncrypted))
	}
	if e.EnableProtocolTrace {
		result = result.Union(mgmt.Fields(ConnectionEnableProtocolTrace))
	}
	if e.Sasl != "" {
		result = result.Union(mgmt.Fields(ConnectionSasl))
	}
	if e.User != "" {
		result = result.Union(mgmt.Fields(ConnectionUser))
	}
	if e.Ssl {
		result = result.Union(mgmt.Fields(ConnectionSsl))
	}
	if e.SslProto != "" {
		result = result.Union(mgmt.Fields(ConnectionSslProto))
	}
	if e.SslCipher != "" {
		result = result.Union(mgmt.Fields(ConnectionSslCipher))
	}
	if e.SslSsf != 0 {
		result = result.Union(mgmt.Fields(ConnectionSslSsf))
	}
	if e.UptimeSeconds != 0 {
		result = result.Union(mgmt.Fields(ConnectionUptimeSeconds))
	}
	if len(e.Properties) != 0 {
		result = result.Union(mgmt.Fields(ConnectionProperties))
	}
	if e.LastDlvSeconds != 0 {
		result = result.Union(mgmt.Fields(ConnectionLastDlvSeconds))
	}
	if e.TlsOrdinal != 0 {
		result = result.Union(mgmt.Fields(ConnectionTlsOrdinal))
	}
	if e.GroupCorrelationId != "" {
		result = result.Union(mgmt.Fields(ConnectionGroupCorrelationId))
	}
	if e.GroupOrdinal != 0 {
		result = result.Union(mgmt.Fields(ConnectionGroupOrdinal))
	}
	return result
}
