// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type RouterLink struct {
	Name                   string
	Identity               string
	Type                   string
	OperStatus             LinkOperStatus
	LinkName               string
	LinkType               LinkType
	LinkDir                Direction
	OwningAddr             string
	Capacity               int64
	UndeliveredCount       int64
	UnsettledCount         int64
	DeliveryCount          int64
	ConnectionId           int64
	PresettledCount        int64
	DroppedPresettledCount int64
	AcceptedCount          int64
	RejectedCount          int64
	ReleasedCount          int64
	ModifiedCount          int64
	DeliveriesDelayed1Sec  int64
	DeliveriesDelayed10Sec int64
	DeliveriesStuck        int64
	OpenMovedStreams       int64
	CreditAvailable        int64
	ZeroCreditSeconds      int64
	SettleRate             int64
	IngressHistogram       []int64
	Priority               int64
}

const (
	RouterLinkName mgmt.Field[RouterLink] = iota
	RouterLinkIdentity
	RouterLinkTypeField
	RouterLinkOperStatus
	RouterLinkLinkName
	RouterLinkLinkType
	RouterLinkLinkDir
	RouterLinkOwningAddr
	RouterLinkCapacity
	RouterLinkUndeliveredCount
	RouterLinkUnsettledCount
	RouterLinkDeliveryCount
	RouterLinkConnectionId
	RouterLinkPresettledCount
	RouterLinkDroppedPresettledCount
	RouterLinkAcceptedCount
	RouterLinkRejectedCount
	RouterLinkReleasedCount
	RouterLinkModifiedCount
	RouterLinkDeliveriesDelayed1Sec
	RouterLinkDeliveriesDelayed10Sec
	RouterLinkDeliveriesStuck
	RouterLinkOpenMovedStreams
	RouterLinkCreditAvailable
	RouterLinkZeroCreditSeconds
	RouterLinkSettleRate
	RouterLinkIngressHistogram
	RouterLinkPriority
)

var RouterLinkType = mgmt.NewType("io.skupper.router.router.link", "router.link", true, []string{"QUERY", "READ"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: false, Update: false, Default: "io.skupper.router.router.link", HasDefault: true},
	{Name: "operStatus", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false, Enum: linkOperStatusValues},
	{Name: "linkName", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "linkType", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false, Enum: linkTypeValues},
	{Name: "linkDir", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false, Enum: directionValues},
	{Name: "owningAddr", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "capacity", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "undeliveredCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "unsettledCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveryCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "connectionId", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "presettledCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "droppedPresettledCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "acceptedCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "rejectedCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "releasedCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "modifiedCount", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesDelayed1Sec", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesDelayed10Sec", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "deliveriesStuck", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "openMovedStreams", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "creditAvailable", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "zeroCreditSeconds", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "settleRate", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
	{Name: "ingressHistogram", Kind: mgmt.ListAttribute, Required: false, Create: false, Update: false},
	{Name: "priority", Kind: mgmt.Int64Attribute, Required: false, Create: false, Update: false},
})

var RouterLinkAllFields = mgmt.Fields(RouterLinkName, RouterLinkIdentity, RouterLinkTypeField, RouterLinkOperStatus, RouterLinkLinkName, RouterLinkLinkType, RouterLinkLinkDir, RouterLinkOwningAddr, RouterLinkCapacity, RouterLinkUndeliveredCount, RouterLinkUnsettledCount, RouterLinkDeliveryCount, RouterLinkConnectionId, RouterLinkPresettledCount, RouterLinkDroppedPresettledCount, RouterLinkAcceptedCount, RouterLinkRejectedCount, RouterLinkReleasedCount, RouterLinkModifiedCount, RouterLinkDeliveriesDelayed1Sec, RouterLinkDeliveriesDelayed10Sec, RouterLinkDeliveriesStuck, RouterLinkOpenMovedStreams, RouterLinkCreditAvailable, RouterLinkZeroCreditSeconds, RouterLinkSettleRate, RouterLinkIngressHistogram, RouterLinkPriority)

var RouterLinkCreateFields mgmt.FieldSet[RouterLink]

var RouterLinkUpdateFields mgmt.FieldSet[RouterLink]

func (*RouterLink) ManagementType() *mgmt.Type { return RouterLinkType }

func (e *RouterLink) SetManagementField(field mgmt.Field[RouterLink], value any) error {
	switch field {
	case RouterLinkName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case RouterLinkIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case RouterLinkTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case RouterLinkOperStatus:
		decoded, ok := mgmt.AsEnum(value, linkOperStatusValues)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "operStatus", value)
		}
		e.OperStatus = LinkOperStatus(decoded)
		return nil
	case RouterLinkLinkName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "linkName", value)
		}
		e.LinkName = decoded
		return nil
	case RouterLinkLinkType:
		decoded, ok := mgmt.AsEnum(value, linkTypeValues)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "linkType", value)
		}
		e.LinkType = LinkType(decoded)
		return nil
	case RouterLinkLinkDir:
		decoded, ok := mgmt.AsEnum(value, directionValues)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "linkDir", value)
		}
		e.LinkDir = Direction(decoded)
		return nil
	case RouterLinkOwningAddr:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "owningAddr", value)
		}
		e.OwningAddr = decoded
		return nil
	case RouterLinkCapacity:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "capacity", value)
		}
		e.Capacity = decoded
		return nil
	case RouterLinkUndeliveredCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "undeliveredCount", value)
		}
		e.UndeliveredCount = decoded
		return nil
	case RouterLinkUnsettledCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "unsettledCount", value)
		}
		e.UnsettledCount = decoded
		return nil
	case RouterLinkDeliveryCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "deliveryCount", value)
		}
		e.DeliveryCount = decoded
		return nil
	case RouterLinkConnectionId:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "connectionId", value)
		}
		e.ConnectionId = decoded
		return nil
	case RouterLinkPresettledCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "presettledCount", value)
		}
		e.PresettledCount = decoded
		return nil
	case RouterLinkDroppedPresettledCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "droppedPresettledCount", value)
		}
		e.DroppedPresettledCount = decoded
		return nil
	case RouterLinkAcceptedCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "acceptedCount", value)
		}
		e.AcceptedCount = decoded
		return nil
	case RouterLinkRejectedCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "rejectedCount", value)
		}
		e.RejectedCount = decoded
		return nil
	case RouterLinkReleasedCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "releasedCount", value)
		}
		e.ReleasedCount = decoded
		return nil
	case RouterLinkModifiedCount:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "modifiedCount", value)
		}
		e.ModifiedCount = decoded
		return nil
	case RouterLinkDeliveriesDelayed1Sec:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "deliveriesDelayed1Sec", value)
		}
		e.DeliveriesDelayed1Sec = decoded
		return nil
	case RouterLinkDeliveriesDelayed10Sec:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "deliveriesDelayed10Sec", value)
		}
		e.DeliveriesDelayed10Sec = decoded
		return nil
	case RouterLinkDeliveriesStuck:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "deliveriesStuck", value)
		}
		e.DeliveriesStuck = decoded
		return nil
	case RouterLinkOpenMovedStreams:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "openMovedStreams", value)
		}
		e.OpenMovedStreams = decoded
		return nil
	case RouterLinkCreditAvailable:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "creditAvailable", value)
		}
		e.CreditAvailable = decoded
		return nil
	case RouterLinkZeroCreditSeconds:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "zeroCreditSeconds", value)
		}
		e.ZeroCreditSeconds = decoded
		return nil
	case RouterLinkSettleRate:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "settleRate", value)
		}
		e.SettleRate = decoded
		return nil
	case RouterLinkIngressHistogram:
		decoded, ok := mgmt.AsInt64List(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "ingressHistogram", value)
		}
		e.IngressHistogram = decoded
		return nil
	case RouterLinkPriority:
		decoded, ok := mgmt.AsInt64(value)
		if !ok {
			return mgmt.DecodeError(RouterLinkType.Name, "priority", value)
		}
		e.Priority = decoded
		return nil
	}
	return mgmt.DecodeError(RouterLinkType.Name, "<unknown>", value)
}

func (e *RouterLink) ManagementValue(field mgmt.Field[RouterLink]) any {
	switch field {
	case RouterLinkName:
		return e.Name
	case RouterLinkIdentity:
		return e.Identity
	case RouterLinkTypeField:
		return e.Type
	case RouterLinkOperStatus:
		return string(e.OperStatus)
	case RouterLinkLinkName:
		return e.LinkName
	case RouterLinkLinkType:
		return string(e.LinkType)
	case RouterLinkLinkDir:
		return string(e.LinkDir)
	case RouterLinkOwningAddr:
		return e.OwningAddr
	case RouterLinkCapacity:
		return e.Capacity
	case RouterLinkUndeliveredCount:
		return e.UndeliveredCount
	case RouterLinkUnsettledCount:
		return e.UnsettledCount
	case RouterLinkDeliveryCount:
		return e.DeliveryCount
	case RouterLinkConnectionId:
		return e.ConnectionId
	case RouterLinkPresettledCount:
		return e.PresettledCount
	case RouterLinkDroppedPresettledCount:
		return e.DroppedPresettledCount
	case RouterLinkAcceptedCount:
		return e.AcceptedCount
	case RouterLinkRejectedCount:
		return e.RejectedCount
	case RouterLinkReleasedCount:
		return e.ReleasedCount
	case RouterLinkModifiedCount:
		return e.ModifiedCount
	case RouterLinkDeliveriesDelayed1Sec:
		return e.DeliveriesDelayed1Sec
	case RouterLinkDeliveriesDelayed10Sec:
		return e.DeliveriesDelayed10Sec
	case RouterLinkDeliveriesStuck:
		return e.DeliveriesStuck
	case RouterLinkOpenMovedStreams:
		return e.OpenMovedStreams
	case RouterLinkCreditAvailable:
		return e.CreditAvailable
	case RouterLinkZeroCreditSeconds:
		return e.ZeroCreditSeconds
	case RouterLinkSettleRate:
		return e.SettleRate
	case RouterLinkIngressHistogram:
		return e.IngressHistogram
	case RouterLinkPriority:
		return e.Priority
	}
	return nil
}

func (e *RouterLink) Equal(other *RouterLink, fields mgmt.FieldSet[RouterLink]) bool {
	if fields.Has(RouterLinkName) && e.Name != other.Name {
		return false
	}
	if fields.Has(RouterLinkIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(RouterLinkTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(RouterLinkOperStatus) && e.OperStatus != other.OperStatus {
		return false
	}
	if fields.Has(RouterLinkLinkName) && e.LinkName != other.LinkName {
		return false
	}
	if fields.Has(RouterLinkLinkType) && e.LinkType != other.LinkType {
		return false
	}
	if fields.Has(RouterLinkLinkDir) && e.LinkDir != other.LinkDir {
		return false
	}
	if fields.Has(RouterLinkOwningAddr) && e.OwningAddr != other.OwningAddr {
		return false
	}
	if fields.Has(RouterLinkCapacity) && e.Capacity != other.Capacity {
		return false
	}
	if fields.Has(RouterLinkUndeliveredCount) && e.UndeliveredCount != other.UndeliveredCount {
		return false
	}
	if fields.Has(RouterLinkUnsettledCount) && e.UnsettledCount != other.UnsettledCount {
		return false
	}
	if fields.Has(RouterLinkDeliveryCount) && e.DeliveryCount != other.DeliveryCount {
		return false
	}
	if fields.Has(RouterLinkConnectionId) && e.ConnectionId != other.ConnectionId {
		return false
	}
	if fields.Has(RouterLinkPresettledCount) && e.PresettledCount != other.PresettledCount {
		return false
	}
	if fields.Has(RouterLinkDroppedPresettledCount) && e.DroppedPresettledCount != other.DroppedPresettledCount {
		return false
	}
	if fields.Has(RouterLinkAcceptedCount) && e.AcceptedCount != other.AcceptedCount {
		return false
	}
	if fields.Has(RouterLinkRejectedCount) && e.RejectedCount != other.RejectedCount {
		return false
	}
	if fields.Has(RouterLinkReleasedCount) && e.ReleasedCount != other.ReleasedCount {
		return false
	}
	if fields.Has(RouterLinkModifiedCount) && e.ModifiedCount != other.ModifiedCount {
		return false
	}
	if fields.Has(RouterLinkDeliveriesDelayed1Sec) && e.DeliveriesDelayed1Sec != other.DeliveriesDelayed1Sec {
		return false
	}
	if fields.Has(RouterLinkDeliveriesDelayed10Sec) && e.DeliveriesDelayed10Sec != other.DeliveriesDelayed10Sec {
		return false
	}
	if fields.Has(RouterLinkDeliveriesStuck) && e.DeliveriesStuck != other.DeliveriesStuck {
		return false
	}
	if fields.Has(RouterLinkOpenMovedStreams) && e.OpenMovedStreams != other.OpenMovedStreams {
		return false
	}
	if fields.Has(RouterLinkCreditAvailable) && e.CreditAvailable != other.CreditAvailable {
		return false
	}
	if fields.Has(RouterLinkZeroCreditSeconds) && e.ZeroCreditSeconds != other.ZeroCreditSeconds {
		return false
	}
	if fields.Has(RouterLinkSettleRate) && e.SettleRate != other.SettleRate {
		return false
	}
	if fields.Has(RouterLinkIngressHistogram) && !mgmt.EqualValues(e.IngressHistogram, other.IngressHistogram) {
		return false
	}
	if fields.Has(RouterLinkPriority) && e.Priority != other.Priority {
		return false
	}
	return true
}

func (e *RouterLink) Diff(other *RouterLink, fields mgmt.FieldSet[RouterLink]) mgmt.FieldSet[RouterLink] {
	var result mgmt.FieldSet[RouterLink]
	if fields.Has(RouterLinkName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(RouterLinkName))
	}
	if fields.Has(RouterLinkIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(RouterLinkIdentity))
	}
	if fields.Has(RouterLinkTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(RouterLinkTypeField))
	}
	if fields.Has(RouterLinkOperStatus) && e.OperStatus != other.OperStatus {
		result = result.Union(mgmt.Fields(RouterLinkOperStatus))
	}
	if fields.Has(RouterLinkLinkName) && e.LinkName != other.LinkName {
		result = result.Union(mgmt.Fields(RouterLinkLinkName))
	}
	if fields.Has(RouterLinkLinkType) && e.LinkType != other.LinkType {
		result = result.Union(mgmt.Fields(RouterLinkLinkType))
	}
	if fields.Has(RouterLinkLinkDir) && e.LinkDir != other.LinkDir {
		result = result.Union(mgmt.Fields(RouterLinkLinkDir))
	}
	if fields.Has(RouterLinkOwningAddr) && e.OwningAddr != other.OwningAddr {
		result = result.Union(mgmt.Fields(RouterLinkOwningAddr))
	}
	if fields.Has(RouterLinkCapacity) && e.Capacity != other.Capacity {
		result = result.Union(mgmt.Fields(RouterLinkCapacity))
	}
	if fields.Has(RouterLinkUndeliveredCount) && e.UndeliveredCount != other.UndeliveredCount {
		result = result.Union(mgmt.Fields(RouterLinkUndeliveredCount))
	}
	if fields.Has(RouterLinkUnsettledCount) && e.UnsettledCount != other.UnsettledCount {
		result = result.Union(mgmt.Fields(RouterLinkUnsettledCount))
	}
	if fields.Has(RouterLinkDeliveryCount) && e.DeliveryCount != other.DeliveryCount {
		result = result.Union(mgmt.Fields(RouterLinkDeliveryCount))
	}
	if fields.Has(RouterLinkConnectionId) && e.ConnectionId != other.ConnectionId {
		result = result.Union(mgmt.Fields(RouterLinkConnectionId))
	}
	if fields.Has(RouterLinkPresettledCount) && e.PresettledCount != other.PresettledCount {
		result = result.Union(mgmt.Fields(RouterLinkPresettledCount))
	}
	if fields.Has(RouterLinkDroppedPresettledCount) && e.DroppedPresettledCount != other.DroppedPresettledCount {
		result = result.Union(mgmt.Fields(RouterLinkDroppedPresettledCount))
	}
	if fields.Has(RouterLinkAcceptedCount) && e.AcceptedCount != other.AcceptedCount {
		result = result.Union(mgmt.Fields(RouterLinkAcceptedCount))
	}
	if fields.Has(RouterLinkRejectedCount) && e.RejectedCount != other.RejectedCount {
		result = result.Union(mgmt.Fields(RouterLinkRejectedCount))
	}
	if fields.Has(RouterLinkReleasedCount) && e.ReleasedCount != other.ReleasedCount {
		result = result.Union(mgmt.Fields(RouterLinkReleasedCount))
	}
	if fields.Has(RouterLinkModifiedCount) && e.ModifiedCount != other.ModifiedCount {
		result = result.Union(mgmt.Fields(RouterLinkModifiedCount))
	}
	if fields.Has(RouterLinkDeliveriesDelayed1Sec) && e.DeliveriesDelayed1Sec != other.DeliveriesDelayed1Sec {
		result = result.Union(mgmt.Fields(RouterLinkDeliveriesDelayed1Sec))
	}
	if fields.Has(RouterLinkDeliveriesDelayed10Sec) && e.DeliveriesDelayed10Sec != other.DeliveriesDelayed10Sec {
		result = result.Union(mgmt.Fields(RouterLinkDeliveriesDelayed10Sec))
	}
	if fields.Has(RouterLinkDeliveriesStuck) && e.DeliveriesStuck != other.DeliveriesStuck {
		result = result.Union(mgmt.Fields(RouterLinkDeliveriesStuck))
	}
	if fields.Has(RouterLinkOpenMovedStreams) && e.OpenMovedStreams != other.OpenMovedStreams {
		result = result.Union(mgmt.Fields(RouterLinkOpenMovedStreams))
	}
	if fields.Has(RouterLinkCreditAvailable) && e.CreditAvailable != other.CreditAvailable {
		result = result.Union(mgmt.Fields(RouterLinkCreditAvailable))
	}
	if fields.Has(RouterLinkZeroCreditSeconds) && e.ZeroCreditSeconds != other.ZeroCreditSeconds {
		result = result.Union(mgmt.Fields(RouterLinkZeroCreditSeconds))
	}
	if fields.Has(RouterLinkSettleRate) && e.SettleRate != other.SettleRate {
		result = result.Union(mgmt.Fields(RouterLinkSettleRate))
	}
	if fields.Has(RouterLinkIngressHistogram) && !mgmt.EqualValues(e.IngressHistogram, other.IngressHistogram) {
		result = result.Union(mgmt.Fields(RouterLinkIngressHistogram))
	}
	if fields.Has(RouterLinkPriority) && e.Priority != other.Priority {
		result = result.Union(mgmt.Fields(RouterLinkPriority))
	}
	return result
}

func (e *RouterLink) ApplyDefaults(present mgmt.FieldSet[RouterLink]) {
	if !present.Has(RouterLinkTypeField) {
		e.Type = "io.skupper.router.router.link"
	}
}

func (e *RouterLink) NonZeroFields() mgmt.FieldSet[RouterLink] {
	var result mgmt.FieldSet[RouterLink]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(RouterLinkName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(RouterLinkIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(RouterLinkTypeField))
	}
	if e.OperStatus != "" {
		result = result.Union(mgmt.Fields(RouterLinkOperStatus))
	}
	if e.LinkName != "" {
		result = result.Union(mgmt.Fields(RouterLinkLinkName))
	}
	if e.LinkType != "" {
		result = result.Union(mgmt.Fields(RouterLinkLinkType))
	}
	if e.LinkDir != "" {
		result = result.Union(mgmt.Fields(RouterLinkLinkDir))
	}
	if e.OwningAddr != "" {
		result = result.Union(mgmt.Fields(RouterLinkOwningAddr))
	}
	if e.Capacity != 0 {
		result = result.Union(mgmt.Fields(RouterLinkCapacity))
	}
	if e.UndeliveredCount != 0 {
		result = result.Union(mgmt.Fields(RouterLinkUndeliveredCount))
	}
	if e.UnsettledCount != 0 {
		result = result.Union(mgmt.Fields(RouterLinkUnsettledCount))
	}
	if e.DeliveryCount != 0 {
		result = result.Union(mgmt.Fields(RouterLinkDeliveryCount))
	}
	if e.ConnectionId != 0 {
		result = result.Union(mgmt.Fields(RouterLinkConnectionId))
	}
	if e.PresettledCount != 0 {
		result = result.Union(mgmt.Fields(RouterLinkPresettledCount))
	}
	if e.DroppedPresettledCount != 0 {
		result = result.Union(mgmt.Fields(RouterLinkDroppedPresettledCount))
	}
	if e.AcceptedCount != 0 {
		result = result.Union(mgmt.Fields(RouterLinkAcceptedCount))
	}
	if e.RejectedCount != 0 {
		result = result.Union(mgmt.Fields(RouterLinkRejectedCount))
	}
	if e.ReleasedCount != 0 {
		result = result.Union(mgmt.Fields(RouterLinkReleasedCount))
	}
	if e.ModifiedCount != 0 {
		result = result.Union(mgmt.Fields(RouterLinkModifiedCount))
	}
	if e.DeliveriesDelayed1Sec != 0 {
		result = result.Union(mgmt.Fields(RouterLinkDeliveriesDelayed1Sec))
	}
	if e.DeliveriesDelayed10Sec != 0 {
		result = result.Union(mgmt.Fields(RouterLinkDeliveriesDelayed10Sec))
	}
	if e.DeliveriesStuck != 0 {
		result = result.Union(mgmt.Fields(RouterLinkDeliveriesStuck))
	}
	if e.OpenMovedStreams != 0 {
		result = result.Union(mgmt.Fields(RouterLinkOpenMovedStreams))
	}
	if e.CreditAvailable != 0 {
		result = result.Union(mgmt.Fields(RouterLinkCreditAvailable))
	}
	if e.ZeroCreditSeconds != 0 {
		result = result.Union(mgmt.Fields(RouterLinkZeroCreditSeconds))
	}
	if e.SettleRate != 0 {
		result = result.Union(mgmt.Fields(RouterLinkSettleRate))
	}
	if len(e.IngressHistogram) != 0 {
		result = result.Union(mgmt.Fields(RouterLinkIngressHistogram))
	}
	if e.Priority != 0 {
		result = result.Union(mgmt.Fields(RouterLinkPriority))
	}
	return result
}
