// Code generated by go generate; DO NOT EDIT.
// Skupper Router schema commit: 84aa0b7b5774b84edcadc712751fe887e4883f6f

package entities

import "github.com/skupperproject/skupper/pkg/skrouter/mgmt"

type Log struct {
	Name             string
	Identity         string
	Type             string
	Module           LogModule
	Enable           string
	IncludeTimestamp bool
	IncludeSource    bool
	OutputFile       string
}

const (
	LogName mgmt.Field[Log] = iota
	LogIdentity
	LogTypeField
	LogModuleField
	LogEnable
	LogIncludeTimestamp
	LogIncludeSource
	LogOutputFile
)

var LogType = mgmt.NewType("io.skupper.router.log", "log", false, []string{"QUERY", "READ", "UPDATE"}, []mgmt.Attribute{
	{Name: "name", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "identity", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: false},
	{Name: "type", Kind: mgmt.StringAttribute, Required: true, Create: false, Update: false, Default: "io.skupper.router.log", HasDefault: true},
	{Name: "module", Kind: mgmt.StringAttribute, Required: true, Create: false, Update: false, Enum: logModuleValues},
	{Name: "enable", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: true},
	{Name: "includeTimestamp", Kind: mgmt.BoolAttribute, Required: false, Create: false, Update: true},
	{Name: "includeSource", Kind: mgmt.BoolAttribute, Required: false, Create: false, Update: true},
	{Name: "outputFile", Kind: mgmt.StringAttribute, Required: false, Create: false, Update: true},
})

var LogAllFields = mgmt.Fields(LogName, LogIdentity, LogTypeField, LogModuleField, LogEnable, LogIncludeTimestamp, LogIncludeSource, LogOutputFile)

var LogCreateFields mgmt.FieldSet[Log]

var LogUpdateFields = mgmt.Fields(LogEnable, LogIncludeTimestamp, LogIncludeSource, LogOutputFile)

func (*Log) ManagementType() *mgmt.Type { return LogType }

func (e *Log) SetManagementField(field mgmt.Field[Log], value any) error {
	switch field {
	case LogName:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(LogType.Name, "name", value)
		}
		e.Name = decoded
		return nil
	case LogIdentity:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(LogType.Name, "identity", value)
		}
		e.Identity = decoded
		return nil
	case LogTypeField:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(LogType.Name, "type", value)
		}
		e.Type = decoded
		return nil
	case LogModuleField:
		decoded, ok := mgmt.AsEnum(value, logModuleValues)
		if !ok {
			return mgmt.DecodeError(LogType.Name, "module", value)
		}
		e.Module = LogModule(decoded)
		return nil
	case LogEnable:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(LogType.Name, "enable", value)
		}
		e.Enable = decoded
		return nil
	case LogIncludeTimestamp:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(LogType.Name, "includeTimestamp", value)
		}
		e.IncludeTimestamp = decoded
		return nil
	case LogIncludeSource:
		decoded, ok := mgmt.AsBool(value)
		if !ok {
			return mgmt.DecodeError(LogType.Name, "includeSource", value)
		}
		e.IncludeSource = decoded
		return nil
	case LogOutputFile:
		decoded, ok := mgmt.AsString(value)
		if !ok {
			return mgmt.DecodeError(LogType.Name, "outputFile", value)
		}
		e.OutputFile = decoded
		return nil
	}
	return mgmt.DecodeError(LogType.Name, "<unknown>", value)
}

func (e *Log) ManagementValue(field mgmt.Field[Log]) any {
	switch field {
	case LogName:
		return e.Name
	case LogIdentity:
		return e.Identity
	case LogTypeField:
		return e.Type
	case LogModuleField:
		return string(e.Module)
	case LogEnable:
		return e.Enable
	case LogIncludeTimestamp:
		return e.IncludeTimestamp
	case LogIncludeSource:
		return e.IncludeSource
	case LogOutputFile:
		return e.OutputFile
	}
	return nil
}

func (e *Log) Equal(other *Log, fields mgmt.FieldSet[Log]) bool {
	if fields.Has(LogName) && e.Name != other.Name {
		return false
	}
	if fields.Has(LogIdentity) && e.Identity != other.Identity {
		return false
	}
	if fields.Has(LogTypeField) && e.Type != other.Type {
		return false
	}
	if fields.Has(LogModuleField) && e.Module != other.Module {
		return false
	}
	if fields.Has(LogEnable) && e.Enable != other.Enable {
		return false
	}
	if fields.Has(LogIncludeTimestamp) && e.IncludeTimestamp != other.IncludeTimestamp {
		return false
	}
	if fields.Has(LogIncludeSource) && e.IncludeSource != other.IncludeSource {
		return false
	}
	if fields.Has(LogOutputFile) && e.OutputFile != other.OutputFile {
		return false
	}
	return true
}

func (e *Log) Diff(other *Log, fields mgmt.FieldSet[Log]) mgmt.FieldSet[Log] {
	var result mgmt.FieldSet[Log]
	if fields.Has(LogName) && e.Name != other.Name {
		result = result.Union(mgmt.Fields(LogName))
	}
	if fields.Has(LogIdentity) && e.Identity != other.Identity {
		result = result.Union(mgmt.Fields(LogIdentity))
	}
	if fields.Has(LogTypeField) && e.Type != other.Type {
		result = result.Union(mgmt.Fields(LogTypeField))
	}
	if fields.Has(LogModuleField) && e.Module != other.Module {
		result = result.Union(mgmt.Fields(LogModuleField))
	}
	if fields.Has(LogEnable) && e.Enable != other.Enable {
		result = result.Union(mgmt.Fields(LogEnable))
	}
	if fields.Has(LogIncludeTimestamp) && e.IncludeTimestamp != other.IncludeTimestamp {
		result = result.Union(mgmt.Fields(LogIncludeTimestamp))
	}
	if fields.Has(LogIncludeSource) && e.IncludeSource != other.IncludeSource {
		result = result.Union(mgmt.Fields(LogIncludeSource))
	}
	if fields.Has(LogOutputFile) && e.OutputFile != other.OutputFile {
		result = result.Union(mgmt.Fields(LogOutputFile))
	}
	return result
}

func (e *Log) ApplyDefaults(present mgmt.FieldSet[Log]) {
	if !present.Has(LogTypeField) {
		e.Type = "io.skupper.router.log"
	}
}

func (e *Log) NonZeroFields() mgmt.FieldSet[Log] {
	var result mgmt.FieldSet[Log]
	if e.Name != "" {
		result = result.Union(mgmt.Fields(LogName))
	}
	if e.Identity != "" {
		result = result.Union(mgmt.Fields(LogIdentity))
	}
	if e.Type != "" {
		result = result.Union(mgmt.Fields(LogTypeField))
	}
	if e.Module != "" {
		result = result.Union(mgmt.Fields(LogModuleField))
	}
	if e.Enable != "" {
		result = result.Union(mgmt.Fields(LogEnable))
	}
	if e.IncludeTimestamp {
		result = result.Union(mgmt.Fields(LogIncludeTimestamp))
	}
	if e.IncludeSource {
		result = result.Union(mgmt.Fields(LogIncludeSource))
	}
	if e.OutputFile != "" {
		result = result.Union(mgmt.Fields(LogOutputFile))
	}
	return result
}
