package mgmt

import (
	"fmt"
	"sync"
)

// Field identifies an attribute of E. Field values are generated by the
// entities package and are only meaningful for their entity type.
type Field[E any] uint8

// FieldSet records which attributes of E are present or requested.
type FieldSet[E any] uint64

// Fields returns a set containing fields.
func Fields[E any](fields ...Field[E]) FieldSet[E] {
	var result FieldSet[E]
	for _, field := range fields {
		result |= 1 << field
	}
	return result
}

// Has reports whether field is in the set.
func (s FieldSet[E]) Has(field Field[E]) bool {
	return s&(1<<field) != 0
}

// Union returns the fields present in either set.
func (s FieldSet[E]) Union(other FieldSet[E]) FieldSet[E] {
	return s | other
}

// Intersect returns the fields present in both sets.
func (s FieldSet[E]) Intersect(other FieldSet[E]) FieldSet[E] {
	return s & other
}

// Without returns the fields in s that are not in other.
func (s FieldSet[E]) Without(other FieldSet[E]) FieldSet[E] {
	return s &^ other
}

// Partial pairs an entity value with the fields that are deliberately
// present. It can therefore represent false, zero, and empty values.
type Partial[E any] struct {
	Value  E
	Fields FieldSet[E]
}

// AttributeKind is the wire-neutral representation of an entity attribute.
type AttributeKind uint8

const (
	StringAttribute AttributeKind = iota
	Int64Attribute
	Uint64Attribute
	BoolAttribute
	ListAttribute
	MapAttribute
)

// Attribute describes one router management attribute.
type Attribute struct {
	Name       string
	Kind       AttributeKind
	Required   bool
	Create     bool
	Update     bool
	Default    any
	HasDefault bool
	Enum       []string
}

// Type contains generated management metadata for one entity type.
type Type struct {
	Name       string
	Short      string
	Core       bool
	Operations []string
	Attributes []Attribute

	byName       map[string]uint8
	allFields    uint64
	createFields uint64
	updateFields uint64
}

var typesByName sync.Map

// NewType constructs generated entity metadata.
func NewType(name, short string, core bool, operations []string, attributes []Attribute) *Type {
	if len(attributes) > 64 {
		panic(fmt.Sprintf("management type %s has %d attributes; FieldSet supports at most 64", name, len(attributes)))
	}
	t := &Type{
		Name:       name,
		Short:      short,
		Core:       core,
		Operations: append([]string(nil), operations...),
		Attributes: append([]Attribute(nil), attributes...),
		byName:     make(map[string]uint8, len(attributes)),
	}
	for i, attribute := range attributes {
		t.byName[attribute.Name] = uint8(i)
		bit := uint64(1) << i
		t.allFields |= bit
		if attribute.Create {
			t.createFields |= bit
		}
		if attribute.Update {
			t.updateFields |= bit
		}
	}
	if previous, loaded := typesByName.LoadOrStore(name, t); loaded && previous != t {
		panic(fmt.Sprintf("management metadata already registered for %s", name))
	}
	return t
}

// Supports reports whether the type supports operation.
func (t *Type) Supports(operation string) bool {
	for _, candidate := range t.Operations {
		if candidate == operation {
			return true
		}
	}
	return false
}

// Attribute returns metadata for a router attribute.
func (t *Type) Attribute(name string) (Attribute, bool) {
	ordinal, ok := t.byName[name]
	if !ok {
		return Attribute{}, false
	}
	return t.Attributes[ordinal], true
}

func (t *Type) names(bits uint64) []string {
	result := make([]string, 0, len(t.Attributes))
	for i, attribute := range t.Attributes {
		if bits&(uint64(1)<<i) != 0 {
			result = append(result, attribute.Name)
		}
	}
	return result
}

// TypeByName returns registered metadata for a router wire type name.
func TypeByName(name string) (*Type, bool) {
	typ, ok := typesByName.Load(name)
	if !ok {
		return nil, false
	}
	return typ.(*Type), true
}

// Entity is implemented by generated pointer types. The second type parameter
// on CRUD functions is inferred from E, so callers only name the value type.
type Entity[E any] interface {
	*E
	ManagementType() *Type
	SetManagementField(Field[E], any) error
	ManagementValue(Field[E]) any
}

// TypeOf returns generated metadata for E.
func TypeOf[E any, PE Entity[E]]() *Type {
	var value E
	return PE(&value).ManagementType()
}

// Names returns the router attribute names in schema order.
func Names[E any, PE Entity[E]](fields FieldSet[E]) []string {
	return TypeOf[E, PE]().names(uint64(fields))
}
