---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: network-console-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: network-console-cert
spec:
  commonName: network-console
  secretName: network-console-certs
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: network-console-issuer
    kind: Issuer
    group: cert-manager.io
