apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: network-console
  name: network-console
spec:
  tls:
    termination: passthrough
  port:
    targetPort: 8010
  to:
    kind: Service
    name: network-console
    weight: 100
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: network-console
  name: network-console
spec:
  ports:
  - port: 8010
    protocol: TCP
    targetPort: 8010
  selector:
    app: network-console
  type: ClusterIP
