---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: network-console
  name: network-console
spec:
  ports:
  - port: 8010
    protocol: TCP
    targetPort: 8010
  selector:
    app: network-console
  type: LoadBalancer

