// Code generated by github.com/skupperproject/skupper/cmd/network-console-controller/codegen. DO NOT EDIT
package api

// Set result
func (r *AddressListResponse) Set(e []AddressRecord) {
	r.Results = e
}

// Set result
func (r *AddressResponse) Set(e *AddressRecord) {
	r.Results = e
}

// Set result
func (r *ConnectorListResponse) Set(e []ConnectorRecord) {
	r.Results = e
}

// Set result
func (r *ConnectorResponse) Set(e *ConnectorRecord) {
	r.Results = e
}

// Set result
func (r *FlowAggregateListResponse) Set(e []FlowAggregateRecord) {
	r.Results = e
}

// Set result
func (r *FlowAggregateResponse) Set(e *FlowAggregateRecord) {
	r.Results = e
}

// Set result
func (r *LinkListResponse) Set(e []LinkRecord) {
	r.Results = e
}

// Set result
func (r *LinkResponse) Set(e *LinkRecord) {
	r.Results = e
}

// Set result
func (r *ListenerListResponse) Set(e []ListenerRecord) {
	r.Results = e
}

// Set result
func (r *ListenerResponse) Set(e *ListenerRecord) {
	r.Results = e
}

// Set result
func (r *ProcessGroupListResponse) Set(e []ProcessGroupRecord) {
	r.Results = e
}

// Set result
func (r *ProcessGroupResponse) Set(e *ProcessGroupRecord) {
	r.Results = e
}

// Set result
func (r *ProcessListResponse) Set(e []ProcessRecord) {
	r.Results = e
}

// Set result
func (r *ProcessResponse) Set(e *ProcessRecord) {
	r.Results = e
}

// Set result
func (r *RouterAccessListResponse) Set(e []RouterAccessRecord) {
	r.Results = e
}

// Set result
func (r *RouterAccessResponse) Set(e *RouterAccessRecord) {
	r.Results = e
}

// Set result
func (r *RouterLinkListResponse) Set(e []RouterLinkRecord) {
	r.Results = e
}

// Set result
func (r *RouterLinkResponse) Set(e *RouterLinkRecord) {
	r.Results = e
}

// Set result
func (r *RouterListResponse) Set(e []RouterRecord) {
	r.Results = e
}

// Set result
func (r *RouterResponse) Set(e *RouterRecord) {
	r.Results = e
}

// Set result
func (r *SiteListResponse) Set(e []SiteRecord) {
	r.Results = e
}

// Set result
func (r *SiteResponse) Set(e *SiteRecord) {
	r.Results = e
}

// Set result
func (r *TransportFlowListResponse) Set(e []TransportFlowRecord) {
	r.Results = e
}
